:- initialization(main).
main :-
    name(foo, C1),
    writeq(C1), nl,
    name(123, C2),
    writeq(C2), nl,
    name(-42, C3),
    writeq(C3), nl,
    name(X4, "hello"),
    writeq(X4), nl,
    name(X5, "123"),
    ( integer(X5) -> writeq(X5-int) ; writeq(X5-other) ), nl,
    name(X6, "-42"),
    ( integer(X6) -> writeq(X6-int) ; writeq(X6-other) ), nl,
    name(X7, "12abc"),
    ( atom(X7) -> writeq(X7-atom) ; writeq(X7-other) ), nl,
    name(X8, ""),
    writeq(X8), nl,
    ( name(bar, [0'b,0'a,0'r]) -> writeq(roundtrip_ok) ; writeq(roundtrip_fail) ), nl,
    write(done), nl,
    halt.
