; generated by scrip-cc -pl -asm
; compile: nasm -f elf64 prog.s -o prog.o
; link:    gcc -no-pie prog.o \
;            src/frontend/prolog/prolog_atom.o \
;            src/frontend/prolog/prolog_unify.o \
;            src/frontend/prolog/prolog_builtin.o \
;            -o prog

global  main
extern  prolog_atom_init, prolog_atom_intern
extern  trail_init, trail_mark_fn, trail_unwind, trail_push
extern  unify
extern  term_new_atom, term_new_var, term_new_int, term_new_float
extern  term_new_compound
extern  pl_write, pl_writeln
extern  pl_is, pl_num_lt, pl_num_gt, pl_num_le, pl_num_ge, pl_num_eq, pl_num_ne
extern  pl_functor, pl_arg, pl_univ
extern  pl_atom, pl_integer, pl_is_float, pl_var, pl_nonvar, pl_compound
extern  printf, fflush, putchar, exit


section .note.GNU-stack noalloc noexec nowrite progbits

section .bss
pl_trail                         resb 32    ; Trail struct (top+cap+stack ptr)
pl_tmp                           resq 1     ; scratch qword
pl_head_args                     resq 8     ; head arg scratch (8 slots, max arity)
global  cursor, subject_data, subject_len_val
cursor                           resq 1     ; SNOBOL4 pattern cursor (unused in Prolog)
subject_len_val                  resq 1     ; SNOBOL4 subject length (unused in Prolog)
subject_data                     resb 65536 ; SNOBOL4 subject buffer  (unused in Prolog)

section .text


; ============================================================
; predicate sentence/2  (1 clause)
; ============================================================
global pl_sentence_sl_2_r
pl_sentence_sl_2_r:
                            push        rbp
                            mov         rbp, rsp
                            sub         rsp, 96
                            mov         byte [rbp - 17], 0    ; _cut = 0
                            mov         [rbp - 24], rdi     ; save args array ptr
                            mov         [rbp - 32], rdx     ; save start
                            xor         eax, eax
                            mov         [rbp - 16], eax        ; sub_cs_acc = 0
                            mov         eax, [rbp - 32]       ; start value
                            cmp         eax, 0
                            jge         pl_sentence_sl_2_c0_α
                            jmp         pl_sentence_sl_2_ω

; --- clause 1/1  n_vars=3 body_ucalls=2 ---
; clause 0 entry
pl_sentence_sl_2_c0_α:
                            mov         rdi, 0
                            call        term_new_var
                            mov         [rbp - 72], rax    ; var slot 0
                            mov         rdi, 1
                            call        term_new_var
                            mov         [rbp - 80], rax    ; var slot 1
                            mov         rdi, 2
                            call        term_new_var
                            mov         [rbp - 88], rax    ; var slot 2
                            lea         rdi, [rel pl_trail]
                            call        trail_mark_fn
                            mov         [rbp - 8], eax          ; clause trail mark
                            mov         dword [rbp - 40], 0  ; init sub_cs slot 0
                            mov         dword [rbp - 48], 0  ; init sub_cs slot 1
                            mov         rax, [rbp - 24]     ; args array ptr
                            mov         rax, [rax + 0]     ; args[0]
                            mov         [rel pl_head_args + 0], rax  ; save call arg[0]
                            mov         rax, [rbp - 72]  ; var slot 0 (_V0)
                            mov         rsi, rax            ; head pattern
                            mov         rdi, [rel pl_head_args + 0]  ; restore call arg[0]
                            lea         rdx, [rel pl_trail]
                            call        unify
                            test        eax, eax
                            jnz         pl_sentence_sl_2_c0_hγ0
pl_sentence_sl_2_c0_hω0:
                            lea         rdi, [rel pl_trail]
                            mov         esi, [rbp - 8]
                            call        trail_unwind
                            jmp         pl_sentence_sl_2_ω
pl_sentence_sl_2_c0_hγ0:
                            mov         rax, [rbp - 24]     ; args array ptr
                            mov         rax, [rax + 8]     ; args[1]
                            mov         [rel pl_head_args + 8], rax  ; save call arg[1]
                            mov         rax, [rbp - 80]  ; var slot 1 (_V1)
                            mov         rsi, rax            ; head pattern
                            mov         rdi, [rel pl_head_args + 8]  ; restore call arg[1]
                            lea         rdx, [rel pl_trail]
                            call        unify
                            test        eax, eax
                            jnz         pl_sentence_sl_2_c0_hγ1
pl_sentence_sl_2_c0_hω1:
                            lea         rdi, [rel pl_trail]
                            mov         esi, [rbp - 8]
                            call        trail_unwind
                            jmp         pl_sentence_sl_2_ω
pl_sentence_sl_2_c0_hγ1:
pl_sentence_sl_2_c0_body:
                            lea         rdi, [rel pl_trail]
                            call        trail_mark_fn
                            mov         [rbp - 56], eax     ; UCALL_MARK_OFFSET(0) = β0 unwind target
; re-entry decode: inner = start - 0
                            mov         eax, [rbp - 32]        ; start
                            sub         eax, 0                ; inner = start - base
                            jle         pl_sentence_sl_2_c0_body_fresh
                            dec         eax                    ; inner - 1 = packed sub_cs
                            mov         ecx, eax               ; work register
                            mov         edx, ecx
                            and         edx, 4095        ; ucall 0 sub_cs = packed % STRIDE
                            mov         [rbp - 40], edx    ; pre-load slot 0
                            shr         ecx, 12        ; >> log2(STRIDE) per level
                            mov         edx, ecx
                            and         edx, 4095        ; ucall 1 sub_cs
                            mov         [rbp - 48], edx    ; pre-load slot 1
; fall into α0 — it restores edx from slot 0
                            jmp         pl_sentence_sl_2_c0_α0
pl_sentence_sl_2_c0_body_fresh:
                            xor         edx, edx               ; sub_cs=0 for first ucall
pl_sentence_sl_2_c0_α0:
                            sub         rsp, 16              ; args array for noun_phrase/2
                            mov         rbx, rsp               ; stable base (immune to rsp shifts)
                            mov         rax, [rbp - 72]  ; var slot 0 (_V0)
                            mov         [rbx + 0], rax    ; args[0]
                            mov         rax, [rbp - 88]  ; var slot 2 (_V2)
                            mov         [rbx + 8], rax    ; args[1]
                            mov         rdi, rbx               ; args[] ptr
                            lea         rsi, [rel pl_trail]
                            mov         edx, [rbp - 40]    ; restore sub_cs ucall 0
                            call        pl_noun_phrase_sl_2_r
                            add         rsp, 16
                            test        eax, eax
                            js          pl_sentence_sl_2_c0_β0
                            mov         [rbp - 40], eax        ; ucall slot 0 sub_cs
                            lea         rdi, [rel pl_trail]
                            call        trail_mark_fn
                            mov         [rbp - 64], eax    ; trail mark for ucall 1
                            jmp         pl_sentence_sl_2_c0_γ0
pl_sentence_sl_2_c0_β0:
                            lea         rdi, [rel pl_trail]
                            mov         esi, [rbp - 56]    ; unwind to before ucall 0
                            call        trail_unwind
                            jmp         pl_sentence_sl_2_ω
pl_sentence_sl_2_c0_γ0:
                            mov         eax, [rbp - 40]    ; sub_cs_acc = slot 0
                            mov         [rbp - 16], eax    ; store recomputed sub_cs_acc
                            mov         dword [rbp - 48], 0  ; init sub_cs slot ucall 1
                            xor         edx, edx               ; next ucall starts fresh
pl_sentence_sl_2_c0_α1:
                            sub         rsp, 16              ; args array for verb_phrase/2
                            mov         rbx, rsp               ; stable base (immune to rsp shifts)
                            mov         rax, [rbp - 88]  ; var slot 2 (_V2)
                            mov         [rbx + 0], rax    ; args[0]
                            mov         rax, [rbp - 80]  ; var slot 1 (_V1)
                            mov         [rbx + 8], rax    ; args[1]
                            mov         rdi, rbx               ; args[] ptr
                            lea         rsi, [rel pl_trail]
                            mov         edx, [rbp - 48]    ; restore sub_cs ucall 1
                            call        pl_verb_phrase_sl_2_r
                            add         rsp, 16
                            test        eax, eax
                            js          pl_sentence_sl_2_c0_β1
                            mov         [rbp - 48], eax        ; ucall slot 1 sub_cs
                            jmp         pl_sentence_sl_2_c0_γ1
pl_sentence_sl_2_c0_β1:
                            lea         rdi, [rel pl_trail]
                            mov         esi, [rbp - 56]    ; unwind to before ucall 1
                            call        trail_unwind
                            mov         edx, [rbp - 40]    ; restore sub_cs ucall 0
                            jmp         pl_sentence_sl_2_c0_α0
pl_sentence_sl_2_c0_γ1:
                            mov         eax, [rbp - 40]    ; sub_cs_acc = slot 0
                            push        rax
                            mov         eax, [rbp - 48]    ; slot 1
                            imul        eax, 4096            ; * STRIDE^1
                            pop         rcx
                            add         eax, ecx
                            mov         [rbp - 16], eax    ; store recomputed sub_cs_acc
                            xor         edx, edx               ; next ucall starts fresh
; γ — success clause 0 (base=0 body_ucalls=2)
                            mov         eax, [rbp - 16]       ; sub_cs_acc from body call
                            inc         eax                   ; sub_cs + 1
                            add         eax, 0               ; + base
                            mov         rsp, rbp
                            pop         rbp
                            ret

pl_sentence_sl_2_ω:
; ω — all clauses exhausted
                            lea         rdi, [rel pl_trail]
                            mov         esi, [rbp - 8]         ; trail mark
                            call        trail_unwind
                            mov         rsp, rbp
                            pop         rbp
                            mov         eax, -1
                            ret

global pl_sentence_sl_2
pl_sentence_sl_2:
; single-shot wrapper: push start=0
                            xor         rdx, rdx
                            jmp         pl_sentence_sl_2_r

; ============================================================
; predicate noun_phrase/2  (1 clause)
; ============================================================
global pl_noun_phrase_sl_2_r
pl_noun_phrase_sl_2_r:
                            push        rbp
                            mov         rbp, rsp
                            sub         rsp, 80
                            mov         byte [rbp - 17], 0    ; _cut = 0
                            mov         [rbp - 24], rdi     ; save args array ptr
                            mov         [rbp - 32], rdx     ; save start
                            xor         eax, eax
                            mov         [rbp - 16], eax        ; sub_cs_acc = 0
                            mov         eax, [rbp - 32]       ; start value
                            cmp         eax, 0
                            jge         pl_noun_phrase_sl_2_c0_α
                            jmp         pl_noun_phrase_sl_2_ω

; --- clause 1/1  n_vars=3 body_ucalls=1 ---
; clause 0 entry
pl_noun_phrase_sl_2_c0_α:
                            mov         rdi, 0
                            call        term_new_var
                            mov         [rbp - 56], rax    ; var slot 0
                            mov         rdi, 1
                            call        term_new_var
                            mov         [rbp - 64], rax    ; var slot 1
                            mov         rdi, 2
                            call        term_new_var
                            mov         [rbp - 72], rax    ; var slot 2
                            lea         rdi, [rel pl_trail]
                            call        trail_mark_fn
                            mov         [rbp - 8], eax          ; clause trail mark
                            mov         dword [rbp - 40], 0  ; init sub_cs slot 0
                            mov         rax, [rbp - 24]     ; args array ptr
                            mov         rax, [rax + 0]     ; args[0]
                            mov         [rel pl_head_args + 0], rax  ; save call arg[0]
                            mov         rax, [rbp - 56]  ; var slot 0 (_V0)
                            mov         rsi, rax            ; head pattern
                            mov         rdi, [rel pl_head_args + 0]  ; restore call arg[0]
                            lea         rdx, [rel pl_trail]
                            call        unify
                            test        eax, eax
                            jnz         pl_noun_phrase_sl_2_c0_hγ0
pl_noun_phrase_sl_2_c0_hω0:
                            lea         rdi, [rel pl_trail]
                            mov         esi, [rbp - 8]
                            call        trail_unwind
                            jmp         pl_noun_phrase_sl_2_ω
pl_noun_phrase_sl_2_c0_hγ0:
                            mov         rax, [rbp - 24]     ; args array ptr
                            mov         rax, [rax + 8]     ; args[1]
                            mov         [rel pl_head_args + 8], rax  ; save call arg[1]
                            mov         rax, [rbp - 64]  ; var slot 1 (_V1)
                            mov         rsi, rax            ; head pattern
                            mov         rdi, [rel pl_head_args + 8]  ; restore call arg[1]
                            lea         rdx, [rel pl_trail]
                            call        unify
                            test        eax, eax
                            jnz         pl_noun_phrase_sl_2_c0_hγ1
pl_noun_phrase_sl_2_c0_hω1:
                            lea         rdi, [rel pl_trail]
                            mov         esi, [rbp - 8]
                            call        trail_unwind
                            jmp         pl_noun_phrase_sl_2_ω
pl_noun_phrase_sl_2_c0_hγ1:
pl_noun_phrase_sl_2_c0_body:
                            lea         rdi, [rel pl_trail]
                            call        trail_mark_fn
                            mov         [rbp - 48], eax     ; UCALL_MARK_OFFSET(0) = β0 unwind target
; re-entry decode: inner = start - 0
                            mov         eax, [rbp - 32]        ; start
                            sub         eax, 0                ; inner = start - base
                            jle         pl_noun_phrase_sl_2_c0_body_fresh
                            dec         eax                    ; inner - 1 = packed sub_cs
                            mov         ecx, eax               ; work register
                            mov         edx, ecx
                            and         edx, 4095        ; ucall 0 sub_cs = packed % STRIDE
                            mov         [rbp - 40], edx    ; pre-load slot 0
; fall into α0 — it restores edx from slot 0
                            jmp         pl_noun_phrase_sl_2_c0_α0
pl_noun_phrase_sl_2_c0_body_fresh:
                            xor         edx, edx               ; sub_cs=0 for first ucall
                            mov         rax, [rbp - 56]  ; var slot 0 (_V0)
                            mov         [rel pl_tmp], rax
                            sub         rsp, 16            ; args[2] for compound ./2
                            lea         rax, [rel pl_atom_the_1]
                            mov         [rsp + 0], rax  ; compound arg 0
                            mov         rax, [rbp - 72]  ; var slot 2 (_V2)
                            mov         [rsp + 8], rax  ; compound arg 1
                            mov         edi, dword [rel pl_atom___0 + 8]  ; functor atom_id
                            mov         esi, 2                   ; arity
                            mov         rdx, rsp                   ; args ptr
                            call        term_new_compound
                            add         rsp, 16
                            mov         rsi, rax
                            mov         rdi, [rel pl_tmp]
                            lea         rdx, [rel pl_trail]
                            call        unify
                            test        eax, eax
                            jnz         pl_noun_phrase_sl_2_c0_ug0
pl_noun_phrase_sl_2_c0_ufail0:
                            lea         rdi, [rel pl_trail]
                            mov         esi, [rbp - 8]
                            call        trail_unwind
                            jmp         pl_noun_phrase_sl_2_ω
pl_noun_phrase_sl_2_c0_ug0:
pl_noun_phrase_sl_2_c0_α0:
                            sub         rsp, 16              ; args array for noun/2
                            mov         rbx, rsp               ; stable base (immune to rsp shifts)
                            mov         rax, [rbp - 72]  ; var slot 2 (_V2)
                            mov         [rbx + 0], rax    ; args[0]
                            mov         rax, [rbp - 64]  ; var slot 1 (_V1)
                            mov         [rbx + 8], rax    ; args[1]
                            mov         rdi, rbx               ; args[] ptr
                            lea         rsi, [rel pl_trail]
                            mov         edx, [rbp - 40]    ; restore sub_cs ucall 0
                            call        pl_noun_sl_2_r
                            add         rsp, 16
                            test        eax, eax
                            js          pl_noun_phrase_sl_2_c0_β1
                            mov         [rbp - 40], eax        ; ucall slot 0 sub_cs
                            jmp         pl_noun_phrase_sl_2_c0_γ1
pl_noun_phrase_sl_2_c0_β1:
                            lea         rdi, [rel pl_trail]
                            mov         esi, [rbp - 48]    ; unwind to before ucall 0
                            call        trail_unwind
                            jmp         pl_noun_phrase_sl_2_ω
pl_noun_phrase_sl_2_c0_γ1:
                            mov         eax, [rbp - 40]    ; sub_cs_acc = slot 0
                            mov         [rbp - 16], eax    ; store recomputed sub_cs_acc
                            xor         edx, edx               ; next ucall starts fresh
; γ — success clause 0 (base=0 body_ucalls=1)
                            mov         eax, [rbp - 16]       ; sub_cs_acc from body call
                            inc         eax                   ; sub_cs + 1
                            add         eax, 0               ; + base
                            mov         rsp, rbp
                            pop         rbp
                            ret

pl_noun_phrase_sl_2_ω:
; ω — all clauses exhausted
                            lea         rdi, [rel pl_trail]
                            mov         esi, [rbp - 8]         ; trail mark
                            call        trail_unwind
                            mov         rsp, rbp
                            pop         rbp
                            mov         eax, -1
                            ret

global pl_noun_phrase_sl_2
pl_noun_phrase_sl_2:
; single-shot wrapper: push start=0
                            xor         rdx, rdx
                            jmp         pl_noun_phrase_sl_2_r

; ============================================================
; predicate verb_phrase/2  (2 clauses)
; ============================================================
global pl_verb_phrase_sl_2_r
pl_verb_phrase_sl_2_r:
                            push        rbp
                            mov         rbp, rsp
                            sub         rsp, 96
                            mov         byte [rbp - 17], 0    ; _cut = 0
                            mov         [rbp - 24], rdi     ; save args array ptr
                            mov         [rbp - 32], rdx     ; save start
                            xor         eax, eax
                            mov         [rbp - 16], eax        ; sub_cs_acc = 0
                            mov         eax, [rbp - 32]       ; start value
                            cmp         eax, 1
                            jge         pl_verb_phrase_sl_2_c1_α
                            cmp         eax, 0
                            jge         pl_verb_phrase_sl_2_c0_α
                            jmp         pl_verb_phrase_sl_2_ω

; --- clause 1/2  n_vars=3 body_ucalls=2 ---
; clause 0 entry
pl_verb_phrase_sl_2_c0_α:
                            mov         rdi, 0
                            call        term_new_var
                            mov         [rbp - 72], rax    ; var slot 0
                            mov         rdi, 1
                            call        term_new_var
                            mov         [rbp - 80], rax    ; var slot 1
                            mov         rdi, 2
                            call        term_new_var
                            mov         [rbp - 88], rax    ; var slot 2
                            lea         rdi, [rel pl_trail]
                            call        trail_mark_fn
                            mov         [rbp - 8], eax          ; clause trail mark
                            mov         dword [rbp - 40], 0  ; init sub_cs slot 0
                            mov         dword [rbp - 48], 0  ; init sub_cs slot 1
                            mov         rax, [rbp - 24]     ; args array ptr
                            mov         rax, [rax + 0]     ; args[0]
                            mov         [rel pl_head_args + 0], rax  ; save call arg[0]
                            mov         rax, [rbp - 72]  ; var slot 0 (_V0)
                            mov         rsi, rax            ; head pattern
                            mov         rdi, [rel pl_head_args + 0]  ; restore call arg[0]
                            lea         rdx, [rel pl_trail]
                            call        unify
                            test        eax, eax
                            jnz         pl_verb_phrase_sl_2_c0_hγ0
pl_verb_phrase_sl_2_c0_hω0:
                            lea         rdi, [rel pl_trail]
                            mov         esi, [rbp - 8]
                            call        trail_unwind
                            jmp         pl_verb_phrase_sl_2_c1_α
pl_verb_phrase_sl_2_c0_hγ0:
                            mov         rax, [rbp - 24]     ; args array ptr
                            mov         rax, [rax + 8]     ; args[1]
                            mov         [rel pl_head_args + 8], rax  ; save call arg[1]
                            mov         rax, [rbp - 80]  ; var slot 1 (_V1)
                            mov         rsi, rax            ; head pattern
                            mov         rdi, [rel pl_head_args + 8]  ; restore call arg[1]
                            lea         rdx, [rel pl_trail]
                            call        unify
                            test        eax, eax
                            jnz         pl_verb_phrase_sl_2_c0_hγ1
pl_verb_phrase_sl_2_c0_hω1:
                            lea         rdi, [rel pl_trail]
                            mov         esi, [rbp - 8]
                            call        trail_unwind
                            jmp         pl_verb_phrase_sl_2_c1_α
pl_verb_phrase_sl_2_c0_hγ1:
pl_verb_phrase_sl_2_c0_body:
                            lea         rdi, [rel pl_trail]
                            call        trail_mark_fn
                            mov         [rbp - 56], eax     ; UCALL_MARK_OFFSET(0) = β0 unwind target
; re-entry decode: inner = start - 0
                            mov         eax, [rbp - 32]        ; start
                            sub         eax, 0                ; inner = start - base
                            jle         pl_verb_phrase_sl_2_c0_body_fresh
                            dec         eax                    ; inner - 1 = packed sub_cs
                            mov         ecx, eax               ; work register
                            mov         edx, ecx
                            and         edx, 4095        ; ucall 0 sub_cs = packed % STRIDE
                            mov         [rbp - 40], edx    ; pre-load slot 0
                            shr         ecx, 12        ; >> log2(STRIDE) per level
                            mov         edx, ecx
                            and         edx, 4095        ; ucall 1 sub_cs
                            mov         [rbp - 48], edx    ; pre-load slot 1
; fall into α0 — it restores edx from slot 0
                            jmp         pl_verb_phrase_sl_2_c0_α0
pl_verb_phrase_sl_2_c0_body_fresh:
                            xor         edx, edx               ; sub_cs=0 for first ucall
pl_verb_phrase_sl_2_c0_α0:
                            sub         rsp, 16              ; args array for verb/2
                            mov         rbx, rsp               ; stable base (immune to rsp shifts)
                            mov         rax, [rbp - 72]  ; var slot 0 (_V0)
                            mov         [rbx + 0], rax    ; args[0]
                            mov         rax, [rbp - 88]  ; var slot 2 (_V2)
                            mov         [rbx + 8], rax    ; args[1]
                            mov         rdi, rbx               ; args[] ptr
                            lea         rsi, [rel pl_trail]
                            mov         edx, [rbp - 40]    ; restore sub_cs ucall 0
                            call        pl_verb_sl_2_r
                            add         rsp, 16
                            test        eax, eax
                            js          pl_verb_phrase_sl_2_c0_β0
                            mov         [rbp - 40], eax        ; ucall slot 0 sub_cs
                            lea         rdi, [rel pl_trail]
                            call        trail_mark_fn
                            mov         [rbp - 64], eax    ; trail mark for ucall 1
                            jmp         pl_verb_phrase_sl_2_c0_γ0
pl_verb_phrase_sl_2_c0_β0:
                            lea         rdi, [rel pl_trail]
                            mov         esi, [rbp - 56]    ; unwind to before ucall 0
                            call        trail_unwind
                            jmp         pl_verb_phrase_sl_2_c1_α
pl_verb_phrase_sl_2_c0_γ0:
                            mov         eax, [rbp - 40]    ; sub_cs_acc = slot 0
                            mov         [rbp - 16], eax    ; store recomputed sub_cs_acc
                            mov         dword [rbp - 48], 0  ; init sub_cs slot ucall 1
                            xor         edx, edx               ; next ucall starts fresh
pl_verb_phrase_sl_2_c0_α1:
                            sub         rsp, 16              ; args array for noun_phrase/2
                            mov         rbx, rsp               ; stable base (immune to rsp shifts)
                            mov         rax, [rbp - 88]  ; var slot 2 (_V2)
                            mov         [rbx + 0], rax    ; args[0]
                            mov         rax, [rbp - 80]  ; var slot 1 (_V1)
                            mov         [rbx + 8], rax    ; args[1]
                            mov         rdi, rbx               ; args[] ptr
                            lea         rsi, [rel pl_trail]
                            mov         edx, [rbp - 48]    ; restore sub_cs ucall 1
                            call        pl_noun_phrase_sl_2_r
                            add         rsp, 16
                            test        eax, eax
                            js          pl_verb_phrase_sl_2_c0_β1
                            mov         [rbp - 48], eax        ; ucall slot 1 sub_cs
                            jmp         pl_verb_phrase_sl_2_c0_γ1
pl_verb_phrase_sl_2_c0_β1:
                            lea         rdi, [rel pl_trail]
                            mov         esi, [rbp - 56]    ; unwind to before ucall 1
                            call        trail_unwind
                            mov         edx, [rbp - 40]    ; restore sub_cs ucall 0
                            jmp         pl_verb_phrase_sl_2_c0_α0
pl_verb_phrase_sl_2_c0_γ1:
                            mov         eax, [rbp - 40]    ; sub_cs_acc = slot 0
                            push        rax
                            mov         eax, [rbp - 48]    ; slot 1
                            imul        eax, 4096            ; * STRIDE^1
                            pop         rcx
                            add         eax, ecx
                            mov         [rbp - 16], eax    ; store recomputed sub_cs_acc
                            xor         edx, edx               ; next ucall starts fresh
; γ — success clause 0 (base=0 body_ucalls=2)
                            mov         eax, [rbp - 16]       ; sub_cs_acc from body call
                            inc         eax                   ; sub_cs + 1
                            add         eax, 0               ; + base
                            mov         rsp, rbp
                            pop         rbp
                            ret

; --- clause 2/2  n_vars=2 body_ucalls=1 ---
; clause 1 entry
pl_verb_phrase_sl_2_c1_α:
                            mov         rdi, 0
                            call        term_new_var
                            mov         [rbp - 72], rax    ; var slot 0
                            mov         rdi, 1
                            call        term_new_var
                            mov         [rbp - 80], rax    ; var slot 1
                            lea         rdi, [rel pl_trail]
                            call        trail_mark_fn
                            mov         [rbp - 8], eax          ; clause trail mark
                            mov         dword [rbp - 40], 0  ; init sub_cs slot 0
                            mov         dword [rbp - 48], 0  ; init sub_cs slot 1
                            mov         rax, [rbp - 24]     ; args array ptr
                            mov         rax, [rax + 0]     ; args[0]
                            mov         [rel pl_head_args + 0], rax  ; save call arg[0]
                            mov         rax, [rbp - 72]  ; var slot 0 (_V0)
                            mov         rsi, rax            ; head pattern
                            mov         rdi, [rel pl_head_args + 0]  ; restore call arg[0]
                            lea         rdx, [rel pl_trail]
                            call        unify
                            test        eax, eax
                            jnz         pl_verb_phrase_sl_2_c1_hγ0
pl_verb_phrase_sl_2_c1_hω0:
                            lea         rdi, [rel pl_trail]
                            mov         esi, [rbp - 8]
                            call        trail_unwind
                            jmp         pl_verb_phrase_sl_2_ω
pl_verb_phrase_sl_2_c1_hγ0:
                            mov         rax, [rbp - 24]     ; args array ptr
                            mov         rax, [rax + 8]     ; args[1]
                            mov         [rel pl_head_args + 8], rax  ; save call arg[1]
                            mov         rax, [rbp - 80]  ; var slot 1 (_V1)
                            mov         rsi, rax            ; head pattern
                            mov         rdi, [rel pl_head_args + 8]  ; restore call arg[1]
                            lea         rdx, [rel pl_trail]
                            call        unify
                            test        eax, eax
                            jnz         pl_verb_phrase_sl_2_c1_hγ1
pl_verb_phrase_sl_2_c1_hω1:
                            lea         rdi, [rel pl_trail]
                            mov         esi, [rbp - 8]
                            call        trail_unwind
                            jmp         pl_verb_phrase_sl_2_ω
pl_verb_phrase_sl_2_c1_hγ1:
pl_verb_phrase_sl_2_c1_body:
                            lea         rdi, [rel pl_trail]
                            call        trail_mark_fn
                            mov         [rbp - 56], eax     ; UCALL_MARK_OFFSET(0) = β0 unwind target
; re-entry decode: inner = start - 1
                            mov         eax, [rbp - 32]        ; start
                            sub         eax, 1                ; inner = start - base
                            jle         pl_verb_phrase_sl_2_c1_body_fresh
                            dec         eax                    ; inner - 1 = packed sub_cs
                            mov         ecx, eax               ; work register
                            mov         edx, ecx
                            and         edx, 4095        ; ucall 0 sub_cs = packed % STRIDE
                            mov         [rbp - 40], edx    ; pre-load slot 0
                            shr         ecx, 12        ; >> log2(STRIDE) per level
                            mov         edx, ecx
                            and         edx, 4095        ; ucall 1 sub_cs
                            mov         [rbp - 48], edx    ; pre-load slot 1
; fall into α0 — it restores edx from slot 0
                            jmp         pl_verb_phrase_sl_2_c1_α0
pl_verb_phrase_sl_2_c1_body_fresh:
                            xor         edx, edx               ; sub_cs=0 for first ucall
pl_verb_phrase_sl_2_c1_α0:
                            sub         rsp, 16              ; args array for verb/2
                            mov         rbx, rsp               ; stable base (immune to rsp shifts)
                            mov         rax, [rbp - 72]  ; var slot 0 (_V0)
                            mov         [rbx + 0], rax    ; args[0]
                            mov         rax, [rbp - 80]  ; var slot 1 (_V1)
                            mov         [rbx + 8], rax    ; args[1]
                            mov         rdi, rbx               ; args[] ptr
                            lea         rsi, [rel pl_trail]
                            mov         edx, [rbp - 40]    ; restore sub_cs ucall 0
                            call        pl_verb_sl_2_r
                            add         rsp, 16
                            test        eax, eax
                            js          pl_verb_phrase_sl_2_c1_β0
                            mov         [rbp - 40], eax        ; ucall slot 0 sub_cs
                            lea         rdi, [rel pl_trail]
                            call        trail_mark_fn
                            mov         [rbp - 64], eax    ; trail mark for ucall 1
                            jmp         pl_verb_phrase_sl_2_c1_γ0
pl_verb_phrase_sl_2_c1_β0:
                            lea         rdi, [rel pl_trail]
                            mov         esi, [rbp - 56]    ; unwind to before ucall 0
                            call        trail_unwind
                            jmp         pl_verb_phrase_sl_2_ω
pl_verb_phrase_sl_2_c1_γ0:
                            mov         eax, [rbp - 40]    ; sub_cs_acc = slot 0
                            mov         [rbp - 16], eax    ; store recomputed sub_cs_acc
                            mov         dword [rbp - 48], 0  ; init sub_cs slot ucall 1
                            xor         edx, edx               ; next ucall starts fresh
; γ — success clause 1 (base=1 body_ucalls=1)
                            mov         eax, [rbp - 16]       ; sub_cs_acc from body call
                            inc         eax                   ; sub_cs + 1
                            add         eax, 1               ; + base
                            mov         rsp, rbp
                            pop         rbp
                            ret

pl_verb_phrase_sl_2_ω:
; ω — all clauses exhausted
                            lea         rdi, [rel pl_trail]
                            mov         esi, [rbp - 8]         ; trail mark
                            call        trail_unwind
                            mov         rsp, rbp
                            pop         rbp
                            mov         eax, -1
                            ret

global pl_verb_phrase_sl_2
pl_verb_phrase_sl_2:
; single-shot wrapper: push start=0
                            xor         rdx, rdx
                            jmp         pl_verb_phrase_sl_2_r

; ============================================================
; predicate noun/2  (3 clauses)
; ============================================================
global pl_noun_sl_2_r
pl_noun_sl_2_r:
                            push        rbp
                            mov         rbp, rsp
                            sub         rsp, 64
                            mov         byte [rbp - 17], 0    ; _cut = 0
                            mov         [rbp - 24], rdi     ; save args array ptr
                            mov         [rbp - 32], rdx     ; save start
                            xor         eax, eax
                            mov         [rbp - 16], eax        ; sub_cs_acc = 0
                            mov         eax, [rbp - 32]       ; start value
                            cmp         eax, 3
                            jge         pl_noun_sl_2_ω                 ; past all clauses
                            cmp         eax, 2
                            jge         pl_noun_sl_2_c2_α
                            cmp         eax, 1
                            jge         pl_noun_sl_2_c1_α
                            cmp         eax, 0
                            jge         pl_noun_sl_2_c0_α
                            jmp         pl_noun_sl_2_ω

; --- clause 1/3  n_vars=2 body_ucalls=0 ---
; clause 0 entry
pl_noun_sl_2_c0_α:
                            mov         rdi, 0
                            call        term_new_var
                            mov         [rbp - 40], rax    ; var slot 0
                            mov         rdi, 1
                            call        term_new_var
                            mov         [rbp - 48], rax    ; var slot 1
                            lea         rdi, [rel pl_trail]
                            call        trail_mark_fn
                            mov         [rbp - 8], eax          ; clause trail mark
                            mov         rax, [rbp - 24]     ; args array ptr
                            mov         rax, [rax + 0]     ; args[0]
                            mov         [rel pl_head_args + 0], rax  ; save call arg[0]
                            mov         rax, [rbp - 40]  ; var slot 0 (_V0)
                            mov         rsi, rax            ; head pattern
                            mov         rdi, [rel pl_head_args + 0]  ; restore call arg[0]
                            lea         rdx, [rel pl_trail]
                            call        unify
                            test        eax, eax
                            jnz         pl_noun_sl_2_c0_hγ0
pl_noun_sl_2_c0_hω0:
                            lea         rdi, [rel pl_trail]
                            mov         esi, [rbp - 8]
                            call        trail_unwind
                            jmp         pl_noun_sl_2_c1_α
pl_noun_sl_2_c0_hγ0:
                            mov         rax, [rbp - 24]     ; args array ptr
                            mov         rax, [rax + 8]     ; args[1]
                            mov         [rel pl_head_args + 8], rax  ; save call arg[1]
                            mov         rax, [rbp - 48]  ; var slot 1 (_V1)
                            mov         rsi, rax            ; head pattern
                            mov         rdi, [rel pl_head_args + 8]  ; restore call arg[1]
                            lea         rdx, [rel pl_trail]
                            call        unify
                            test        eax, eax
                            jnz         pl_noun_sl_2_c0_hγ1
pl_noun_sl_2_c0_hω1:
                            lea         rdi, [rel pl_trail]
                            mov         esi, [rbp - 8]
                            call        trail_unwind
                            jmp         pl_noun_sl_2_c1_α
pl_noun_sl_2_c0_hγ1:
pl_noun_sl_2_c0_body:
                            xor         edx, edx               ; sub_cs=0 for first ucall
                            mov         rax, [rbp - 40]  ; var slot 0 (_V0)
                            mov         [rel pl_tmp], rax
                            sub         rsp, 16            ; args[2] for compound ./2
                            lea         rax, [rel pl_atom_cat_2]
                            mov         [rsp + 0], rax  ; compound arg 0
                            mov         rax, [rbp - 48]  ; var slot 1 (_V1)
                            mov         [rsp + 8], rax  ; compound arg 1
                            mov         edi, dword [rel pl_atom___0 + 8]  ; functor atom_id
                            mov         esi, 2                   ; arity
                            mov         rdx, rsp                   ; args ptr
                            call        term_new_compound
                            add         rsp, 16
                            mov         rsi, rax
                            mov         rdi, [rel pl_tmp]
                            lea         rdx, [rel pl_trail]
                            call        unify
                            test        eax, eax
                            jnz         pl_noun_sl_2_c0_ug0
pl_noun_sl_2_c0_ufail0:
                            lea         rdi, [rel pl_trail]
                            mov         esi, [rbp - 8]
                            call        trail_unwind
                            jmp         pl_noun_sl_2_c1_α
pl_noun_sl_2_c0_ug0:
; γ — success clause 0 (base=0 body_ucalls=0)
                            mov         eax, 1               ; base+1 → next clause
                            mov         rsp, rbp
                            pop         rbp
                            ret

; --- clause 2/3  n_vars=2 body_ucalls=0 ---
; clause 1 entry
pl_noun_sl_2_c1_α:
                            mov         rdi, 0
                            call        term_new_var
                            mov         [rbp - 40], rax    ; var slot 0
                            mov         rdi, 1
                            call        term_new_var
                            mov         [rbp - 48], rax    ; var slot 1
                            lea         rdi, [rel pl_trail]
                            call        trail_mark_fn
                            mov         [rbp - 8], eax          ; clause trail mark
                            mov         rax, [rbp - 24]     ; args array ptr
                            mov         rax, [rax + 0]     ; args[0]
                            mov         [rel pl_head_args + 0], rax  ; save call arg[0]
                            mov         rax, [rbp - 40]  ; var slot 0 (_V0)
                            mov         rsi, rax            ; head pattern
                            mov         rdi, [rel pl_head_args + 0]  ; restore call arg[0]
                            lea         rdx, [rel pl_trail]
                            call        unify
                            test        eax, eax
                            jnz         pl_noun_sl_2_c1_hγ0
pl_noun_sl_2_c1_hω0:
                            lea         rdi, [rel pl_trail]
                            mov         esi, [rbp - 8]
                            call        trail_unwind
                            jmp         pl_noun_sl_2_c2_α
pl_noun_sl_2_c1_hγ0:
                            mov         rax, [rbp - 24]     ; args array ptr
                            mov         rax, [rax + 8]     ; args[1]
                            mov         [rel pl_head_args + 8], rax  ; save call arg[1]
                            mov         rax, [rbp - 48]  ; var slot 1 (_V1)
                            mov         rsi, rax            ; head pattern
                            mov         rdi, [rel pl_head_args + 8]  ; restore call arg[1]
                            lea         rdx, [rel pl_trail]
                            call        unify
                            test        eax, eax
                            jnz         pl_noun_sl_2_c1_hγ1
pl_noun_sl_2_c1_hω1:
                            lea         rdi, [rel pl_trail]
                            mov         esi, [rbp - 8]
                            call        trail_unwind
                            jmp         pl_noun_sl_2_c2_α
pl_noun_sl_2_c1_hγ1:
pl_noun_sl_2_c1_body:
                            xor         edx, edx               ; sub_cs=0 for first ucall
                            mov         rax, [rbp - 40]  ; var slot 0 (_V0)
                            mov         [rel pl_tmp], rax
                            sub         rsp, 16            ; args[2] for compound ./2
                            lea         rax, [rel pl_atom_dog_3]
                            mov         [rsp + 0], rax  ; compound arg 0
                            mov         rax, [rbp - 48]  ; var slot 1 (_V1)
                            mov         [rsp + 8], rax  ; compound arg 1
                            mov         edi, dword [rel pl_atom___0 + 8]  ; functor atom_id
                            mov         esi, 2                   ; arity
                            mov         rdx, rsp                   ; args ptr
                            call        term_new_compound
                            add         rsp, 16
                            mov         rsi, rax
                            mov         rdi, [rel pl_tmp]
                            lea         rdx, [rel pl_trail]
                            call        unify
                            test        eax, eax
                            jnz         pl_noun_sl_2_c1_ug0
pl_noun_sl_2_c1_ufail0:
                            lea         rdi, [rel pl_trail]
                            mov         esi, [rbp - 8]
                            call        trail_unwind
                            jmp         pl_noun_sl_2_c2_α
pl_noun_sl_2_c1_ug0:
; γ — success clause 1 (base=1 body_ucalls=0)
                            mov         eax, 2               ; base+1 → next clause
                            mov         rsp, rbp
                            pop         rbp
                            ret

; --- clause 3/3  n_vars=2 body_ucalls=0 ---
; clause 2 entry
pl_noun_sl_2_c2_α:
                            mov         rdi, 0
                            call        term_new_var
                            mov         [rbp - 40], rax    ; var slot 0
                            mov         rdi, 1
                            call        term_new_var
                            mov         [rbp - 48], rax    ; var slot 1
                            lea         rdi, [rel pl_trail]
                            call        trail_mark_fn
                            mov         [rbp - 8], eax          ; clause trail mark
                            mov         rax, [rbp - 24]     ; args array ptr
                            mov         rax, [rax + 0]     ; args[0]
                            mov         [rel pl_head_args + 0], rax  ; save call arg[0]
                            mov         rax, [rbp - 40]  ; var slot 0 (_V0)
                            mov         rsi, rax            ; head pattern
                            mov         rdi, [rel pl_head_args + 0]  ; restore call arg[0]
                            lea         rdx, [rel pl_trail]
                            call        unify
                            test        eax, eax
                            jnz         pl_noun_sl_2_c2_hγ0
pl_noun_sl_2_c2_hω0:
                            lea         rdi, [rel pl_trail]
                            mov         esi, [rbp - 8]
                            call        trail_unwind
                            jmp         pl_noun_sl_2_ω
pl_noun_sl_2_c2_hγ0:
                            mov         rax, [rbp - 24]     ; args array ptr
                            mov         rax, [rax + 8]     ; args[1]
                            mov         [rel pl_head_args + 8], rax  ; save call arg[1]
                            mov         rax, [rbp - 48]  ; var slot 1 (_V1)
                            mov         rsi, rax            ; head pattern
                            mov         rdi, [rel pl_head_args + 8]  ; restore call arg[1]
                            lea         rdx, [rel pl_trail]
                            call        unify
                            test        eax, eax
                            jnz         pl_noun_sl_2_c2_hγ1
pl_noun_sl_2_c2_hω1:
                            lea         rdi, [rel pl_trail]
                            mov         esi, [rbp - 8]
                            call        trail_unwind
                            jmp         pl_noun_sl_2_ω
pl_noun_sl_2_c2_hγ1:
pl_noun_sl_2_c2_body:
                            xor         edx, edx               ; sub_cs=0 for first ucall
                            mov         rax, [rbp - 40]  ; var slot 0 (_V0)
                            mov         [rel pl_tmp], rax
                            sub         rsp, 16            ; args[2] for compound ./2
                            lea         rax, [rel pl_atom_mouse_4]
                            mov         [rsp + 0], rax  ; compound arg 0
                            mov         rax, [rbp - 48]  ; var slot 1 (_V1)
                            mov         [rsp + 8], rax  ; compound arg 1
                            mov         edi, dword [rel pl_atom___0 + 8]  ; functor atom_id
                            mov         esi, 2                   ; arity
                            mov         rdx, rsp                   ; args ptr
                            call        term_new_compound
                            add         rsp, 16
                            mov         rsi, rax
                            mov         rdi, [rel pl_tmp]
                            lea         rdx, [rel pl_trail]
                            call        unify
                            test        eax, eax
                            jnz         pl_noun_sl_2_c2_ug0
pl_noun_sl_2_c2_ufail0:
                            lea         rdi, [rel pl_trail]
                            mov         esi, [rbp - 8]
                            call        trail_unwind
                            jmp         pl_noun_sl_2_ω
pl_noun_sl_2_c2_ug0:
; γ — success clause 2 (base=2 body_ucalls=0)
                            mov         eax, 3               ; base+1 → next clause
                            mov         rsp, rbp
                            pop         rbp
                            ret

pl_noun_sl_2_ω:
; ω — all clauses exhausted
                            lea         rdi, [rel pl_trail]
                            mov         esi, [rbp - 8]         ; trail mark
                            call        trail_unwind
                            mov         rsp, rbp
                            pop         rbp
                            mov         eax, -1
                            ret

global pl_noun_sl_2
pl_noun_sl_2:
; single-shot wrapper: push start=0
                            xor         rdx, rdx
                            jmp         pl_noun_sl_2_r

; ============================================================
; predicate verb/2  (2 clauses)
; ============================================================
global pl_verb_sl_2_r
pl_verb_sl_2_r:
                            push        rbp
                            mov         rbp, rsp
                            sub         rsp, 64
                            mov         byte [rbp - 17], 0    ; _cut = 0
                            mov         [rbp - 24], rdi     ; save args array ptr
                            mov         [rbp - 32], rdx     ; save start
                            xor         eax, eax
                            mov         [rbp - 16], eax        ; sub_cs_acc = 0
                            mov         eax, [rbp - 32]       ; start value
                            cmp         eax, 2
                            jge         pl_verb_sl_2_ω                 ; past all clauses
                            cmp         eax, 1
                            jge         pl_verb_sl_2_c1_α
                            cmp         eax, 0
                            jge         pl_verb_sl_2_c0_α
                            jmp         pl_verb_sl_2_ω

; --- clause 1/2  n_vars=2 body_ucalls=0 ---
; clause 0 entry
pl_verb_sl_2_c0_α:
                            mov         rdi, 0
                            call        term_new_var
                            mov         [rbp - 40], rax    ; var slot 0
                            mov         rdi, 1
                            call        term_new_var
                            mov         [rbp - 48], rax    ; var slot 1
                            lea         rdi, [rel pl_trail]
                            call        trail_mark_fn
                            mov         [rbp - 8], eax          ; clause trail mark
                            mov         rax, [rbp - 24]     ; args array ptr
                            mov         rax, [rax + 0]     ; args[0]
                            mov         [rel pl_head_args + 0], rax  ; save call arg[0]
                            mov         rax, [rbp - 40]  ; var slot 0 (_V0)
                            mov         rsi, rax            ; head pattern
                            mov         rdi, [rel pl_head_args + 0]  ; restore call arg[0]
                            lea         rdx, [rel pl_trail]
                            call        unify
                            test        eax, eax
                            jnz         pl_verb_sl_2_c0_hγ0
pl_verb_sl_2_c0_hω0:
                            lea         rdi, [rel pl_trail]
                            mov         esi, [rbp - 8]
                            call        trail_unwind
                            jmp         pl_verb_sl_2_c1_α
pl_verb_sl_2_c0_hγ0:
                            mov         rax, [rbp - 24]     ; args array ptr
                            mov         rax, [rax + 8]     ; args[1]
                            mov         [rel pl_head_args + 8], rax  ; save call arg[1]
                            mov         rax, [rbp - 48]  ; var slot 1 (_V1)
                            mov         rsi, rax            ; head pattern
                            mov         rdi, [rel pl_head_args + 8]  ; restore call arg[1]
                            lea         rdx, [rel pl_trail]
                            call        unify
                            test        eax, eax
                            jnz         pl_verb_sl_2_c0_hγ1
pl_verb_sl_2_c0_hω1:
                            lea         rdi, [rel pl_trail]
                            mov         esi, [rbp - 8]
                            call        trail_unwind
                            jmp         pl_verb_sl_2_c1_α
pl_verb_sl_2_c0_hγ1:
pl_verb_sl_2_c0_body:
                            xor         edx, edx               ; sub_cs=0 for first ucall
                            mov         rax, [rbp - 40]  ; var slot 0 (_V0)
                            mov         [rel pl_tmp], rax
                            sub         rsp, 16            ; args[2] for compound ./2
                            lea         rax, [rel pl_atom_chases_5]
                            mov         [rsp + 0], rax  ; compound arg 0
                            mov         rax, [rbp - 48]  ; var slot 1 (_V1)
                            mov         [rsp + 8], rax  ; compound arg 1
                            mov         edi, dword [rel pl_atom___0 + 8]  ; functor atom_id
                            mov         esi, 2                   ; arity
                            mov         rdx, rsp                   ; args ptr
                            call        term_new_compound
                            add         rsp, 16
                            mov         rsi, rax
                            mov         rdi, [rel pl_tmp]
                            lea         rdx, [rel pl_trail]
                            call        unify
                            test        eax, eax
                            jnz         pl_verb_sl_2_c0_ug0
pl_verb_sl_2_c0_ufail0:
                            lea         rdi, [rel pl_trail]
                            mov         esi, [rbp - 8]
                            call        trail_unwind
                            jmp         pl_verb_sl_2_c1_α
pl_verb_sl_2_c0_ug0:
; γ — success clause 0 (base=0 body_ucalls=0)
                            mov         eax, 1               ; base+1 → next clause
                            mov         rsp, rbp
                            pop         rbp
                            ret

; --- clause 2/2  n_vars=2 body_ucalls=0 ---
; clause 1 entry
pl_verb_sl_2_c1_α:
                            mov         rdi, 0
                            call        term_new_var
                            mov         [rbp - 40], rax    ; var slot 0
                            mov         rdi, 1
                            call        term_new_var
                            mov         [rbp - 48], rax    ; var slot 1
                            lea         rdi, [rel pl_trail]
                            call        trail_mark_fn
                            mov         [rbp - 8], eax          ; clause trail mark
                            mov         rax, [rbp - 24]     ; args array ptr
                            mov         rax, [rax + 0]     ; args[0]
                            mov         [rel pl_head_args + 0], rax  ; save call arg[0]
                            mov         rax, [rbp - 40]  ; var slot 0 (_V0)
                            mov         rsi, rax            ; head pattern
                            mov         rdi, [rel pl_head_args + 0]  ; restore call arg[0]
                            lea         rdx, [rel pl_trail]
                            call        unify
                            test        eax, eax
                            jnz         pl_verb_sl_2_c1_hγ0
pl_verb_sl_2_c1_hω0:
                            lea         rdi, [rel pl_trail]
                            mov         esi, [rbp - 8]
                            call        trail_unwind
                            jmp         pl_verb_sl_2_ω
pl_verb_sl_2_c1_hγ0:
                            mov         rax, [rbp - 24]     ; args array ptr
                            mov         rax, [rax + 8]     ; args[1]
                            mov         [rel pl_head_args + 8], rax  ; save call arg[1]
                            mov         rax, [rbp - 48]  ; var slot 1 (_V1)
                            mov         rsi, rax            ; head pattern
                            mov         rdi, [rel pl_head_args + 8]  ; restore call arg[1]
                            lea         rdx, [rel pl_trail]
                            call        unify
                            test        eax, eax
                            jnz         pl_verb_sl_2_c1_hγ1
pl_verb_sl_2_c1_hω1:
                            lea         rdi, [rel pl_trail]
                            mov         esi, [rbp - 8]
                            call        trail_unwind
                            jmp         pl_verb_sl_2_ω
pl_verb_sl_2_c1_hγ1:
pl_verb_sl_2_c1_body:
                            xor         edx, edx               ; sub_cs=0 for first ucall
                            mov         rax, [rbp - 40]  ; var slot 0 (_V0)
                            mov         [rel pl_tmp], rax
                            sub         rsp, 16            ; args[2] for compound ./2
                            lea         rax, [rel pl_atom_sees_6]
                            mov         [rsp + 0], rax  ; compound arg 0
                            mov         rax, [rbp - 48]  ; var slot 1 (_V1)
                            mov         [rsp + 8], rax  ; compound arg 1
                            mov         edi, dword [rel pl_atom___0 + 8]  ; functor atom_id
                            mov         esi, 2                   ; arity
                            mov         rdx, rsp                   ; args ptr
                            call        term_new_compound
                            add         rsp, 16
                            mov         rsi, rax
                            mov         rdi, [rel pl_tmp]
                            lea         rdx, [rel pl_trail]
                            call        unify
                            test        eax, eax
                            jnz         pl_verb_sl_2_c1_ug0
pl_verb_sl_2_c1_ufail0:
                            lea         rdi, [rel pl_trail]
                            mov         esi, [rbp - 8]
                            call        trail_unwind
                            jmp         pl_verb_sl_2_ω
pl_verb_sl_2_c1_ug0:
; γ — success clause 1 (base=1 body_ucalls=0)
                            mov         eax, 2               ; base+1 → next clause
                            mov         rsp, rbp
                            pop         rbp
                            ret

pl_verb_sl_2_ω:
; ω — all clauses exhausted
                            lea         rdi, [rel pl_trail]
                            mov         esi, [rbp - 8]         ; trail mark
                            call        trail_unwind
                            mov         rsp, rbp
                            pop         rbp
                            mov         eax, -1
                            ret

global pl_verb_sl_2
pl_verb_sl_2:
; single-shot wrapper: push start=0
                            xor         rdx, rdx
                            jmp         pl_verb_sl_2_r

; ============================================================
; predicate main/0  (1 clause)
; ============================================================
global pl_main_sl_0_r
pl_main_sl_0_r:
                            push        rbp
                            mov         rbp, rsp
                            sub         rsp, 48
                            mov         byte [rbp - 17], 0    ; _cut = 0
; arity 0 — no args to save
                            xor         rax, rax
                            mov         [rbp - 24], rax     ; args array ptr = NULL
                            mov         [rbp - 32], rdx     ; save start
                            xor         eax, eax
                            mov         [rbp - 16], eax        ; sub_cs_acc = 0
                            mov         eax, [rbp - 32]       ; start value
                            cmp         eax, 1
                            jge         pl_main_sl_0_ω                 ; past all clauses
                            cmp         eax, 0
                            jge         pl_main_sl_0_c0_α
                            jmp         pl_main_sl_0_ω

; --- clause 1/1  n_vars=0 body_ucalls=0 ---
; clause 0 entry
pl_main_sl_0_c0_α:
                            lea         rdi, [rel pl_trail]
                            call        trail_mark_fn
                            mov         [rbp - 8], eax          ; clause trail mark
pl_main_sl_0_c0_body:
                            xor         edx, edx               ; sub_cs=0 for first ucall
                            sub         rsp, 16
                            lea         rax, [rel pl_atom_sentence_7]
                            mov         [rsp + 0], rax
                            sub         rsp, 16            ; args[2] for compound ./2
                            lea         rax, [rel pl_atom_the_1]
                            mov         [rsp + 0], rax  ; compound arg 0
                            sub         rsp, 16            ; args[2] for compound ./2
                            lea         rax, [rel pl_atom_cat_2]
                            mov         [rsp + 0], rax  ; compound arg 0
                            sub         rsp, 16            ; args[2] for compound ./2
                            lea         rax, [rel pl_atom_chases_5]
                            mov         [rsp + 0], rax  ; compound arg 0
                            sub         rsp, 16            ; args[2] for compound ./2
                            lea         rax, [rel pl_atom_the_1]
                            mov         [rsp + 0], rax  ; compound arg 0
                            sub         rsp, 16            ; args[2] for compound ./2
                            lea         rax, [rel pl_atom_mouse_4]
                            mov         [rsp + 0], rax  ; compound arg 0
                            lea         rax, [rel pl_atom____8]
                            mov         [rsp + 8], rax  ; compound arg 1
                            mov         edi, dword [rel pl_atom___0 + 8]  ; functor atom_id
                            mov         esi, 2                   ; arity
                            mov         rdx, rsp                   ; args ptr
                            call        term_new_compound
                            add         rsp, 16
                            mov         [rsp + 8], rax  ; compound arg 1
                            mov         edi, dword [rel pl_atom___0 + 8]  ; functor atom_id
                            mov         esi, 2                   ; arity
                            mov         rdx, rsp                   ; args ptr
                            call        term_new_compound
                            add         rsp, 16
                            mov         [rsp + 8], rax  ; compound arg 1
                            mov         edi, dword [rel pl_atom___0 + 8]  ; functor atom_id
                            mov         esi, 2                   ; arity
                            mov         rdx, rsp                   ; args ptr
                            call        term_new_compound
                            add         rsp, 16
                            mov         [rsp + 8], rax  ; compound arg 1
                            mov         edi, dword [rel pl_atom___0 + 8]  ; functor atom_id
                            mov         esi, 2                   ; arity
                            mov         rdx, rsp                   ; args ptr
                            call        term_new_compound
                            add         rsp, 16
                            mov         [rsp + 8], rax  ; compound arg 1
                            mov         edi, dword [rel pl_atom___0 + 8]  ; functor atom_id
                            mov         esi, 2                   ; arity
                            mov         rdx, rsp                   ; args ptr
                            call        term_new_compound
                            add         rsp, 16
                            mov         [rsp + 8], rax
                            mov         rdi, rsp
                            lea         rsi, [rel pl_trail]
                            xor         edx, edx
                            call        pl_phrase_sl_2_r
                            add         rsp, 16
                            test        eax, eax
                            js          disj_main_sl_0_0_0_else
                            lea         rax, [rel pl_atom_yes_9]
                            mov         rdi, rax
                            call        pl_write
                            jmp         disj_main_sl_0_0_0_done
disj_main_sl_0_0_0_else:
                            lea         rax, [rel pl_atom_no_10]
                            mov         rdi, rax
                            call        pl_write
disj_main_sl_0_0_0_done:
                            mov         edi, 10         ; '\n'
                            call        putchar
                            sub         rsp, 16
                            lea         rax, [rel pl_atom_sentence_7]
                            mov         [rsp + 0], rax
                            sub         rsp, 16            ; args[2] for compound ./2
                            lea         rax, [rel pl_atom_the_1]
                            mov         [rsp + 0], rax  ; compound arg 0
                            sub         rsp, 16            ; args[2] for compound ./2
                            lea         rax, [rel pl_atom_dog_3]
                            mov         [rsp + 0], rax  ; compound arg 0
                            sub         rsp, 16            ; args[2] for compound ./2
                            lea         rax, [rel pl_atom_sees_6]
                            mov         [rsp + 0], rax  ; compound arg 0
                            lea         rax, [rel pl_atom____8]
                            mov         [rsp + 8], rax  ; compound arg 1
                            mov         edi, dword [rel pl_atom___0 + 8]  ; functor atom_id
                            mov         esi, 2                   ; arity
                            mov         rdx, rsp                   ; args ptr
                            call        term_new_compound
                            add         rsp, 16
                            mov         [rsp + 8], rax  ; compound arg 1
                            mov         edi, dword [rel pl_atom___0 + 8]  ; functor atom_id
                            mov         esi, 2                   ; arity
                            mov         rdx, rsp                   ; args ptr
                            call        term_new_compound
                            add         rsp, 16
                            mov         [rsp + 8], rax  ; compound arg 1
                            mov         edi, dword [rel pl_atom___0 + 8]  ; functor atom_id
                            mov         esi, 2                   ; arity
                            mov         rdx, rsp                   ; args ptr
                            call        term_new_compound
                            add         rsp, 16
                            mov         [rsp + 8], rax
                            mov         rdi, rsp
                            lea         rsi, [rel pl_trail]
                            xor         edx, edx
                            call        pl_phrase_sl_2_r
                            add         rsp, 16
                            test        eax, eax
                            js          disj_main_sl_0_0_2_else
                            lea         rax, [rel pl_atom_yes_9]
                            mov         rdi, rax
                            call        pl_write
                            jmp         disj_main_sl_0_0_2_done
disj_main_sl_0_0_2_else:
                            lea         rax, [rel pl_atom_no_10]
                            mov         rdi, rax
                            call        pl_write
disj_main_sl_0_0_2_done:
                            mov         edi, 10         ; '\n'
                            call        putchar
                            sub         rsp, 16
                            lea         rax, [rel pl_atom_sentence_7]
                            mov         [rsp + 0], rax
                            sub         rsp, 16            ; args[2] for compound ./2
                            lea         rax, [rel pl_atom_cat_2]
                            mov         [rsp + 0], rax  ; compound arg 0
                            sub         rsp, 16            ; args[2] for compound ./2
                            lea         rax, [rel pl_atom_chases_5]
                            mov         [rsp + 0], rax  ; compound arg 0
                            lea         rax, [rel pl_atom____8]
                            mov         [rsp + 8], rax  ; compound arg 1
                            mov         edi, dword [rel pl_atom___0 + 8]  ; functor atom_id
                            mov         esi, 2                   ; arity
                            mov         rdx, rsp                   ; args ptr
                            call        term_new_compound
                            add         rsp, 16
                            mov         [rsp + 8], rax  ; compound arg 1
                            mov         edi, dword [rel pl_atom___0 + 8]  ; functor atom_id
                            mov         esi, 2                   ; arity
                            mov         rdx, rsp                   ; args ptr
                            call        term_new_compound
                            add         rsp, 16
                            mov         [rsp + 8], rax
                            mov         rdi, rsp
                            lea         rsi, [rel pl_trail]
                            xor         edx, edx
                            call        pl_phrase_sl_2_r
                            add         rsp, 16
                            test        eax, eax
                            js          disj_main_sl_0_0_4_else
                            lea         rax, [rel pl_atom_yes_9]
                            mov         rdi, rax
                            call        pl_write
                            jmp         disj_main_sl_0_0_4_done
disj_main_sl_0_0_4_else:
                            lea         rax, [rel pl_atom_no_10]
                            mov         rdi, rax
                            call        pl_write
disj_main_sl_0_0_4_done:
                            mov         edi, 10         ; '\n'
                            call        putchar
; γ — success clause 0 (base=0 body_ucalls=0)
                            mov         eax, 1               ; base+1 → next clause
                            mov         rsp, rbp
                            pop         rbp
                            ret

pl_main_sl_0_ω:
; ω — all clauses exhausted
                            lea         rdi, [rel pl_trail]
                            mov         esi, [rbp - 8]         ; trail mark
                            call        trail_unwind
                            mov         rsp, rbp
                            pop         rbp
                            mov         eax, -1
                            ret

global pl_main_sl_0
pl_main_sl_0:
; single-shot wrapper: push start=0
                            xor         rdx, rdx
                            jmp         pl_main_sl_0_r

; ============================================================
; pl_rt_init — fix up atom_ids in .data Term structs
; ============================================================
pl_rt_init:
                            push        rbp
                            mov         rbp, rsp
                            lea         rdi, [rel pl_astr_0]
                            call        prolog_atom_intern
                            mov         dword [rel pl_atom___0 + 8], eax
                            lea         rdi, [rel pl_astr_1]
                            call        prolog_atom_intern
                            mov         dword [rel pl_atom_the_1 + 8], eax
                            lea         rdi, [rel pl_astr_2]
                            call        prolog_atom_intern
                            mov         dword [rel pl_atom_cat_2 + 8], eax
                            lea         rdi, [rel pl_astr_3]
                            call        prolog_atom_intern
                            mov         dword [rel pl_atom_dog_3 + 8], eax
                            lea         rdi, [rel pl_astr_4]
                            call        prolog_atom_intern
                            mov         dword [rel pl_atom_mouse_4 + 8], eax
                            lea         rdi, [rel pl_astr_5]
                            call        prolog_atom_intern
                            mov         dword [rel pl_atom_chases_5 + 8], eax
                            lea         rdi, [rel pl_astr_6]
                            call        prolog_atom_intern
                            mov         dword [rel pl_atom_sees_6 + 8], eax
                            lea         rdi, [rel pl_astr_7]
                            call        prolog_atom_intern
                            mov         dword [rel pl_atom_sentence_7 + 8], eax
                            lea         rdi, [rel pl_astr_8]
                            call        prolog_atom_intern
                            mov         dword [rel pl_atom____8 + 8], eax
                            lea         rdi, [rel pl_astr_9]
                            call        prolog_atom_intern
                            mov         dword [rel pl_atom_yes_9 + 8], eax
                            lea         rdi, [rel pl_astr_10]
                            call        prolog_atom_intern
                            mov         dword [rel pl_atom_no_10 + 8], eax
                            pop         rbp
                            ret

; ============================================================
; main
; ============================================================
main:
                            push        rbp
                            mov         rbp, rsp
; init atom table
                            call        prolog_atom_init
; init trail
                            lea         rdi, [rel pl_trail]
                            call        trail_init
; fix up atom_id fields
                            call        pl_rt_init
; call initialization predicate: main/0
                            xor         rdi, rdi               ; args=NULL (arity 0)
                            lea         rsi, [rel pl_trail]   ; Trail*
                            xor         edx, edx               ; start=0
                            call        pl_main_sl_0_r
; exit 0
                            xor         edi, edi
                            call        exit
                            pop         rbp
                            ret

section .rodata
pl_astr_0: db `.`,0
pl_astr_1: db `t`,`h`,`e`,0
pl_astr_2: db `c`,`a`,`t`,0
pl_astr_3: db `d`,`o`,`g`,0
pl_astr_4: db `m`,`o`,`u`,`s`,`e`,0
pl_astr_5: db `c`,`h`,`a`,`s`,`e`,`s`,0
pl_astr_6: db `s`,`e`,`e`,`s`,0
pl_astr_7: db `s`,`e`,`n`,`t`,`e`,`n`,`c`,`e`,0
pl_astr_8: db `[`,`]`,0
pl_astr_9: db `y`,`e`,`s`,0
pl_astr_10: db `n`,`o`,0

section .data
; TT_ATOM=0 — term_tag(4B) + saved_slot(4B) + atom_id(8B) = 16 bytes
pl_atom___0:
dd      0               ; tag = TT_ATOM
dd      0               ; saved_slot
dd      0               ; atom_id — filled by pl_rt_init
dd      0               ; atom_id high dword (padding)
dq      0               ; union padding (compound.args* slot)
pl_atom_the_1:
dd      0               ; tag = TT_ATOM
dd      0               ; saved_slot
dd      0               ; atom_id — filled by pl_rt_init
dd      0               ; atom_id high dword (padding)
dq      0               ; union padding (compound.args* slot)
pl_atom_cat_2:
dd      0               ; tag = TT_ATOM
dd      0               ; saved_slot
dd      0               ; atom_id — filled by pl_rt_init
dd      0               ; atom_id high dword (padding)
dq      0               ; union padding (compound.args* slot)
pl_atom_dog_3:
dd      0               ; tag = TT_ATOM
dd      0               ; saved_slot
dd      0               ; atom_id — filled by pl_rt_init
dd      0               ; atom_id high dword (padding)
dq      0               ; union padding (compound.args* slot)
pl_atom_mouse_4:
dd      0               ; tag = TT_ATOM
dd      0               ; saved_slot
dd      0               ; atom_id — filled by pl_rt_init
dd      0               ; atom_id high dword (padding)
dq      0               ; union padding (compound.args* slot)
pl_atom_chases_5:
dd      0               ; tag = TT_ATOM
dd      0               ; saved_slot
dd      0               ; atom_id — filled by pl_rt_init
dd      0               ; atom_id high dword (padding)
dq      0               ; union padding (compound.args* slot)
pl_atom_sees_6:
dd      0               ; tag = TT_ATOM
dd      0               ; saved_slot
dd      0               ; atom_id — filled by pl_rt_init
dd      0               ; atom_id high dword (padding)
dq      0               ; union padding (compound.args* slot)
pl_atom_sentence_7:
dd      0               ; tag = TT_ATOM
dd      0               ; saved_slot
dd      0               ; atom_id — filled by pl_rt_init
dd      0               ; atom_id high dword (padding)
dq      0               ; union padding (compound.args* slot)
pl_atom____8:
dd      0               ; tag = TT_ATOM
dd      0               ; saved_slot
dd      0               ; atom_id — filled by pl_rt_init
dd      0               ; atom_id high dword (padding)
dq      0               ; union padding (compound.args* slot)
pl_atom_yes_9:
dd      0               ; tag = TT_ATOM
dd      0               ; saved_slot
dd      0               ; atom_id — filled by pl_rt_init
dd      0               ; atom_id high dword (padding)
dq      0               ; union padding (compound.args* slot)
pl_atom_no_10:
dd      0               ; tag = TT_ATOM
dd      0               ; saved_slot
dd      0               ; atom_id — filled by pl_rt_init
dd      0               ; atom_id high dword (padding)
dq      0               ; union padding (compound.args* slot)
