:- initialization(main).
main :-
    open('/tmp/rung76_s.txt', write, WS),
    put_char(WS, a), put_char(WS, b), put_char(WS, c),
    close(WS),
    open('/tmp/rung76_s.txt', read, RS),
    ( at_end_of_stream(RS) -> write(at0_true) ; write(at0_false) ), nl,
    get_char(RS, C1), get_char(RS, C2), get_char(RS, C3),
    write(read(C1,C2,C3)), nl,
    ( at_end_of_stream(RS) -> write(ateof_true) ; write(ateof_false) ), nl,
    get_char(RS, C4),
    write(past(C4)), nl,
    ( at_end_of_stream(RS) -> write(pasteof_true) ; write(pasteof_false) ), nl,
    close(RS),
    open('/tmp/rung76_s.txt', read, RS2), set_input(RS2),
    ( at_end_of_stream -> write(cur_true) ; write(cur_false) ), nl,
    close(RS2),
    ( catch(at_end_of_stream(nosuch), error(existence_error(T,V),_), (write(exist(T,V)), nl)) -> true ; write(no_exist_check), nl ),
    ( catch(put_char(user_output, _), error(instantiation_error,_), (write(instantiation_caught), nl)) -> true ; write(no_inst_check), nl ),
    write(done), nl,
    halt.
