:- initialization(main).
main :-
    open('/tmp/rung72_ug.txt', write, WS), write(WS, 'ABC'), close(WS),
    open('/tmp/rung72_ug.txt', read, RS),
    get_char(RS, C1),
    unget_char(RS, C1),
    get_char(RS, C2),
    get_code(RS, D1),
    unget_code(RS, D1),
    get_code(RS, D2),
    close(RS),
    write(char(C1,C2)), nl,
    write(code(D1,D2)), nl,
    open('/tmp/rung72_ug.bin', write, WSB, [type(binary)]), put_byte(WSB, 200), close(WSB),
    open('/tmp/rung72_ug.bin', read, RSB, [type(binary)]),
    get_byte(RSB, B1),
    unget_byte(RSB, B1),
    get_byte(RSB, B2),
    close(RSB),
    write(byte(B1,B2)), nl,
    write(done), nl,
    halt.
