; JVM Jasmin output — generated by scrip --jit-emit --target=jvm
.class public Prog
.super java/lang/Object
.method public static main([Ljava/lang/String;)V
    .limit stack 10
    .limit locals 2
    invokestatic rt/SnoRt/init()V
    iconst_1
    i2l
    invokestatic rt/SnoRt/set_stno(J)V
    iconst_1
    i2l
    invokestatic rt/SnoRt/push_int(J)V
    ldc "I"
    invokestatic rt/SnoRt/store_var(Ljava/lang/String;)V
    iconst_2
    i2l
    invokestatic rt/SnoRt/set_stno(J)V
    ldc "I"
    invokestatic rt/SnoRt/push_var(Ljava/lang/String;)V
    ldc "OUTPUT"
    invokestatic rt/SnoRt/store_var(Ljava/lang/String;)V
    iconst_3
    i2l
    invokestatic rt/SnoRt/set_stno(J)V
    ldc "I"
    invokestatic rt/SnoRt/push_var(Ljava/lang/String;)V
    iconst_1
    i2l
    invokestatic rt/SnoRt/push_int(J)V
    bipush 1
    invokestatic rt/SnoRt/arith(I)V
    ldc "I"
    invokestatic rt/SnoRt/store_var(Ljava/lang/String;)V
    iconst_4
    i2l
    invokestatic rt/SnoRt/set_stno(J)V
    ldc "I"
    invokestatic rt/SnoRt/push_var(Ljava/lang/String;)V
    bipush 6
    i2l
    invokestatic rt/SnoRt/push_int(J)V
    invokestatic rt/SnoRt/pop_void()V
    iconst_5
    i2l
    invokestatic rt/SnoRt/set_stno(J)V
    invokestatic rt/SnoRt/halt_tos()V
    invokestatic rt/SnoRt/finalize_rt()I
    pop
    return
.end method
