:- initialization(main).
main :-
    read_term_from_atom('foo(x,y,z).', T1, []),
    writeq(T1), nl,
    read_term_from_atom('bar(A,B,A).', T2, [variables(V2)]),
    numbervars(t(T2,V2), 0, _),
    writeq(T2), nl, writeq(V2), nl,
    read_term_from_atom('bar(A,B,A).', T3, [variable_names(VN3)]),
    numbervars(VN3, 0, _),
    writeq(VN3), nl,
    read_term_from_atom('baz(P,Q,P,R).', T4, [singletons(S4)]),
    numbervars(t(T4,S4), 0, _),
    writeq(S4), nl,
    read_term_from_atom('quux(A,B,A,C,B).', T5, [variables(V5), variable_names(VN5), singletons(S5)]),
    numbervars(t(T5,V5,VN5,S5), 0, _),
    writeq(T5), nl, writeq(V5), nl, writeq(VN5), nl, writeq(S5), nl,
    read_term_from_chars([g,'(',a,',',b,')','.'], T6, [variables(V6)]),
    writeq(T6), nl, writeq(V6), nl,
    read_term_from_codes([104,105,40,88,44,89,41,46], T7, [variable_names(VN7)]),
    numbervars(VN7, 0, _),
    writeq(VN7), nl,
    write(done), nl.
