; Auto-generated by icon_emit.c — Tiny-ICON Byrd Box x64
bits 64
default rel

section .rodata
icn_str_0:  db  119, 111, 114, 108, 100, 0
icn_str_1:  db  104, 101, 108, 108, 111, 0
icn_str_2:  db  104, 101, 108, 108, 111, 0
icn_str_3:  db  104, 101, 108, 108, 111, 0

section .bss
    icn_retval: resq 1
    icn_sq3_lptr: resq 1
    icn_sq3_rptr: resq 1
    icn_sq9_lptr: resq 1
    icn_sq9_rptr: resq 1
    icn_failed: resb 1
    icn_suspended: resb 1
    icn_suspend_resume: resq 1
    icn_suspend_rbp: resq 1

section .text
    global _start
    extern icn_write_int
    extern icn_write_str
    extern icn_push
    extern icn_pop
    extern icn_str_concat
    extern icn_str_eq
    extern icn_any
    extern icn_many
    extern icn_upto
    extern icn_str_find
    extern icn_match
    extern icn_tab
    extern icn_move
    extern icn_subject
    extern icn_pos
    extern icn_str_cmp
    extern icn_strlen
    extern icn_pow
    extern icn_str_subscript
    extern icn_str_section
    extern icn_bang_char_at
    extern icn_match_pat
    extern icn_cset_complement
    extern icn_cset_union
    extern icn_cset_diff
    extern icn_cset_inter

_start:
    call    icn_main
    mov     rax, 60
    xor     rdi, rdi
    syscall


; === procedure main ===
    ; CALL write  id=1
    ; INT 2  id=2
icn_2_α:
    push    2
    jmp     icon_1_call
icn_2_β:
    jmp     icn_main_done
icn_1_α:
    jmp     icn_2_α
icn_1_β:
    jmp     icn_2_β
icon_1_call:
    pop     rdi
    call    icn_write_int
    jmp     icn_main_done
    ; SEQ  id=3
icn_4_α:
    lea     rdi, [rel icn_str_0]
    jmp     icon_3_rrelay
icn_4_β:
    jmp     icon_3_lb
icn_5_α:
    lea     rdi, [rel icn_str_1]
    jmp     icon_3_lrelay
icn_5_β:
    jmp     icon_0_else
icon_3_lrelay:
    mov     [rel icn_sq3_lptr], rdi
    jmp     icon_3_lstore
icon_3_rrelay:
    mov     [rel icn_sq3_rptr], rdi
    jmp     icon_3_check
icon_3_lb:
    jmp     icn_5_β
icn_3_α:
    jmp     icn_5_α
icn_3_β:
    jmp     icn_4_β
icon_3_lstore:
    jmp     icn_4_α
icon_3_check:
    mov     rdi, [rel icn_sq3_lptr]
    mov     rsi, [rel icn_sq3_rptr]
    call    icn_str_eq
    test    rax, rax
    jz      icn_4_β
    push    0
    jmp     icon_0_then
icon_0_then:
    add     rsp, 8
    jmp     icn_1_α
icon_0_else:
    jmp     icn_main_done
icn_0_α:
    jmp     icn_3_α
icn_0_β:
    jmp     icn_3_β
    ; CALL write  id=7
    ; INT 1  id=8
icn_8_α:
    push    1
    jmp     icon_7_call
icn_8_β:
    jmp     icn_0_α
icn_7_α:
    jmp     icn_8_α
icn_7_β:
    jmp     icn_8_β
icon_7_call:
    pop     rdi
    call    icn_write_int
    jmp     icn_0_α
    ; SEQ  id=9
icn_10_α:
    lea     rdi, [rel icn_str_2]
    jmp     icon_9_rrelay
icn_10_β:
    jmp     icon_9_lb
icn_11_α:
    lea     rdi, [rel icn_str_3]
    jmp     icon_9_lrelay
icn_11_β:
    jmp     icon_6_else
icon_9_lrelay:
    mov     [rel icn_sq9_lptr], rdi
    jmp     icon_9_lstore
icon_9_rrelay:
    mov     [rel icn_sq9_rptr], rdi
    jmp     icon_9_check
icon_9_lb:
    jmp     icn_11_β
icn_9_α:
    jmp     icn_11_α
icn_9_β:
    jmp     icn_10_β
icon_9_lstore:
    jmp     icn_10_α
icon_9_check:
    mov     rdi, [rel icn_sq9_lptr]
    mov     rsi, [rel icn_sq9_rptr]
    call    icn_str_eq
    test    rax, rax
    jz      icn_10_β
    push    0
    jmp     icon_6_then
icon_6_then:
    add     rsp, 8
    jmp     icn_7_α
icon_6_else:
    jmp     icn_0_α
icn_6_α:
    jmp     icn_9_α
icn_6_β:
    jmp     icn_9_β
icn_main:
    push    rbp
    mov     rbp, rsp
    jmp     icn_6_α
icn_main_done:
    mov     byte [rel icn_failed], 1
    pop     rbp
    ret
