; Auto-generated by icon_emit.c — Tiny-ICON Byrd Box x64
bits 64
default rel

section .rodata
icn_str_0:  db  104, 101, 108, 108, 111, 32, 0
icn_str_1:  db  119, 111, 114, 108, 100, 0

section .bss
    icn_retval: resq 1
    icn_cc1_lptr: resq 1
    icn_cc1_rptr: resq 1
    icn_failed: resb 1
    icn_suspended: resb 1
    icn_suspend_resume: resq 1
    icn_suspend_rbp: resq 1

section .text
    global _start
    extern icn_write_int
    extern icn_write_str
    extern icn_push
    extern icn_pop
    extern icn_str_concat
    extern icn_str_eq
    extern icn_any
    extern icn_many
    extern icn_upto
    extern icn_str_find
    extern icn_match
    extern icn_tab
    extern icn_move
    extern icn_subject
    extern icn_pos
    extern icn_str_cmp
    extern icn_strlen
    extern icn_pow
    extern icn_str_subscript
    extern icn_str_section
    extern icn_bang_char_at
    extern icn_match_pat
    extern icn_cset_complement
    extern icn_cset_union
    extern icn_cset_diff
    extern icn_cset_inter

_start:
    call    icn_main
    mov     rax, 60
    xor     rdi, rdi
    syscall


; === procedure greet ===
    ; CONCAT  id=1
    ; VAR name  id=2
icn_2_α:
    mov     rax, [rbp-8]
    push    rax
    jmp     icon_1_rrelay
icn_2_β:
    jmp     icon_1_lb
icn_3_α:
    lea     rdi, [rel icn_str_0]
    jmp     icon_1_lrelay
icn_3_β:
    jmp     icon_0_ret_store
icon_1_lrelay:
    mov     [rel icn_cc1_lptr], rdi
    jmp     icon_1_lstore
icon_1_rrelay:
    pop     rax
    mov     [rel icn_cc1_rptr], rax
    jmp     icon_1_compute
icon_1_lb:
    jmp     icn_3_β
icn_1_α:
    mov     qword [rbp-16], 0
    jmp     icn_3_α
icn_1_β:
    mov     qword [rbp-16], 1
    jmp     icn_3_α
icon_1_lstore:
    cmp     qword [rbp-16], 0
    je      icn_2_α
    jmp     icn_2_β
icon_1_compute:
    mov     rdi, [rel icn_cc1_lptr]
    mov     rsi, [rel icn_cc1_rptr]
    call    icn_str_concat
    push    rax
    jmp     icon_0_ret_store
icn_0_α:
    jmp     icn_1_α
icn_0_β:
    jmp     icn_u_greet_ret
icon_0_ret_store:
    pop     rax
    mov     [rel icn_retval], rax
    mov     byte [rel icn_failed], 0
    jmp     icn_u_greet_ret
icn_u_greet:
    push    rbp
    mov     rbp, rsp
    sub     rsp, 32
    call    icn_pop
    mov     [rbp-8], rax
    jmp     icn_0_α
icn_u_greet_ret:
    add     rsp, 32
    pop     rbp
    ret
icn_u_greet_done:
    mov     byte [rel icn_failed], 1
    add     rsp, 32
    pop     rbp
    ret

; === procedure main ===
    ; CALL write  id=4
    ; CALL greet  id=5
icn_6_α:
    lea     rdi, [rel icn_str_1]
    jmp     icon_5_push0
icn_6_β:
    jmp     icn_main_done
icon_5_push0:
    pop     rdi
    call    icn_push
    jmp     icon_5_docall
icn_5_α:
    jmp     icn_6_α
icn_5_β:
    jmp     icn_main_done
icon_5_docall:
    call    icn_u_greet
    movzx   rax, byte [rel icn_failed]
    test    rax, rax
    jnz     icn_main_done
    mov     rax, [rel icn_retval]
    push    rax
    jmp     icon_4_call
icn_4_α:
    jmp     icn_5_α
icn_4_β:
    jmp     icn_5_β
icon_4_call:
    pop     rdi
    call    icn_write_int
    jmp     icn_main_done
icn_main:
    push    rbp
    mov     rbp, rsp
    jmp     icn_4_α
icn_main_done:
    mov     byte [rel icn_failed], 1
    pop     rbp
    ret
