; Auto-generated by icon_emit.c — Tiny-ICON Byrd Box x64
bits 64
default rel

section .rodata
icn_str_0:  db  91, 100, 111, 110, 101, 93, 0
icn_str_1:  db  45, 118, 0
icn_str_2:  db  9, 91, 111, 107, 93, 0
icn_str_3:  db  84, 91, 0
icn_str_4:  db  99, 104, 101, 99, 107, 105, 110, 103, 32, 107, 101, 121, 40, 84, 41, 58, 0
icn_str_5:  db  84, 91, 0
icn_str_6:  db  99, 104, 101, 99, 107, 105, 110, 103, 32, 33, 84, 58, 0
icn_str_7:  db  83, 91, 0
icn_str_8:  db  99, 104, 101, 99, 107, 105, 110, 103, 32, 33, 83, 58, 0

section .bss
    icn_retval: resq 1
    icn_gvar_verbose: resq 1
    icn_sq30_lptr: resq 1
    icn_sq30_rptr: resq 1
    icn_gvar_l: resq 1
    icn_gvar_s: resq 1
    icn_gvar_s1: resq 1
    icn_43_I: resq 1
    icon_43_bound: resq 1
    icon_43_e1cur: resq 1
    icon_43_e2seen: resq 1
    icn_gvar_s2: resq 1
    icn_67_I: resq 1
    icon_67_bound: resq 1
    icon_67_e1cur: resq 1
    icon_67_e2seen: resq 1
    icn_gvar_k: resq 1
    icn_gvar_ok: resq 1
    icn_gvar_&null: resq 1
    icon_93_bang_str: resq 1
    icon_93_bang_pos: resq 1
    icn_gvar_e: resq 1
    icn_gvar_sg: resq 1
    icn_cbo112_lptr: resq 1
    icn_cbo112_rptr: resq 1
    icn_cbo126_lptr: resq 1
    icn_cbo126_rptr: resq 1
    icn_gvar_i: resq 1
    icn_gvar_T: resq 1
    icon_164_bang_str: resq 1
    icon_164_bang_pos: resq 1
    icon_177_bang_str: resq 1
    icon_177_bang_pos: resq 1
    icn_gvar_S: resq 1
    icn_187_I: resq 1
    icon_187_bound: resq 1
    icon_187_e1cur: resq 1
    icon_187_e2seen: resq 1
    icn_gvar_N: resq 1
    icn_failed: resb 1
    icn_suspended: resb 1
    icn_suspend_resume: resq 1
    icn_suspend_rbp: resq 1

section .text
    global _start
    extern icn_write_int
    extern icn_write_str
    extern icn_push
    extern icn_pop
    extern icn_str_concat
    extern icn_str_eq
    extern icn_any
    extern icn_many
    extern icn_upto
    extern icn_str_find
    extern icn_match
    extern icn_tab
    extern icn_move
    extern icn_subject
    extern icn_pos
    extern icn_str_cmp
    extern icn_strlen
    extern icn_pow
    extern icn_str_subscript
    extern icn_str_section
    extern icn_bang_char_at
    extern icn_match_pat
    extern icn_cset_complement
    extern icn_cset_union
    extern icn_cset_diff
    extern icn_cset_inter

_start:
    call    icn_main
    mov     rax, 60
    xor     rdi, rdi
    syscall


; === procedure main ===
    ; CALL write  id=0
icn_1_α:
    lea     rdi, [rel icn_str_0]
    jmp     icon_0_call
icn_1_β:
    jmp     icn_main_done
icn_0_α:
    jmp     icn_1_α
icn_0_β:
    jmp     icn_1_β
icon_0_call:
    call    icn_write_str
    jmp     icn_main_done
    ; CALL stale  id=2
icn_2_α:
    jmp     icon_2_docall
icn_2_β:
    jmp     icn_0_α
icon_2_docall:
    call    icn_u_stale
    movzx   rax, byte [rel icn_failed]
    test    rax, rax
    jnz     icn_0_α
    mov     rax, [rel icn_retval]
    push    rax
    jmp     icn_0_α
    ; EVERY  id=3
    ; CALL tins  id=4
    ; INT 23  id=6
icn_6_α:
    push    23
    jmp     icon_4_push2
icn_6_β:
    jmp     icn_2_α
    ; INT 11  id=7
icn_7_α:
    push    11
    jmp     icon_4_push2
icn_7_β:
    jmp     icn_6_α
    ; INT 3  id=8
icn_8_α:
    push    3
    jmp     icon_4_push2
icn_8_β:
    jmp     icn_7_α
icn_5_α:
    jmp     icn_8_α
icn_5_β:
    jmp     icn_8_β
icon_4_push2:
    pop     rdi
    call    icn_push
    jmp     icon_4_docall
    ; INT 503  id=10
icn_10_α:
    push    503
    jmp     icon_4_push1
icn_10_β:
    jmp     icn_2_α
    ; INT 419  id=11
icn_11_α:
    push    419
    jmp     icon_4_push1
icn_11_β:
    jmp     icn_10_α
    ; INT 239  id=12
icn_12_α:
    push    239
    jmp     icon_4_push1
icn_12_β:
    jmp     icn_11_α
icn_9_α:
    jmp     icn_12_α
icn_9_β:
    jmp     icn_12_β
icon_4_push1:
    pop     rdi
    call    icn_push
    jmp     icn_5_α
    ; INT 233  id=14
icn_14_α:
    push    233
    jmp     icon_4_push0
icn_14_β:
    jmp     icn_2_α
    ; INT 103  id=15
icn_15_α:
    push    103
    jmp     icon_4_push0
icn_15_β:
    jmp     icn_14_α
    ; INT 40  id=16
icn_16_α:
    push    40
    jmp     icon_4_push0
icn_16_β:
    jmp     icn_15_α
icn_13_α:
    jmp     icn_16_α
icn_13_β:
    jmp     icn_16_β
icon_4_push0:
    pop     rdi
    call    icn_push
    jmp     icn_9_α
icn_4_α:
    jmp     icn_13_α
icn_4_β:
    jmp     icn_2_α
icon_4_docall:
    call    icn_u_tins
    movzx   rax, byte [rel icn_failed]
    test    rax, rax
    jnz     icn_2_α
    mov     rax, [rel icn_retval]
    push    rax
    jmp     icon_3_genb
icon_3_genb:
    jmp     icn_4_β
icn_3_α:
    jmp     icn_4_α
icn_3_β:
    jmp     icn_2_α
    ; EVERY  id=17
    ; CALL tdel  id=18
    ; INT 23  id=20
icn_20_α:
    push    23
    jmp     icon_18_push1
icn_20_β:
    jmp     icn_3_α
    ; INT 11  id=21
icn_21_α:
    push    11
    jmp     icon_18_push1
icn_21_β:
    jmp     icn_20_α
    ; INT 3  id=22
icn_22_α:
    push    3
    jmp     icon_18_push1
icn_22_β:
    jmp     icn_21_α
icn_19_α:
    jmp     icn_22_α
icn_19_β:
    jmp     icn_22_β
icon_18_push1:
    pop     rdi
    call    icn_push
    jmp     icon_18_docall
    ; INT 991  id=24
icn_24_α:
    push    991
    jmp     icon_18_push0
icn_24_β:
    jmp     icn_3_α
    ; INT 619  id=25
icn_25_α:
    push    619
    jmp     icon_18_push0
icn_25_β:
    jmp     icn_24_α
    ; INT 41  id=26
icn_26_α:
    push    41
    jmp     icon_18_push0
icn_26_β:
    jmp     icn_25_α
icn_23_α:
    jmp     icn_26_α
icn_23_β:
    jmp     icn_26_β
icon_18_push0:
    pop     rdi
    call    icn_push
    jmp     icn_19_α
icn_18_α:
    jmp     icn_23_α
icn_18_β:
    jmp     icn_3_α
icon_18_docall:
    call    icn_u_tdel
    movzx   rax, byte [rel icn_failed]
    test    rax, rax
    jnz     icn_3_α
    mov     rax, [rel icn_retval]
    push    rax
    jmp     icon_17_genb
icon_17_genb:
    jmp     icn_18_β
icn_17_α:
    jmp     icn_18_α
icn_17_β:
    jmp     icn_3_α
    ; INT 1  id=29
icn_29_α:
    push    1
    jmp     icon_28_store
icn_29_β:
    jmp     icn_17_α
icn_28_α:
    jmp     icn_29_α
icn_28_β:
    jmp     icn_29_β
icon_28_store:
    pop     rax
    mov     [rel icn_gvar_verbose], rax
    jmp     icn_17_α
    ; SEQ  id=30
icn_31_α:
    lea     rdi, [rel icn_str_1]
    jmp     icon_30_rrelay
icn_31_β:
    jmp     icon_30_lb
    ; INT 1  id=33
icn_33_α:
    push    1
    jmp     icon_32_sub_gi
icn_33_β:
    jmp     icon_27_else
    ; VAR args  id=34
icn_34_α:
    mov     rax, [rbp-8]
    push    rax
    jmp     icon_32_sub_go
icn_34_β:
    jmp     icon_27_else
icn_32_α:
    jmp     icn_34_α
icn_32_β:
    jmp     icn_33_β
icon_32_sub_gi:
    pop     rax
    mov     [rbp-16], rax
    jmp     icn_34_α
icon_32_sub_go:
    pop     rdi
    mov     rsi, [rbp-16]
    dec     rsi
    call    icn_str_subscript
    push    rax
    jmp     icon_30_lrelay
icon_30_lrelay:
    pop     rax
    mov     [rel icn_sq30_lptr], rax
    jmp     icon_30_lstore
icon_30_rrelay:
    mov     [rel icn_sq30_rptr], rdi
    jmp     icon_30_check
icon_30_lb:
    jmp     icn_32_β
icn_30_α:
    jmp     icn_32_α
icn_30_β:
    jmp     icn_31_β
icon_30_lstore:
    jmp     icn_31_α
icon_30_check:
    mov     rdi, [rel icn_sq30_lptr]
    mov     rsi, [rel icn_sq30_rptr]
    call    icn_str_eq
    test    rax, rax
    jz      icn_31_β
    push    0
    jmp     icon_27_then
icon_27_then:
    add     rsp, 8
    jmp     icn_28_α
icon_27_else:
    jmp     icn_17_α
icn_27_α:
    jmp     icn_30_α
icn_27_β:
    jmp     icn_30_β
icn_main:
    push    rbp
    mov     rbp, rsp
    sub     rsp, 32
    jmp     icn_27_α
icn_main_done:
    mov     byte [rel icn_failed], 1
    add     rsp, 32
    pop     rbp
    ret

; === procedure tins ===
    ; CALL check  id=35
    ; VAR l  id=36
icn_36_α:
    mov     rax, [rel icn_gvar_l]
    push    rax
    jmp     icon_35_push2
icn_36_β:
    jmp     icn_u_tins_done
icon_35_push2:
    pop     rdi
    call    icn_push
    jmp     icon_35_docall
    ; VAR s  id=37
icn_37_α:
    mov     rax, [rel icn_gvar_s]
    push    rax
    jmp     icon_35_push1
icn_37_β:
    jmp     icn_u_tins_done
icon_35_push1:
    pop     rdi
    call    icn_push
    jmp     icn_36_α
    ; VAR s1  id=38
icn_38_α:
    mov     rax, [rel icn_gvar_s1]
    push    rax
    jmp     icon_35_push0
icn_38_β:
    jmp     icn_u_tins_done
icon_35_push0:
    pop     rdi
    call    icn_push
    jmp     icn_37_α
icn_35_α:
    jmp     icn_38_α
icn_35_β:
    jmp     icn_u_tins_done
icon_35_docall:
    call    icn_u_check
    movzx   rax, byte [rel icn_failed]
    test    rax, rax
    jnz     icn_u_tins_done
    mov     rax, [rel icn_retval]
    push    rax
    jmp     icn_u_tins_done
    ; EVERY  id=39
    ; EVERY  id=41
    ; CALL insert  id=42
icn_42_α:
    jmp     icon_41_genb
icn_42_β:
    jmp     icon_41_genb
    ; TO  id=43
    ; VAR n  id=44
icn_44_α:
    mov     rax, [rbp-24]
    push    rax
    jmp     icon_43_init
icn_44_β:
    jmp     icon_43_e1b
    ; INT 1  id=45
icn_45_α:
    push    1
    jmp     icn_44_α
icn_45_β:
    jmp     icon_39_genb
icon_43_e1b:
    mov     qword [rel icon_43_e2seen], 0
    jmp     icn_45_β
icon_43_e2b:
    jmp     icn_44_β
icn_43_α:
    mov     qword [rel icon_43_e2seen], 0
    jmp     icn_45_α
icn_43_β:
    inc     qword [rel icn_43_I]
    jmp     icn_43_code
icon_43_init:
    pop     rax
    mov     [rel icon_43_bound], rax
    cmp     qword [rel icon_43_e2seen], 0
    jne     icon_43_init_e2adv
    pop     rax
    mov     [rel icon_43_e1cur], rax
    mov     [rel icn_43_I], rax
    mov     qword [rel icon_43_e2seen], 1
    jmp     icn_43_code
icon_43_init_e2adv:
    mov     rax, [rel icon_43_e1cur]
    mov     [rel icn_43_I], rax
    jmp     icn_43_code
icn_43_code:
    mov     rax, [rel icn_43_I]
    cmp     rax, [rel icon_43_bound]
    jg      icon_43_e2b
    push    rax
    jmp     icon_41_body
icon_41_body:
    jmp     icn_42_α
icon_41_genb:
    jmp     icn_43_β
icn_41_α:
    jmp     icn_43_α
icn_41_β:
    jmp     icon_39_genb
    ; LT  id=46
    ; VAR limit  id=47
icn_47_α:
    mov     rax, [rbp-16]
    push    rax
    jmp     icon_46_check
icn_47_β:
    jmp     icon_46_lb
    ; VAR s  id=49
icn_49_α:
    mov     rax, [rel icn_gvar_s]
    push    rax
    jmp     icon_48_size_relay
icn_49_β:
    jmp     icon_40_else
icn_48_α:
    jmp     icn_49_α
icn_48_β:
    jmp     icn_49_β
icon_48_size_relay:
    pop     rdi
    call    icn_strlen
    push    rax
    jmp     icon_46_lstore
icon_46_lb:
    jmp     icn_48_β
icn_46_α:
    jmp     icn_48_α
icn_46_β:
    jmp     icn_47_β
icon_46_lstore:
    pop     rax
    mov     [rbp-32], rax
    jmp     icn_47_α
icon_46_check:
    pop     rcx
    mov     rax, [rbp-32]
    cmp     rax, rcx
    jge      icn_47_β
    push    rcx
    jmp     icon_40_then
icon_40_then:
    add     rsp, 8
    jmp     icn_41_α
icon_40_else:
    jmp     icon_39_genb
icn_40_α:
    jmp     icn_46_α
icn_40_β:
    jmp     icn_46_β
    ; CALL put  id=50
icn_50_α:
    jmp     icn_35_α
icn_50_β:
    jmp     icn_35_α
icon_39_body:
    jmp     icn_40_α
icon_39_genb:
    jmp     icn_50_β
icn_39_α:
    jmp     icn_50_α
icn_39_β:
    jmp     icn_35_α
    ; CALL list  id=52
icn_52_α:
    jmp     icn_39_α
icn_52_β:
    jmp     icn_39_α
icn_51_α:
    jmp     icn_52_α
icn_51_β:
    jmp     icn_52_β
icon_51_store:
    pop     rax
    mov     [rel icn_gvar_l], rax
    jmp     icn_39_α
    ; CALL copy  id=54
icn_54_α:
    jmp     icn_51_α
icn_54_β:
    jmp     icn_51_α
icn_53_α:
    jmp     icn_54_α
icn_53_β:
    jmp     icn_54_β
icon_53_store:
    pop     rax
    mov     [rel icn_gvar_s1], rax
    jmp     icn_51_α
    ; EVERY  id=55
    ; CALL insert  id=56
icn_56_α:
    jmp     icn_53_α
icn_56_β:
    jmp     icn_53_α
icon_55_genb:
    jmp     icn_56_β
icn_55_α:
    jmp     icn_56_α
icn_55_β:
    jmp     icn_53_α
    ; CALL set  id=58
icn_58_α:
    jmp     icn_55_α
icn_58_β:
    jmp     icn_55_α
icn_57_α:
    jmp     icn_58_α
icn_57_β:
    jmp     icn_58_β
icon_57_store:
    pop     rax
    mov     [rel icn_gvar_s], rax
    jmp     icn_55_α
    ; CALL writes  id=59
icn_59_α:
    jmp     icn_57_α
icn_59_β:
    jmp     icn_57_α
icn_u_tins:
    push    rbp
    mov     rbp, rsp
    sub     rsp, 48
    call    icn_pop
    mov     [rbp-24], rax
    call    icn_pop
    mov     [rbp-16], rax
    call    icn_pop
    mov     [rbp-8], rax
    jmp     icn_59_α
icn_u_tins_ret:
    add     rsp, 48
    pop     rbp
    ret
icn_u_tins_done:
    mov     byte [rel icn_failed], 1
    add     rsp, 48
    pop     rbp
    ret

; === procedure tdel ===
    ; CALL check  id=60
    ; VAR l  id=61
icn_61_α:
    mov     rax, [rel icn_gvar_l]
    push    rax
    jmp     icon_60_push2
icn_61_β:
    jmp     icn_u_tdel_done
icon_60_push2:
    pop     rdi
    call    icn_push
    jmp     icon_60_docall
    ; VAR s2  id=62
icn_62_α:
    mov     rax, [rel icn_gvar_s2]
    push    rax
    jmp     icon_60_push1
icn_62_β:
    jmp     icn_u_tdel_done
icon_60_push1:
    pop     rdi
    call    icn_push
    jmp     icn_61_α
    ; VAR s  id=63
icn_63_α:
    mov     rax, [rel icn_gvar_s]
    push    rax
    jmp     icon_60_push0
icn_63_β:
    jmp     icn_u_tdel_done
icon_60_push0:
    pop     rdi
    call    icn_push
    jmp     icn_62_α
icn_60_α:
    jmp     icn_63_α
icn_60_β:
    jmp     icn_u_tdel_done
icon_60_docall:
    call    icn_u_check
    movzx   rax, byte [rel icn_failed]
    test    rax, rax
    jnz     icn_u_tdel_done
    mov     rax, [rel icn_retval]
    push    rax
    jmp     icn_u_tdel_done
    ; EVERY  id=64
    ; EVERY  id=65
    ; CALL delete  id=66
icn_66_α:
    jmp     icon_65_genb
icn_66_β:
    jmp     icon_65_genb
    ; TO  id=67
    ; VAR n  id=68
icn_68_α:
    mov     rax, [rbp-16]
    push    rax
    jmp     icon_67_init
icn_68_β:
    jmp     icon_67_e1b
    ; INT 1  id=69
icn_69_α:
    push    1
    jmp     icn_68_α
icn_69_β:
    jmp     icon_64_genb
icon_67_e1b:
    mov     qword [rel icon_67_e2seen], 0
    jmp     icn_69_β
icon_67_e2b:
    jmp     icn_68_β
icn_67_α:
    mov     qword [rel icon_67_e2seen], 0
    jmp     icn_69_α
icn_67_β:
    inc     qword [rel icn_67_I]
    jmp     icn_67_code
icon_67_init:
    pop     rax
    mov     [rel icon_67_bound], rax
    cmp     qword [rel icon_67_e2seen], 0
    jne     icon_67_init_e2adv
    pop     rax
    mov     [rel icon_67_e1cur], rax
    mov     [rel icn_67_I], rax
    mov     qword [rel icon_67_e2seen], 1
    jmp     icn_67_code
icon_67_init_e2adv:
    mov     rax, [rel icon_67_e1cur]
    mov     [rel icn_67_I], rax
    jmp     icn_67_code
icn_67_code:
    mov     rax, [rel icn_67_I]
    cmp     rax, [rel icon_67_bound]
    jg      icon_67_e2b
    push    rax
    jmp     icon_65_body
icon_65_body:
    jmp     icn_66_α
icon_65_genb:
    jmp     icn_67_β
icn_65_α:
    jmp     icn_67_α
icn_65_β:
    jmp     icon_64_genb
    ; CALL put  id=70
icn_70_α:
    jmp     icn_60_α
icn_70_β:
    jmp     icn_60_α
icon_64_body:
    jmp     icn_65_α
icon_64_genb:
    jmp     icn_70_β
icn_64_α:
    jmp     icn_70_α
icn_64_β:
    jmp     icn_60_α
    ; INT 0  id=72
icn_72_α:
    push    0
    jmp     icon_71_store
icn_72_β:
    jmp     icn_64_α
icn_71_α:
    jmp     icn_72_α
icn_71_β:
    jmp     icn_72_β
icon_71_store:
    pop     rax
    mov     [rel icn_gvar_k], rax
    jmp     icn_64_α
    ; CALL list  id=74
icn_74_α:
    jmp     icn_71_α
icn_74_β:
    jmp     icn_71_α
icn_73_α:
    jmp     icn_74_α
icn_73_β:
    jmp     icn_74_β
icon_73_store:
    pop     rax
    mov     [rel icn_gvar_l], rax
    jmp     icn_71_α
    ; CALL copy  id=76
icn_76_α:
    jmp     icn_73_α
icn_76_β:
    jmp     icn_73_α
icn_75_α:
    jmp     icn_76_α
icn_75_β:
    jmp     icn_76_β
icon_75_store:
    pop     rax
    mov     [rel icn_gvar_s2], rax
    jmp     icn_73_α
    ; EVERY  id=77
    ; CALL insert  id=78
icn_78_α:
    jmp     icn_75_α
icn_78_β:
    jmp     icn_75_α
icon_77_genb:
    jmp     icn_78_β
icn_77_α:
    jmp     icn_78_α
icn_77_β:
    jmp     icn_75_α
    ; CALL set  id=80
icn_80_α:
    jmp     icn_77_α
icn_80_β:
    jmp     icn_77_α
icn_79_α:
    jmp     icn_80_α
icn_79_β:
    jmp     icn_80_β
icon_79_store:
    pop     rax
    mov     [rel icn_gvar_s], rax
    jmp     icn_77_α
    ; CALL writes  id=81
icn_81_α:
    jmp     icn_79_α
icn_81_β:
    jmp     icn_79_α
icn_u_tdel:
    push    rbp
    mov     rbp, rsp
    sub     rsp, 32
    call    icn_pop
    mov     [rbp-16], rax
    call    icn_pop
    mov     [rbp-8], rax
    jmp     icn_81_α
icn_u_tdel_ret:
    add     rsp, 32
    pop     rbp
    ret
icn_u_tdel_done:
    mov     byte [rel icn_failed], 1
    add     rsp, 32
    pop     rbp
    ret

; === procedure check ===
    ; CALL write  id=82
    ; VAR ok  id=83
icn_83_α:
    mov     rax, [rel icn_gvar_ok]
    push    rax
    jmp     icon_82_call
icn_83_β:
    jmp     icn_u_check_done
icn_82_α:
    jmp     icn_83_α
icn_82_β:
    jmp     icn_83_β
icon_82_call:
    pop     rdi
    call    icn_write_int
    jmp     icn_u_check_done
    ; VAR &null  id=87
icn_87_α:
    mov     rax, [rel icn_gvar_&null]
    push    rax
    jmp     icon_86_store
icn_87_β:
    jmp     icn_82_α
icn_86_α:
    jmp     icn_87_α
icn_86_β:
    jmp     icn_87_β
icon_86_store:
    pop     rax
    mov     [rel icn_gvar_ok], rax
    jmp     icn_82_α
    ; EVERY  id=88
    ; CALL writes  id=90
icn_90_α:
    jmp     icon_88_genb
icn_90_β:
    jmp     icon_88_genb
    ; CALL delete  id=91
icn_91_α:
    jmp     icn_90_α
icn_91_β:
    jmp     icn_90_α
icn_89_α:
    jmp     icn_91_α
icn_89_β:
    jmp     icn_91_β
    ; VAR l  id=94
icn_94_α:
    mov     rax, [rbp-24]
    push    rax
    jmp     icon_93_bang_as
icn_94_β:
    jmp     icn_82_α
icon_93_bang_as:
    pop     rax
    mov     [rel icon_93_bang_str], rax
    mov     qword [rel icon_93_bang_pos], 0
icon_93_bang_chk:
    mov     rdi, [rel icon_93_bang_str]
    call    icn_strlen
    cmp     [rel icon_93_bang_pos], rax
    jge     icn_82_α
    mov     rdi, [rel icon_93_bang_str]
    mov     rsi, [rel icon_93_bang_pos]
    call    icn_bang_char_at
    push    rax
    inc     qword [rel icon_93_bang_pos]
    jmp     icon_92_store
icn_93_α:
    jmp     icn_94_α
icn_93_β:
    jmp     icon_93_bang_chk
icn_92_α:
    jmp     icn_93_α
icn_92_β:
    jmp     icn_93_β
icon_92_store:
    pop     rax
    mov     [rel icn_gvar_e], rax
    jmp     icon_88_body
icon_88_body:
    jmp     icn_89_α
icon_88_genb:
    jmp     icn_92_β
icn_88_α:
    jmp     icn_92_α
icn_88_β:
    jmp     icn_82_α
icon_85_seq_1:
    add     rsp, 8
    jmp     icn_86_α
    ; CALL writes  id=95
icn_95_α:
    jmp     icn_82_α
icn_95_β:
    jmp     icn_82_α
icon_85_seq_0:
    add     rsp, 8
    jmp     icn_88_α
icn_85_α:
    jmp     icn_95_α
icn_85_β:
    jmp     icn_82_α
    ; LT  id=96
    ; VAR l  id=98
icn_98_α:
    mov     rax, [rbp-24]
    push    rax
    jmp     icon_97_size_relay
icn_98_β:
    jmp     icon_96_lb
icn_97_α:
    jmp     icn_98_α
icn_97_β:
    jmp     icn_98_β
icon_97_size_relay:
    pop     rdi
    call    icn_strlen
    push    rax
    jmp     icon_96_check
    ; VAR sg  id=100
icn_100_α:
    mov     rax, [rel icn_gvar_sg]
    push    rax
    jmp     icon_99_size_relay
icn_100_β:
    jmp     icon_84_else
icn_99_α:
    jmp     icn_100_α
icn_99_β:
    jmp     icn_100_β
icon_99_size_relay:
    pop     rdi
    call    icn_strlen
    push    rax
    jmp     icon_96_lstore
icon_96_lb:
    jmp     icn_99_β
icn_96_α:
    jmp     icn_99_α
icn_96_β:
    jmp     icn_97_β
icon_96_lstore:
    pop     rax
    mov     [rbp-32], rax
    jmp     icn_97_α
icon_96_check:
    pop     rcx
    mov     rax, [rbp-32]
    cmp     rax, rcx
    jge      icn_97_β
    push    rcx
    jmp     icon_84_then
icon_84_then:
    add     rsp, 8
    jmp     icn_85_α
icon_84_else:
    jmp     icn_82_α
icn_84_α:
    jmp     icn_96_α
icn_84_β:
    jmp     icn_96_β
    ; VAR &null  id=104
icn_104_α:
    mov     rax, [rel icn_gvar_&null]
    push    rax
    jmp     icon_103_store
icn_104_β:
    jmp     icn_84_α
icn_103_α:
    jmp     icn_104_α
icn_103_β:
    jmp     icn_104_β
icon_103_store:
    pop     rax
    mov     [rel icn_gvar_ok], rax
    jmp     icn_84_α
    ; EVERY  id=105
    ; CALL writes  id=106
icn_106_α:
    jmp     icn_84_α
icn_106_β:
    jmp     icn_84_α
icon_105_genb:
    jmp     icn_106_β
icn_105_α:
    jmp     icn_106_α
icn_105_β:
    jmp     icn_84_α
icon_102_seq_1:
    add     rsp, 8
    jmp     icn_103_α
    ; CALL writes  id=107
icn_107_α:
    jmp     icn_84_α
icn_107_β:
    jmp     icn_84_α
icon_102_seq_0:
    add     rsp, 8
    jmp     icn_105_α
icn_102_α:
    jmp     icn_107_α
icn_102_β:
    jmp     icn_84_α
    ; GT  id=108
    ; INT 0  id=109
icn_109_α:
    push    0
    jmp     icon_108_check
icn_109_β:
    jmp     icon_108_lb
    ; VAR s2  id=113
icn_113_α:
    mov     rax, [rbp-16]
    push    rax
    jmp     icon_112_cbo_cmp
icn_113_β:
    jmp     icon_112_cbo_lb
    ; VAR sg  id=114
icn_114_α:
    mov     rax, [rel icn_gvar_sg]
    push    rax
    jmp     icon_112_cbo_ls
icn_114_β:
    jmp     icon_101_else
icon_112_cbo_lb:
    jmp     icn_114_β
icn_112_α:
    jmp     icn_114_α
icn_112_β:
    jmp     icn_113_β
icon_112_cbo_ls:
    pop     rax
    mov     [rel icn_cbo112_lptr], rax
    jmp     icn_113_α
icon_112_cbo_cmp:
    pop     rax
    mov     [rel icn_cbo112_rptr], rax
    mov     rdi, [rel icn_cbo112_lptr]
    mov     rsi, [rel icn_cbo112_rptr]
    call    icn_cset_diff
    push    rax
    jmp     icon_111_store
icn_111_α:
    jmp     icn_112_α
icn_111_β:
    jmp     icn_112_β
icon_111_store:
    pop     rax
    mov     [rel icn_gvar_s], rax
    jmp     icon_110_size_relay
icn_110_α:
    jmp     icn_111_α
icn_110_β:
    jmp     icn_111_β
icon_110_size_relay:
    pop     rdi
    call    icn_strlen
    push    rax
    jmp     icon_108_lstore
icon_108_lb:
    jmp     icn_110_β
icn_108_α:
    jmp     icn_110_α
icn_108_β:
    jmp     icn_109_β
icon_108_lstore:
    pop     rax
    mov     [rbp-40], rax
    jmp     icn_109_α
icon_108_check:
    pop     rcx
    mov     rax, [rbp-40]
    cmp     rax, rcx
    jle      icn_109_β
    push    rcx
    jmp     icon_101_then
icon_101_then:
    add     rsp, 8
    jmp     icn_102_α
icon_101_else:
    jmp     icn_84_α
icn_101_α:
    jmp     icn_108_α
icn_101_β:
    jmp     icn_108_β
    ; VAR &null  id=118
icn_118_α:
    mov     rax, [rel icn_gvar_&null]
    push    rax
    jmp     icon_117_store
icn_118_β:
    jmp     icn_101_α
icn_117_α:
    jmp     icn_118_α
icn_117_β:
    jmp     icn_118_β
icon_117_store:
    pop     rax
    mov     [rel icn_gvar_ok], rax
    jmp     icn_101_α
    ; EVERY  id=119
    ; CALL writes  id=120
icn_120_α:
    jmp     icn_101_α
icn_120_β:
    jmp     icn_101_α
icon_119_genb:
    jmp     icn_120_β
icn_119_α:
    jmp     icn_120_α
icn_119_β:
    jmp     icn_101_α
icon_116_seq_1:
    add     rsp, 8
    jmp     icn_117_α
    ; CALL writes  id=121
icn_121_α:
    jmp     icn_101_α
icn_121_β:
    jmp     icn_101_α
icon_116_seq_0:
    add     rsp, 8
    jmp     icn_119_α
icn_116_α:
    jmp     icn_121_α
icn_116_β:
    jmp     icn_101_α
    ; GT  id=122
    ; INT 0  id=123
icn_123_α:
    push    0
    jmp     icon_122_check
icn_123_β:
    jmp     icon_122_lb
    ; VAR sg  id=127
icn_127_α:
    mov     rax, [rel icn_gvar_sg]
    push    rax
    jmp     icon_126_cbo_cmp
icn_127_β:
    jmp     icon_126_cbo_lb
    ; VAR s1  id=128
icn_128_α:
    mov     rax, [rbp-8]
    push    rax
    jmp     icon_126_cbo_ls
icn_128_β:
    jmp     icon_115_else
icon_126_cbo_lb:
    jmp     icn_128_β
icn_126_α:
    jmp     icn_128_α
icn_126_β:
    jmp     icn_127_β
icon_126_cbo_ls:
    pop     rax
    mov     [rel icn_cbo126_lptr], rax
    jmp     icn_127_α
icon_126_cbo_cmp:
    pop     rax
    mov     [rel icn_cbo126_rptr], rax
    mov     rdi, [rel icn_cbo126_lptr]
    mov     rsi, [rel icn_cbo126_rptr]
    call    icn_cset_diff
    push    rax
    jmp     icon_125_store
icn_125_α:
    jmp     icn_126_α
icn_125_β:
    jmp     icn_126_β
icon_125_store:
    pop     rax
    mov     [rel icn_gvar_s], rax
    jmp     icon_124_size_relay
icn_124_α:
    jmp     icn_125_α
icn_124_β:
    jmp     icn_125_β
icon_124_size_relay:
    pop     rdi
    call    icn_strlen
    push    rax
    jmp     icon_122_lstore
icon_122_lb:
    jmp     icn_124_β
icn_122_α:
    jmp     icn_124_α
icn_122_β:
    jmp     icn_123_β
icon_122_lstore:
    pop     rax
    mov     [rbp-48], rax
    jmp     icn_123_α
icon_122_check:
    pop     rcx
    mov     rax, [rbp-48]
    cmp     rax, rcx
    jle      icn_123_β
    push    rcx
    jmp     icon_115_then
icon_115_then:
    add     rsp, 8
    jmp     icn_116_α
icon_115_else:
    jmp     icn_101_α
icn_115_α:
    jmp     icn_122_α
icn_115_β:
    jmp     icn_122_β
icn_130_α:
    lea     rdi, [rel icn_str_2]
    jmp     icon_129_store
icn_130_β:
    jmp     icn_115_α
icn_129_α:
    jmp     icn_130_α
icn_129_β:
    jmp     icn_130_β
icon_129_store:
    ; str assign: rdi already has pointer
    mov     [rel icn_gvar_ok], rdi
    jmp     icn_115_α
    ; CALL writes  id=132
icn_132_α:
    jmp     icn_129_α
icn_132_β:
    jmp     icn_129_α
    ; VAR verbose  id=134
icn_134_α:
    mov     rax, [rel icn_gvar_verbose]
    push    rax
    jmp     icon_131_then
icn_134_β:
    jmp     icon_131_else
icn_133_α:
    jmp     icn_134_α
icn_133_β:
    jmp     icn_134_β
icon_131_then:
    add     rsp, 8
    jmp     icn_132_α
icon_131_else:
    jmp     icn_129_α
icn_131_α:
    jmp     icn_133_α
icn_131_β:
    jmp     icn_133_β
    ; CALL set  id=136
icn_136_α:
    jmp     icn_131_α
icn_136_β:
    jmp     icn_131_α
icn_135_α:
    jmp     icn_136_α
icn_135_β:
    jmp     icn_136_β
icon_135_store:
    pop     rax
    mov     [rel icn_gvar_sg], rax
    jmp     icn_131_α
icn_u_check:
    push    rbp
    mov     rbp, rsp
    sub     rsp, 64
    call    icn_pop
    mov     [rbp-24], rax
    call    icn_pop
    mov     [rbp-16], rax
    call    icn_pop
    mov     [rbp-8], rax
    jmp     icn_135_α
icn_u_check_ret:
    add     rsp, 64
    pop     rbp
    ret
icn_u_check_done:
    mov     byte [rel icn_failed], 1
    add     rsp, 64
    pop     rbp
    ret

; === procedure stale ===
icn_137_α:
    mov     qword [rel icn_retval], 0
    mov     byte [rel icn_failed], 0
    jmp     icn_u_stale_ret
icn_137_β:
    jmp     icn_u_stale_ret
    ; CALL write  id=138
icn_138_α:
    call    icn_write_str
    jmp     icn_137_α
icn_138_β:
    jmp     icn_137_α
    ; EVERY  id=139
    ; CALL delete  id=141
icn_141_α:
    jmp     icon_139_genb
icn_141_β:
    jmp     icon_139_genb
    ; CALL write  id=143
icn_144_α:
    lea     rdi, [rel icn_str_3]
    jmp     icon_143_call
icn_144_β:
    jmp     icon_139_genb
icn_143_α:
    jmp     icn_144_α
icn_143_β:
    jmp     icn_144_β
icon_143_call:
    call    icn_write_str
    jmp     icon_140_seq_0
    ; VAR i  id=147
icn_147_α:
    mov     rax, [rel icn_gvar_i]
    push    rax
    jmp     icon_146_sub_gi
icn_147_β:
    jmp     icon_145_efail
    ; VAR T  id=148
icn_148_α:
    mov     rax, [rel icn_gvar_T]
    push    rax
    jmp     icon_146_sub_go
icn_148_β:
    jmp     icon_145_efail
icn_146_α:
    jmp     icn_148_α
icn_146_β:
    jmp     icn_147_β
icon_146_sub_gi:
    pop     rax
    mov     [rbp-8], rax
    jmp     icn_148_α
icon_146_sub_go:
    pop     rdi
    mov     rsi, [rbp-8]
    dec     rsi
    call    icn_str_subscript
    push    rax
    jmp     icon_145_eok
icn_145_α:
    jmp     icn_146_α
icn_145_β:
    jmp     icon_142_else
icon_145_eok:
    add     rsp, 8
    jmp     icon_142_else
icon_145_efail:
    push    0
    jmp     icon_142_then
icon_142_then:
    add     rsp, 8
    jmp     icn_143_α
icon_142_else:
    jmp     icon_139_genb
icn_142_α:
    jmp     icn_145_α
icn_142_β:
    jmp     icn_145_β
icon_140_seq_0:
    add     rsp, 8
    jmp     icn_141_α
icn_140_α:
    jmp     icn_142_α
icn_140_β:
    jmp     icon_139_genb
    ; CALL key  id=150
icn_150_α:
    jmp     icn_138_α
icn_150_β:
    jmp     icn_138_α
icn_149_α:
    jmp     icn_150_α
icn_149_β:
    jmp     icn_150_β
icon_149_store:
    pop     rax
    mov     [rel icn_gvar_i], rax
    jmp     icon_139_body
icon_139_body:
    jmp     icn_140_α
icon_139_genb:
    jmp     icn_149_β
icn_139_α:
    jmp     icn_149_α
icn_139_β:
    jmp     icn_138_α
    ; CALL write  id=151
icn_152_α:
    lea     rdi, [rel icn_str_4]
    jmp     icon_151_call
icn_152_β:
    jmp     icn_139_α
icn_151_α:
    jmp     icn_152_α
icn_151_β:
    jmp     icn_152_β
icon_151_call:
    call    icn_write_str
    jmp     icn_139_α
    ; EVERY  id=153
    ; CALL delete  id=155
icn_155_α:
    jmp     icon_153_genb
icn_155_β:
    jmp     icon_153_genb
    ; CALL write  id=157
icn_158_α:
    lea     rdi, [rel icn_str_5]
    jmp     icon_157_call
icn_158_β:
    jmp     icon_153_genb
icn_157_α:
    jmp     icn_158_α
icn_157_β:
    jmp     icn_158_β
icon_157_call:
    call    icn_write_str
    jmp     icon_154_seq_0
    ; VAR i  id=161
icn_161_α:
    mov     rax, [rel icn_gvar_i]
    push    rax
    jmp     icon_160_sub_gi
icn_161_β:
    jmp     icon_159_efail
    ; VAR T  id=162
icn_162_α:
    mov     rax, [rel icn_gvar_T]
    push    rax
    jmp     icon_160_sub_go
icn_162_β:
    jmp     icon_159_efail
icn_160_α:
    jmp     icn_162_α
icn_160_β:
    jmp     icn_161_β
icon_160_sub_gi:
    pop     rax
    mov     [rbp-16], rax
    jmp     icn_162_α
icon_160_sub_go:
    pop     rdi
    mov     rsi, [rbp-16]
    dec     rsi
    call    icn_str_subscript
    push    rax
    jmp     icon_159_eok
icn_159_α:
    jmp     icn_160_α
icn_159_β:
    jmp     icon_156_else
icon_159_eok:
    add     rsp, 8
    jmp     icon_156_else
icon_159_efail:
    push    0
    jmp     icon_156_then
icon_156_then:
    add     rsp, 8
    jmp     icn_157_α
icon_156_else:
    jmp     icon_153_genb
icn_156_α:
    jmp     icn_159_α
icn_156_β:
    jmp     icn_159_β
icon_154_seq_0:
    add     rsp, 8
    jmp     icn_155_α
icn_154_α:
    jmp     icn_156_α
icn_154_β:
    jmp     icon_153_genb
    ; VAR T  id=165
icn_165_α:
    mov     rax, [rel icn_gvar_T]
    push    rax
    jmp     icon_164_bang_as
icn_165_β:
    jmp     icn_151_α
icon_164_bang_as:
    pop     rax
    mov     [rel icon_164_bang_str], rax
    mov     qword [rel icon_164_bang_pos], 0
icon_164_bang_chk:
    mov     rdi, [rel icon_164_bang_str]
    call    icn_strlen
    cmp     [rel icon_164_bang_pos], rax
    jge     icn_151_α
    mov     rdi, [rel icon_164_bang_str]
    mov     rsi, [rel icon_164_bang_pos]
    call    icn_bang_char_at
    push    rax
    inc     qword [rel icon_164_bang_pos]
    jmp     icon_163_store
icn_164_α:
    jmp     icn_165_α
icn_164_β:
    jmp     icon_164_bang_chk
icn_163_α:
    jmp     icn_164_α
icn_163_β:
    jmp     icn_164_β
icon_163_store:
    pop     rax
    mov     [rel icn_gvar_i], rax
    jmp     icon_153_body
icon_153_body:
    jmp     icn_154_α
icon_153_genb:
    jmp     icn_163_β
icn_153_α:
    jmp     icn_163_α
icn_153_β:
    jmp     icn_151_α
    ; CALL write  id=166
icn_167_α:
    lea     rdi, [rel icn_str_6]
    jmp     icon_166_call
icn_167_β:
    jmp     icn_153_α
icn_166_α:
    jmp     icn_167_α
icn_166_β:
    jmp     icn_167_β
icon_166_call:
    call    icn_write_str
    jmp     icn_153_α
    ; EVERY  id=168
    ; CALL delete  id=170
icn_170_α:
    jmp     icon_168_genb
icn_170_β:
    jmp     icon_168_genb
    ; CALL write  id=172
icn_173_α:
    lea     rdi, [rel icn_str_7]
    jmp     icon_172_call
icn_173_β:
    jmp     icon_168_genb
icn_172_α:
    jmp     icn_173_α
icn_172_β:
    jmp     icn_173_β
icon_172_call:
    call    icn_write_str
    jmp     icon_169_seq_0
    ; CALL member  id=175
icn_175_α:
    jmp     icon_174_efail
icn_175_β:
    jmp     icon_174_efail
icn_174_α:
    jmp     icn_175_α
icn_174_β:
    jmp     icon_171_else
icon_174_eok:
    add     rsp, 8
    jmp     icon_171_else
icon_174_efail:
    push    0
    jmp     icon_171_then
icon_171_then:
    add     rsp, 8
    jmp     icn_172_α
icon_171_else:
    jmp     icon_168_genb
icn_171_α:
    jmp     icn_174_α
icn_171_β:
    jmp     icn_174_β
icon_169_seq_0:
    add     rsp, 8
    jmp     icn_170_α
icn_169_α:
    jmp     icn_171_α
icn_169_β:
    jmp     icon_168_genb
    ; VAR S  id=178
icn_178_α:
    mov     rax, [rel icn_gvar_S]
    push    rax
    jmp     icon_177_bang_as
icn_178_β:
    jmp     icn_166_α
icon_177_bang_as:
    pop     rax
    mov     [rel icon_177_bang_str], rax
    mov     qword [rel icon_177_bang_pos], 0
icon_177_bang_chk:
    mov     rdi, [rel icon_177_bang_str]
    call    icn_strlen
    cmp     [rel icon_177_bang_pos], rax
    jge     icn_166_α
    mov     rdi, [rel icon_177_bang_str]
    mov     rsi, [rel icon_177_bang_pos]
    call    icn_bang_char_at
    push    rax
    inc     qword [rel icon_177_bang_pos]
    jmp     icon_176_store
icn_177_α:
    jmp     icn_178_α
icn_177_β:
    jmp     icon_177_bang_chk
icn_176_α:
    jmp     icn_177_α
icn_176_β:
    jmp     icn_177_β
icon_176_store:
    pop     rax
    mov     [rel icn_gvar_i], rax
    jmp     icon_168_body
icon_168_body:
    jmp     icn_169_α
icon_168_genb:
    jmp     icn_176_β
icn_168_α:
    jmp     icn_176_α
icn_168_β:
    jmp     icn_166_α
    ; CALL write  id=179
icn_180_α:
    lea     rdi, [rel icn_str_8]
    jmp     icon_179_call
icn_180_β:
    jmp     icn_168_α
icn_179_α:
    jmp     icn_180_α
icn_179_β:
    jmp     icn_180_β
icon_179_call:
    call    icn_write_str
    jmp     icn_168_α
    ; EVERY  id=181
    ; CALL insert  id=183
icn_183_α:
    jmp     icon_181_genb
icn_183_β:
    jmp     icon_181_genb
    ; VAR i  id=185
icn_185_α:
    mov     rax, [rel icn_gvar_i]
    push    rax
    jmp     icon_184_store
icn_185_β:
    jmp     icon_181_genb
icn_184_α:
    jmp     icn_185_α
icn_184_β:
    jmp     icn_185_β
icon_184_store:
    pop     rax
    jmp     icon_182_seq_0
icon_182_seq_0:
    add     rsp, 8
    jmp     icn_183_α
icn_182_α:
    jmp     icn_184_α
icn_182_β:
    jmp     icon_181_genb
    ; TO  id=187
    ; VAR N  id=188
icn_188_α:
    mov     rax, [rel icn_gvar_N]
    push    rax
    jmp     icon_187_init
icn_188_β:
    jmp     icon_187_e1b
    ; INT 1  id=189
icn_189_α:
    push    1
    jmp     icn_188_α
icn_189_β:
    jmp     icn_179_α
icon_187_e1b:
    mov     qword [rel icon_187_e2seen], 0
    jmp     icn_189_β
icon_187_e2b:
    jmp     icn_188_β
icn_187_α:
    mov     qword [rel icon_187_e2seen], 0
    jmp     icn_189_α
icn_187_β:
    inc     qword [rel icn_187_I]
    jmp     icn_187_code
icon_187_init:
    pop     rax
    mov     [rel icon_187_bound], rax
    cmp     qword [rel icon_187_e2seen], 0
    jne     icon_187_init_e2adv
    pop     rax
    mov     [rel icon_187_e1cur], rax
    mov     [rel icn_187_I], rax
    mov     qword [rel icon_187_e2seen], 1
    jmp     icn_187_code
icon_187_init_e2adv:
    mov     rax, [rel icon_187_e1cur]
    mov     [rel icn_187_I], rax
    jmp     icn_187_code
icn_187_code:
    mov     rax, [rel icn_187_I]
    cmp     rax, [rel icon_187_bound]
    jg      icon_187_e2b
    push    rax
    jmp     icon_186_store
icn_186_α:
    jmp     icn_187_α
icn_186_β:
    jmp     icn_187_β
icon_186_store:
    pop     rax
    mov     [rel icn_gvar_i], rax
    jmp     icon_181_body
icon_181_body:
    jmp     icn_182_α
icon_181_genb:
    jmp     icn_186_β
icn_181_α:
    jmp     icn_186_α
icn_181_β:
    jmp     icn_179_α
    ; CALL write  id=190
icn_190_α:
    call    icn_write_str
    jmp     icn_181_α
icn_190_β:
    jmp     icn_181_α
    ; CALL set  id=192
icn_192_α:
    jmp     icn_190_α
icn_192_β:
    jmp     icn_190_α
icn_191_α:
    jmp     icn_192_α
icn_191_β:
    jmp     icn_192_β
icon_191_store:
    pop     rax
    mov     [rel icn_gvar_S], rax
    jmp     icn_190_α
    ; CALL table  id=194
icn_194_α:
    jmp     icn_191_α
icn_194_β:
    jmp     icn_191_α
icn_193_α:
    jmp     icn_194_α
icn_193_β:
    jmp     icn_194_β
icon_193_store:
    pop     rax
    mov     [rel icn_gvar_T], rax
    jmp     icn_191_α
    ; INT 100  id=196
icn_196_α:
    push    100
    jmp     icon_195_store
icn_196_β:
    jmp     icn_193_α
icn_195_α:
    jmp     icn_196_α
icn_195_β:
    jmp     icn_196_β
icon_195_store:
    pop     rax
    mov     [rel icn_gvar_N], rax
    jmp     icn_193_α
icn_u_stale:
    push    rbp
    mov     rbp, rsp
    sub     rsp, 32
    jmp     icn_195_α
icn_u_stale_ret:
    add     rsp, 32
    pop     rbp
    ret
icn_u_stale_done:
    mov     byte [rel icn_failed], 1
    add     rsp, 32
    pop     rbp
    ret
