; Auto-generated by icon_emit.c — Tiny-ICON Byrd Box x64
bits 64
default rel

section .rodata
icn_str_0:  db  102, 97, 105, 108, 0
icn_str_1:  db  102, 97, 105, 108, 0
icn_str_2:  db  102, 97, 105, 108, 0
icn_str_3:  db  102, 97, 105, 108, 0
icn_str_4:  db  102, 97, 105, 108, 0
icn_str_5:  db  102, 97, 105, 108, 0
icn_str_6:  db  102, 97, 105, 108, 0
icn_str_7:  db  102, 97, 105, 108, 0
icn_str_8:  db  102, 97, 105, 108, 0
icn_str_9:  db  102, 97, 105, 108, 0
icn_str_10:  db  102, 97, 105, 108, 0
icn_str_11:  db  102, 97, 105, 108, 0
icn_str_12:  db  102, 97, 105, 108, 0

section .bss
    icn_retval: resq 1
    icn_gvar_&errortext: resq 1
    icn_gvar_&errornumber: resq 1
    icn_gvar_&error: resq 1
    icn_failed: resb 1
    icn_suspended: resb 1
    icn_suspend_resume: resq 1
    icn_suspend_rbp: resq 1

section .text
    global _start
    extern icn_write_int
    extern icn_write_str
    extern icn_push
    extern icn_pop
    extern icn_str_concat
    extern icn_str_eq
    extern icn_any
    extern icn_many
    extern icn_upto
    extern icn_str_find
    extern icn_match
    extern icn_tab
    extern icn_move
    extern icn_subject
    extern icn_pos
    extern icn_str_cmp
    extern icn_strlen
    extern icn_pow
    extern icn_str_subscript
    extern icn_str_section
    extern icn_bang_char_at
    extern icn_match_pat
    extern icn_cset_complement
    extern icn_cset_union
    extern icn_cset_diff
    extern icn_cset_inter

_start:
    call    icn_main
    mov     rax, 60
    xor     rdi, rdi
    syscall


; === procedure main ===
    ; CALL write  id=0
icn_2_α:
    lea     rdi, [rel icn_str_0]
    jmp     icon_0_call
icn_2_β:
    jmp     icn_main_done
    ; CALL image  id=3
icn_3_α:
    jmp     icn_2_α
icn_3_β:
    jmp     icn_2_α
icn_1_α:
    jmp     icn_3_α
icn_1_β:
    jmp     icn_3_β
icn_0_α:
    jmp     icn_1_α
icn_0_β:
    jmp     icn_1_β
icon_0_call:
    pop     rdi
    call    icn_write_int
    jmp     icn_main_done
    ; CALL write  id=4
icn_6_α:
    lea     rdi, [rel icn_str_1]
    jmp     icon_4_call
icn_6_β:
    jmp     icn_0_α
    ; VAR &errortext  id=7
icn_7_α:
    mov     rax, [rel icn_gvar_&errortext]
    push    rax
    jmp     icon_4_call
icn_7_β:
    jmp     icn_6_α
icn_5_α:
    jmp     icn_7_α
icn_5_β:
    jmp     icn_7_β
icn_4_α:
    jmp     icn_5_α
icn_4_β:
    jmp     icn_5_β
icon_4_call:
    pop     rdi
    call    icn_write_int
    jmp     icn_0_α
    ; CALL write  id=8
icn_10_α:
    lea     rdi, [rel icn_str_2]
    jmp     icon_8_call
icn_10_β:
    jmp     icn_4_α
    ; VAR &errornumber  id=11
icn_11_α:
    mov     rax, [rel icn_gvar_&errornumber]
    push    rax
    jmp     icon_8_call
icn_11_β:
    jmp     icn_10_α
icn_9_α:
    jmp     icn_11_α
icn_9_β:
    jmp     icn_11_β
icn_8_α:
    jmp     icn_9_α
icn_8_β:
    jmp     icn_9_β
icon_8_call:
    pop     rdi
    call    icn_write_int
    jmp     icn_4_α
    ; CALL write  id=12
    ; VAR &error  id=13
icn_13_α:
    mov     rax, [rel icn_gvar_&error]
    push    rax
    jmp     icon_12_call
icn_13_β:
    jmp     icn_8_α
icn_12_α:
    jmp     icn_13_α
icn_12_β:
    jmp     icn_13_β
icon_12_call:
    pop     rdi
    call    icn_write_int
    jmp     icn_8_α
    ; CALL errorclear  id=14
icn_14_α:
    jmp     icn_12_α
icn_14_β:
    jmp     icn_12_α
    ; CALL write  id=15
icn_17_α:
    lea     rdi, [rel icn_str_3]
    jmp     icon_15_call
icn_17_β:
    jmp     icn_14_α
    ; CALL image  id=18
icn_18_α:
    jmp     icn_17_α
icn_18_β:
    jmp     icn_17_α
icn_16_α:
    jmp     icn_18_α
icn_16_β:
    jmp     icn_18_β
icn_15_α:
    jmp     icn_16_α
icn_15_β:
    jmp     icn_16_β
icon_15_call:
    pop     rdi
    call    icn_write_int
    jmp     icn_14_α
    ; CALL write  id=19
icn_21_α:
    lea     rdi, [rel icn_str_4]
    jmp     icon_19_call
icn_21_β:
    jmp     icn_15_α
    ; VAR &errortext  id=22
icn_22_α:
    mov     rax, [rel icn_gvar_&errortext]
    push    rax
    jmp     icon_19_call
icn_22_β:
    jmp     icn_21_α
icn_20_α:
    jmp     icn_22_α
icn_20_β:
    jmp     icn_22_β
icn_19_α:
    jmp     icn_20_α
icn_19_β:
    jmp     icn_20_β
icon_19_call:
    pop     rdi
    call    icn_write_int
    jmp     icn_15_α
    ; CALL write  id=23
icn_25_α:
    lea     rdi, [rel icn_str_5]
    jmp     icon_23_call
icn_25_β:
    jmp     icn_19_α
    ; VAR &errornumber  id=26
icn_26_α:
    mov     rax, [rel icn_gvar_&errornumber]
    push    rax
    jmp     icon_23_call
icn_26_β:
    jmp     icn_25_α
icn_24_α:
    jmp     icn_26_α
icn_24_β:
    jmp     icn_26_β
icn_23_α:
    jmp     icn_24_α
icn_23_β:
    jmp     icn_24_β
icon_23_call:
    pop     rdi
    call    icn_write_int
    jmp     icn_19_α
    ; CALL write  id=27
    ; VAR &error  id=28
icn_28_α:
    mov     rax, [rel icn_gvar_&error]
    push    rax
    jmp     icon_27_call
icn_28_β:
    jmp     icn_23_α
icn_27_α:
    jmp     icn_28_α
icn_27_β:
    jmp     icn_28_β
icon_27_call:
    pop     rdi
    call    icn_write_int
    jmp     icn_23_α
    ; CALL write  id=29
icn_31_α:
    lea     rdi, [rel icn_str_6]
    jmp     icon_29_call
icn_31_β:
    jmp     icn_27_α
    ; CALL image  id=32
icn_32_α:
    jmp     icn_31_α
icn_32_β:
    jmp     icn_31_α
icn_30_α:
    jmp     icn_32_α
icn_30_β:
    jmp     icn_32_β
icn_29_α:
    jmp     icn_30_α
icn_29_β:
    jmp     icn_30_β
icon_29_call:
    pop     rdi
    call    icn_write_int
    jmp     icn_27_α
    ; CALL write  id=33
icn_35_α:
    lea     rdi, [rel icn_str_7]
    jmp     icon_33_call
icn_35_β:
    jmp     icn_29_α
    ; VAR &errortext  id=36
icn_36_α:
    mov     rax, [rel icn_gvar_&errortext]
    push    rax
    jmp     icon_33_call
icn_36_β:
    jmp     icn_35_α
icn_34_α:
    jmp     icn_36_α
icn_34_β:
    jmp     icn_36_β
icn_33_α:
    jmp     icn_34_α
icn_33_β:
    jmp     icn_34_β
icon_33_call:
    pop     rdi
    call    icn_write_int
    jmp     icn_29_α
    ; CALL write  id=37
icn_39_α:
    lea     rdi, [rel icn_str_8]
    jmp     icon_37_call
icn_39_β:
    jmp     icn_33_α
    ; VAR &errornumber  id=40
icn_40_α:
    mov     rax, [rel icn_gvar_&errornumber]
    push    rax
    jmp     icon_37_call
icn_40_β:
    jmp     icn_39_α
icn_38_α:
    jmp     icn_40_α
icn_38_β:
    jmp     icn_40_β
icn_37_α:
    jmp     icn_38_α
icn_37_β:
    jmp     icn_38_β
icon_37_call:
    pop     rdi
    call    icn_write_int
    jmp     icn_33_α
    ; CALL write  id=41
    ; VAR &error  id=42
icn_42_α:
    mov     rax, [rel icn_gvar_&error]
    push    rax
    jmp     icon_41_call
icn_42_β:
    jmp     icn_37_α
icn_41_α:
    jmp     icn_42_α
icn_41_β:
    jmp     icn_42_β
icon_41_call:
    pop     rdi
    call    icn_write_int
    jmp     icn_37_α
    ; CALL write  id=43
icn_45_α:
    lea     rdi, [rel icn_str_9]
    jmp     icon_43_call
icn_45_β:
    jmp     icn_41_α
    ; CALL &null  id=46
icn_46_α:
    jmp     icn_45_α
icn_46_β:
    jmp     icn_45_α
icn_44_α:
    jmp     icn_46_α
icn_44_β:
    jmp     icn_46_β
icn_43_α:
    jmp     icn_44_α
icn_43_β:
    jmp     icn_44_β
icon_43_call:
    pop     rdi
    call    icn_write_int
    jmp     icn_41_α
    ; CALL write  id=47
    ; VAR &error  id=48
icn_48_α:
    mov     rax, [rel icn_gvar_&error]
    push    rax
    jmp     icon_47_call
icn_48_β:
    jmp     icn_43_α
icn_47_α:
    jmp     icn_48_α
icn_47_β:
    jmp     icn_48_β
icon_47_call:
    pop     rdi
    call    icn_write_int
    jmp     icn_43_α
    ; INT 1  id=50
icn_50_α:
    push    1
    jmp     icon_49_store
icn_50_β:
    jmp     icn_47_α
icn_49_α:
    jmp     icn_50_α
icn_49_β:
    jmp     icn_50_β
icon_49_store:
    pop     rax
    mov     [rel icn_gvar_&error], rax
    jmp     icn_47_α
    ; CALL write  id=51
icn_53_α:
    lea     rdi, [rel icn_str_10]
    jmp     icon_51_call
icn_53_β:
    jmp     icn_49_α
    ; CALL image  id=54
icn_54_α:
    jmp     icn_53_α
icn_54_β:
    jmp     icn_53_α
icn_52_α:
    jmp     icn_54_α
icn_52_β:
    jmp     icn_54_β
icn_51_α:
    jmp     icn_52_α
icn_51_β:
    jmp     icn_52_β
icon_51_call:
    pop     rdi
    call    icn_write_int
    jmp     icn_49_α
    ; CALL write  id=55
icn_57_α:
    lea     rdi, [rel icn_str_11]
    jmp     icon_55_call
icn_57_β:
    jmp     icn_51_α
    ; VAR &errortext  id=58
icn_58_α:
    mov     rax, [rel icn_gvar_&errortext]
    push    rax
    jmp     icon_55_call
icn_58_β:
    jmp     icn_57_α
icn_56_α:
    jmp     icn_58_α
icn_56_β:
    jmp     icn_58_β
icn_55_α:
    jmp     icn_56_α
icn_55_β:
    jmp     icn_56_β
icon_55_call:
    pop     rdi
    call    icn_write_int
    jmp     icn_51_α
    ; CALL write  id=59
icn_61_α:
    lea     rdi, [rel icn_str_12]
    jmp     icon_59_call
icn_61_β:
    jmp     icn_55_α
    ; VAR &errornumber  id=62
icn_62_α:
    mov     rax, [rel icn_gvar_&errornumber]
    push    rax
    jmp     icon_59_call
icn_62_β:
    jmp     icn_61_α
icn_60_α:
    jmp     icn_62_α
icn_60_β:
    jmp     icn_62_β
icn_59_α:
    jmp     icn_60_α
icn_59_β:
    jmp     icn_60_β
icon_59_call:
    pop     rdi
    call    icn_write_int
    jmp     icn_55_α
    ; CALL write  id=63
    ; VAR &error  id=64
icn_64_α:
    mov     rax, [rel icn_gvar_&error]
    push    rax
    jmp     icon_63_call
icn_64_β:
    jmp     icn_59_α
icn_63_α:
    jmp     icn_64_α
icn_63_β:
    jmp     icn_64_β
icon_63_call:
    pop     rdi
    call    icn_write_int
    jmp     icn_59_α
icn_main:
    push    rbp
    mov     rbp, rsp
    jmp     icn_63_α
icn_main_done:
    mov     byte [rel icn_failed], 1
    pop     rbp
    ret
