; Auto-generated by icon_emit.c — Tiny-ICON Byrd Box x64
bits 64
default rel

section .bss
    icn_retval: resq 1
    icn_failed: resb 1
    icn_suspended: resb 1
    icn_suspend_resume: resq 1
    icn_suspend_rbp: resq 1

section .text
    global _start
    extern icn_write_int
    extern icn_write_str
    extern icn_push
    extern icn_pop
    extern icn_str_concat
    extern icn_str_eq
    extern icn_any
    extern icn_many
    extern icn_upto
    extern icn_str_find
    extern icn_match
    extern icn_tab
    extern icn_move
    extern icn_subject
    extern icn_pos
    extern icn_str_cmp
    extern icn_strlen
    extern icn_pow
    extern icn_str_subscript
    extern icn_str_section
    extern icn_bang_char_at
    extern icn_match_pat

_start:
    call    icn_main
    mov     rax, 60
    xor     rdi, rdi
    syscall


; === procedure positive ===
    ; VAR n  id=2
icon_2_α:
    mov     rax, [rbp-8]
    push    rax
    jmp     icon_1_ret_store
icon_2_β:
    jmp     icon_1_ret_store
icon_1_α:
    jmp     icon_2_α
icon_1_β:
    jmp     icn_positive_ret
icon_1_ret_store:
    pop     rax
    mov     [rel icn_retval], rax
    mov     byte [rel icn_failed], 0
    jmp     icn_positive_ret
    ; GT  id=3
    ; INT 0  id=4
icon_4_α:
    push    0
    jmp     icon_3_check
icon_4_β:
    jmp     icon_3_lb
    ; VAR n  id=5
icon_5_α:
    mov     rax, [rbp-8]
    push    rax
    jmp     icon_3_lstore
icon_5_β:
    jmp     icon_0_else
icon_3_lb:
    jmp     icon_5_β
icon_3_α:
    jmp     icon_5_α
icon_3_β:
    jmp     icon_4_β
icon_3_lstore:
    pop     rax
    mov     [rbp-16], rax
    jmp     icon_4_α
icon_3_check:
    pop     rcx
    mov     rax, [rbp-16]
    cmp     rax, rcx
    jle      icon_4_β
    push    rcx
    jmp     icon_0_then
icon_0_then:
    add     rsp, 8
    jmp     icon_1_α
icon_0_else:
    jmp     icn_positive_done
icon_0_α:
    jmp     icon_3_α
icon_0_β:
    jmp     icon_3_β
icn_positive:
    push    rbp
    mov     rbp, rsp
    sub     rsp, 32
    call    icn_pop
    mov     [rbp-8], rax
    jmp     icon_0_α
icn_positive_ret:
    add     rsp, 32
    pop     rbp
    ret
icn_positive_done:
    mov     byte [rel icn_failed], 1
    add     rsp, 32
    pop     rbp
    ret

; === procedure main ===
    ; CALL write  id=7
    ; INT 2  id=8
icon_8_α:
    push    2
    jmp     icon_7_call
icon_8_β:
    jmp     icn_main_done
icon_7_α:
    jmp     icon_8_α
icon_7_β:
    jmp     icon_8_β
icon_7_call:
    pop     rdi
    call    icn_write_int
    jmp     icn_main_done
    ; CALL write  id=9
    ; INT 3  id=10
icon_10_α:
    push    3
    jmp     icon_9_call
icon_10_β:
    jmp     icn_main_done
icon_9_α:
    jmp     icon_10_α
icon_9_β:
    jmp     icon_10_β
icon_9_call:
    pop     rdi
    call    icn_write_int
    jmp     icn_main_done
    ; CALL positive  id=11
    ; INT 0  id=12
icon_12_α:
    push    0
    jmp     icon_11_push0
icon_12_β:
    jmp     icon_6_else
icon_11_push0:
    pop     rdi
    call    icn_push
    jmp     icon_11_docall
icon_11_α:
    jmp     icon_12_α
icon_11_β:
    jmp     icon_6_else
icon_11_docall:
    call    icn_positive
    movzx   rax, byte [rel icn_failed]
    test    rax, rax
    jnz     icon_6_else
    mov     rax, [rel icn_retval]
    push    rax
    jmp     icon_6_then
icon_6_then:
    add     rsp, 8
    jmp     icon_7_α
icon_6_else:
    jmp     icon_9_α
icon_6_α:
    jmp     icon_11_α
icon_6_β:
    jmp     icon_11_β
    ; CALL write  id=14
    ; INT 1  id=15
icon_15_α:
    push    1
    jmp     icon_14_call
icon_15_β:
    jmp     icon_6_α
icon_14_α:
    jmp     icon_15_α
icon_14_β:
    jmp     icon_15_β
icon_14_call:
    pop     rdi
    call    icn_write_int
    jmp     icon_6_α
    ; CALL positive  id=16
    ; INT 5  id=17
icon_17_α:
    push    5
    jmp     icon_16_push0
icon_17_β:
    jmp     icon_13_else
icon_16_push0:
    pop     rdi
    call    icn_push
    jmp     icon_16_docall
icon_16_α:
    jmp     icon_17_α
icon_16_β:
    jmp     icon_13_else
icon_16_docall:
    call    icn_positive
    movzx   rax, byte [rel icn_failed]
    test    rax, rax
    jnz     icon_13_else
    mov     rax, [rel icn_retval]
    push    rax
    jmp     icon_13_then
icon_13_then:
    add     rsp, 8
    jmp     icon_14_α
icon_13_else:
    jmp     icon_6_α
icon_13_α:
    jmp     icon_16_α
icon_13_β:
    jmp     icon_16_β
icn_main:
    push    rbp
    mov     rbp, rsp
    jmp     icon_13_α
icn_main_done:
    mov     byte [rel icn_failed], 1
    pop     rbp
    ret
