; Auto-generated by icon_emit.c — Tiny-ICON Byrd Box x64
bits 64
default rel

section .rodata
icn_str_0:  db  104, 101, 108, 108, 111, 0

section .bss
    icn_retval: resq 1
    icn_gvar_greeting: resq 1
    icn_failed: resb 1
    icn_suspended: resb 1
    icn_suspend_resume: resq 1
    icn_suspend_rbp: resq 1

section .text
    global _start
    extern icn_write_int
    extern icn_write_str
    extern icn_push
    extern icn_pop
    extern icn_str_concat
    extern icn_str_eq
    extern icn_any
    extern icn_many
    extern icn_upto
    extern icn_str_find
    extern icn_match
    extern icn_tab
    extern icn_move
    extern icn_subject
    extern icn_pos
    extern icn_str_cmp
    extern icn_strlen
    extern icn_pow
    extern icn_str_subscript
    extern icn_str_section
    extern icn_bang_char_at
    extern icn_match_pat
    extern icn_cset_complement
    extern icn_cset_union
    extern icn_cset_diff
    extern icn_cset_inter

_start:
    call    icn_main
    mov     rax, 60
    xor     rdi, rdi
    syscall


; === procedure setup ===
icn_1_α:
    lea     rdi, [rel icn_str_0]
    jmp     icon_0_store
icn_1_β:
    jmp     icn_u_setup_done
icn_0_α:
    jmp     icn_1_α
icn_0_β:
    jmp     icn_1_β
icon_0_store:
    ; str assign: rdi already has pointer
    mov     [rel icn_gvar_greeting], rdi
    jmp     icn_u_setup_done
icn_u_setup:
    push    rbp
    mov     rbp, rsp
    jmp     icn_0_α
icn_u_setup_ret:
    pop     rbp
    ret
icn_u_setup_done:
    mov     byte [rel icn_failed], 1
    pop     rbp
    ret

; === procedure main ===
    ; CALL write  id=2
    ; VAR greeting  id=3
icn_3_α:
    mov     rax, [rel icn_gvar_greeting]
    push    rax
    jmp     icon_2_call
icn_3_β:
    jmp     icn_main_done
icn_2_α:
    jmp     icn_3_α
icn_2_β:
    jmp     icn_3_β
icon_2_call:
    pop     rdi
    call    icn_write_int
    jmp     icn_main_done
    ; CALL setup  id=4
icn_4_α:
    jmp     icon_4_docall
icn_4_β:
    jmp     icn_2_α
icon_4_docall:
    call    icn_u_setup
    movzx   rax, byte [rel icn_failed]
    test    rax, rax
    jnz     icn_2_α
    mov     rax, [rel icn_retval]
    push    rax
    jmp     icn_2_α
icn_main:
    push    rbp
    mov     rbp, rsp
    jmp     icn_4_α
icn_main_done:
    mov     byte [rel icn_failed], 1
    pop     rbp
    ret
