; Auto-generated by icon_emit.c — Tiny-ICON Byrd Box x64
bits 64
default rel

section .bss
    icn_retval: resq 1
    icn_4_I: resq 1
    icon_4_bound: resq 1
    icon_4_e1cur: resq 1
    icon_4_e2seen: resq 1
    icn_7_I: resq 1
    icon_7_bound: resq 1
    icon_7_e1cur: resq 1
    icon_7_e2seen: resq 1
    icn_failed: resb 1
    icn_suspended: resb 1
    icn_suspend_resume: resq 1
    icn_suspend_rbp: resq 1

section .text
    global _start
    extern icn_write_int
    extern icn_write_str
    extern icn_push
    extern icn_pop
    extern icn_str_concat
    extern icn_str_eq
    extern icn_any
    extern icn_many
    extern icn_upto
    extern icn_str_find
    extern icn_match
    extern icn_tab
    extern icn_move
    extern icn_subject
    extern icn_pos
    extern icn_str_cmp
    extern icn_strlen
    extern icn_pow
    extern icn_str_subscript
    extern icn_str_section
    extern icn_bang_char_at
    extern icn_match_pat

_start:
    call    icn_main
    mov     rax, 60
    xor     rdi, rdi
    syscall


; === procedure main ===
    ; EVERY  id=0
    ; CALL write  id=1
    ; LT  id=2
    ; MUL  id=3
    ; TO  id=4
    ; INT 2  id=5
icn_5_α:
    push    2
    jmp     icon_4_init
icn_5_β:
    jmp     icon_4_e1b
    ; INT 1  id=6
icn_6_α:
    push    1
    jmp     icn_5_α
icn_6_β:
    jmp     icon_3_lb
icon_4_e1b:
    mov     qword [rel icon_4_e2seen], 0
    jmp     icn_6_β
icon_4_e2b:
    jmp     icn_5_β
icn_4_α:
    mov     qword [rel icon_4_e2seen], 0
    jmp     icn_6_α
icn_4_β:
    inc     qword [rel icn_4_I]
    jmp     icn_4_code
icon_4_init:
    pop     rax
    mov     [rel icon_4_bound], rax
    cmp     qword [rel icon_4_e2seen], 0
    jne     icon_4_init_e2adv
    pop     rax
    mov     [rel icon_4_e1cur], rax
    mov     [rel icn_4_I], rax
    mov     qword [rel icon_4_e2seen], 1
    jmp     icn_4_code
icon_4_init_e2adv:
    mov     rax, [rel icon_4_e1cur]
    mov     [rel icn_4_I], rax
    jmp     icn_4_code
icn_4_code:
    mov     rax, [rel icn_4_I]
    cmp     rax, [rel icon_4_bound]
    jg      icon_4_e2b
    push    rax
    jmp     icon_3_compute
    ; TO  id=7
    ; INT 3  id=8
icn_8_α:
    push    3
    jmp     icon_7_init
icn_8_β:
    jmp     icon_7_e1b
    ; INT 1  id=9
icn_9_α:
    push    1
    jmp     icn_8_α
icn_9_β:
    jmp     icon_2_lb
icon_7_e1b:
    mov     qword [rel icon_7_e2seen], 0
    jmp     icn_9_β
icon_7_e2b:
    jmp     icn_8_β
icn_7_α:
    mov     qword [rel icon_7_e2seen], 0
    jmp     icn_9_α
icn_7_β:
    inc     qword [rel icn_7_I]
    jmp     icn_7_code
icon_7_init:
    pop     rax
    mov     [rel icon_7_bound], rax
    cmp     qword [rel icon_7_e2seen], 0
    jne     icon_7_init_e2adv
    pop     rax
    mov     [rel icon_7_e1cur], rax
    mov     [rel icn_7_I], rax
    mov     qword [rel icon_7_e2seen], 1
    jmp     icn_7_code
icon_7_init_e2adv:
    mov     rax, [rel icon_7_e1cur]
    mov     [rel icn_7_I], rax
    jmp     icn_7_code
icn_7_code:
    mov     rax, [rel icn_7_I]
    cmp     rax, [rel icon_7_bound]
    jg      icon_7_e2b
    push    rax
    jmp     icon_3_lstore
icon_3_lb:
    jmp     icn_7_β
icn_3_α:
    mov     qword [rbp-24], 0
    jmp     icn_7_α
icn_3_β:
    jmp     icn_4_β
icon_3_lstore:
    pop     rax
    mov     [rbp-16], rax
    cmp     qword [rbp-24], 0
    je      icn_4_α
    jmp     icn_4_β
icon_3_compute:
    pop     rax
    mov     rcx, [rbp-16]
    imul    rcx, rax
    push    rcx
    jmp     icon_2_check
    ; INT 3  id=10
icn_10_α:
    push    3
    jmp     icon_2_lstore
icn_10_β:
    jmp     icn_main_done
icon_2_lb:
    jmp     icn_10_β
icn_2_α:
    jmp     icn_10_α
icn_2_β:
    jmp     icn_3_β
icon_2_lstore:
    pop     rax
    mov     [rbp-8], rax
    jmp     icn_3_α
icon_2_check:
    pop     rcx
    mov     rax, [rbp-8]
    cmp     rax, rcx
    jge      icn_3_β
    push    rcx
    jmp     icon_1_call
icn_1_α:
    jmp     icn_2_α
icn_1_β:
    jmp     icn_2_β
icon_1_call:
    pop     rdi
    call    icn_write_int
    jmp     icon_0_genb
icon_0_genb:
    jmp     icn_1_β
icn_0_α:
    jmp     icn_1_α
icn_0_β:
    jmp     icn_main_done
icn_main:
    push    rbp
    mov     rbp, rsp
    sub     rsp, 32
    jmp     icn_0_α
icn_main_done:
    mov     byte [rel icn_failed], 1
    add     rsp, 32
    pop     rbp
    ret
