; Auto-generated by icon_emit.c — Tiny-ICON Byrd Box x64
bits 64
default rel

section .rodata
icn_str_0:  db  100, 111, 110, 101, 0
icn_str_1:  db  110, 111, 112, 101, 0
icn_str_2:  db  100, 101, 102, 0
icn_str_3:  db  97, 98, 99, 0
icn_str_4:  db  101, 113, 117, 97, 108, 0
icn_str_5:  db  97, 98, 99, 0
icn_str_6:  db  97, 98, 99, 0

section .bss
    icn_retval: resq 1
    icn_sq5_lptr: resq 1
    icn_sq5_rptr: resq 1
    icn_sq11_lptr: resq 1
    icn_sq11_rptr: resq 1
    icn_failed: resb 1
    icn_suspended: resb 1
    icn_suspend_resume: resq 1
    icn_suspend_rbp: resq 1

section .text
    global _start
    extern icn_write_int
    extern icn_write_str
    extern icn_push
    extern icn_pop
    extern icn_str_concat
    extern icn_str_eq
    extern icn_any
    extern icn_many
    extern icn_upto
    extern icn_str_find
    extern icn_match
    extern icn_tab
    extern icn_move
    extern icn_subject
    extern icn_pos
    extern icn_str_cmp
    extern icn_strlen
    extern icn_pow
    extern icn_str_subscript
    extern icn_str_section
    extern icn_bang_char_at
    extern icn_match_pat
    extern icn_cset_complement
    extern icn_cset_union
    extern icn_cset_diff
    extern icn_cset_inter

_start:
    call    icn_main
    mov     rax, 60
    xor     rdi, rdi
    syscall


; === procedure main ===
    ; CALL write  id=0
icn_1_α:
    lea     rdi, [rel icn_str_0]
    jmp     icon_0_call
icn_1_β:
    jmp     icn_main_done
icn_0_α:
    jmp     icn_1_α
icn_0_β:
    jmp     icn_1_β
icon_0_call:
    call    icn_write_str
    jmp     icn_main_done
    ; CALL write  id=3
icn_4_α:
    lea     rdi, [rel icn_str_1]
    jmp     icon_3_call
icn_4_β:
    jmp     icn_0_α
icn_3_α:
    jmp     icn_4_α
icn_3_β:
    jmp     icn_4_β
icon_3_call:
    call    icn_write_str
    jmp     icn_0_α
    ; SEQ  id=5
icn_6_α:
    lea     rdi, [rel icn_str_2]
    jmp     icon_5_rrelay
icn_6_β:
    jmp     icon_5_lb
icn_7_α:
    lea     rdi, [rel icn_str_3]
    jmp     icon_5_lrelay
icn_7_β:
    jmp     icon_2_else
icon_5_lrelay:
    mov     [rel icn_sq5_lptr], rdi
    jmp     icon_5_lstore
icon_5_rrelay:
    mov     [rel icn_sq5_rptr], rdi
    jmp     icon_5_check
icon_5_lb:
    jmp     icn_7_β
icn_5_α:
    jmp     icn_7_α
icn_5_β:
    jmp     icn_6_β
icon_5_lstore:
    jmp     icn_6_α
icon_5_check:
    mov     rdi, [rel icn_sq5_lptr]
    mov     rsi, [rel icn_sq5_rptr]
    call    icn_str_eq
    test    rax, rax
    jz      icn_6_β
    push    0
    jmp     icon_2_then
icon_2_then:
    add     rsp, 8
    jmp     icn_3_α
icon_2_else:
    jmp     icn_0_α
icn_2_α:
    jmp     icn_5_α
icn_2_β:
    jmp     icn_5_β
    ; CALL write  id=9
icn_10_α:
    lea     rdi, [rel icn_str_4]
    jmp     icon_9_call
icn_10_β:
    jmp     icn_2_α
icn_9_α:
    jmp     icn_10_α
icn_9_β:
    jmp     icn_10_β
icon_9_call:
    call    icn_write_str
    jmp     icn_2_α
    ; SEQ  id=11
icn_12_α:
    lea     rdi, [rel icn_str_5]
    jmp     icon_11_rrelay
icn_12_β:
    jmp     icon_11_lb
icn_13_α:
    lea     rdi, [rel icn_str_6]
    jmp     icon_11_lrelay
icn_13_β:
    jmp     icon_8_else
icon_11_lrelay:
    mov     [rel icn_sq11_lptr], rdi
    jmp     icon_11_lstore
icon_11_rrelay:
    mov     [rel icn_sq11_rptr], rdi
    jmp     icon_11_check
icon_11_lb:
    jmp     icn_13_β
icn_11_α:
    jmp     icn_13_α
icn_11_β:
    jmp     icn_12_β
icon_11_lstore:
    jmp     icn_12_α
icon_11_check:
    mov     rdi, [rel icn_sq11_lptr]
    mov     rsi, [rel icn_sq11_rptr]
    call    icn_str_eq
    test    rax, rax
    jz      icn_12_β
    push    0
    jmp     icon_8_then
icon_8_then:
    add     rsp, 8
    jmp     icn_9_α
icon_8_else:
    jmp     icn_2_α
icn_8_α:
    jmp     icn_11_α
icn_8_β:
    jmp     icn_11_β
icn_main:
    push    rbp
    mov     rbp, rsp
    jmp     icn_8_α
icn_main_done:
    mov     byte [rel icn_failed], 1
    pop     rbp
    ret
