; Auto-generated by icon_emit.c — Tiny-ICON Byrd Box x64
bits 64
default rel

section .rodata
icn_str_0:  db  93, 0
icn_str_1:  db  91, 0
icn_str_2:  db  99, 0
icn_str_3:  db  98, 0
icn_str_4:  db  97, 0

section .bss
    icn_retval: resq 1
    icn_cc1_lptr: resq 1
    icn_cc1_rptr: resq 1
    icn_cc3_lptr: resq 1
    icn_cc3_rptr: resq 1
    icn_failed: resb 1
    icn_suspended: resb 1
    icn_suspend_resume: resq 1
    icn_suspend_rbp: resq 1

section .text
    global _start
    extern icn_write_int
    extern icn_write_str
    extern icn_push
    extern icn_pop
    extern icn_str_concat
    extern icn_str_eq
    extern icn_any
    extern icn_many
    extern icn_upto
    extern icn_str_find
    extern icn_match
    extern icn_tab
    extern icn_move
    extern icn_subject
    extern icn_pos
    extern icn_str_cmp
    extern icn_strlen
    extern icn_pow
    extern icn_str_subscript
    extern icn_str_section
    extern icn_bang_char_at
    extern icn_match_pat
    extern icn_cset_complement
    extern icn_cset_union
    extern icn_cset_diff
    extern icn_cset_inter

_start:
    call    icn_main
    mov     rax, 60
    xor     rdi, rdi
    syscall


; === procedure tag ===
    ; CONCAT  id=1
icn_2_α:
    lea     rdi, [rel icn_str_0]
    jmp     icon_1_rrelay
icn_2_β:
    jmp     icon_1_lb
    ; CONCAT  id=3
    ; VAR s  id=4
icn_4_α:
    mov     rax, [rbp-8]
    push    rax
    jmp     icon_3_rrelay
icn_4_β:
    jmp     icon_3_lb
icn_5_α:
    lea     rdi, [rel icn_str_1]
    jmp     icon_3_lrelay
icn_5_β:
    jmp     icon_0_ret_store
icon_3_lrelay:
    mov     [rel icn_cc3_lptr], rdi
    jmp     icon_3_lstore
icon_3_rrelay:
    pop     rax
    mov     [rel icn_cc3_rptr], rax
    jmp     icon_3_compute
icon_3_lb:
    jmp     icn_5_β
icn_3_α:
    mov     qword [rbp-24], 0
    jmp     icn_5_α
icn_3_β:
    mov     qword [rbp-24], 1
    jmp     icn_5_α
icon_3_lstore:
    cmp     qword [rbp-24], 0
    je      icn_4_α
    jmp     icn_4_β
icon_3_compute:
    mov     rdi, [rel icn_cc3_lptr]
    mov     rsi, [rel icn_cc3_rptr]
    call    icn_str_concat
    push    rax
    jmp     icon_1_lrelay
icon_1_lrelay:
    pop     rax
    mov     [rel icn_cc1_lptr], rax
    jmp     icon_1_lstore
icon_1_rrelay:
    mov     [rel icn_cc1_rptr], rdi
    jmp     icon_1_compute
icon_1_lb:
    jmp     icn_3_β
icn_1_α:
    mov     qword [rbp-16], 0
    jmp     icn_3_α
icn_1_β:
    jmp     icn_2_β
icon_1_lstore:
    cmp     qword [rbp-16], 0
    je      icn_2_α
    jmp     icn_2_β
icon_1_compute:
    mov     rdi, [rel icn_cc1_lptr]
    mov     rsi, [rel icn_cc1_rptr]
    call    icn_str_concat
    push    rax
    jmp     icon_0_ret_store
icn_0_α:
    jmp     icn_1_α
icn_0_β:
    jmp     icn_u_tag_ret
icon_0_ret_store:
    pop     rax
    mov     [rel icn_retval], rax
    mov     byte [rel icn_failed], 0
    jmp     icn_u_tag_ret
icn_u_tag:
    push    rbp
    mov     rbp, rsp
    sub     rsp, 32
    call    icn_pop
    mov     [rbp-8], rax
    jmp     icn_0_α
icn_u_tag_ret:
    add     rsp, 32
    pop     rbp
    ret
icn_u_tag_done:
    mov     byte [rel icn_failed], 1
    add     rsp, 32
    pop     rbp
    ret

; === procedure main ===
    ; EVERY  id=6
    ; CALL write  id=7
    ; CALL tag  id=8
icn_10_α:
    lea     rdi, [rel icn_str_2]
    jmp     icon_8_push0
icn_10_β:
    jmp     icn_main_done
icn_11_α:
    lea     rdi, [rel icn_str_3]
    jmp     icon_8_push0
icn_11_β:
    jmp     icn_10_α
icn_12_α:
    lea     rdi, [rel icn_str_4]
    jmp     icon_8_push0
icn_12_β:
    jmp     icn_11_α
icn_9_α:
    jmp     icn_12_α
icn_9_β:
    jmp     icn_12_β
icon_8_push0:
    pop     rdi
    call    icn_push
    jmp     icon_8_docall
icn_8_α:
    jmp     icn_9_α
icn_8_β:
    jmp     icn_main_done
icon_8_docall:
    call    icn_u_tag
    movzx   rax, byte [rel icn_failed]
    test    rax, rax
    jnz     icn_main_done
    mov     rax, [rel icn_retval]
    push    rax
    jmp     icon_7_call
icn_7_α:
    jmp     icn_8_α
icn_7_β:
    jmp     icn_8_β
icon_7_call:
    pop     rdi
    call    icn_write_int
    jmp     icon_6_genb
icon_6_genb:
    jmp     icn_7_β
icn_6_α:
    jmp     icn_7_α
icn_6_β:
    jmp     icn_main_done
icn_main:
    push    rbp
    mov     rbp, rsp
    jmp     icn_6_α
icn_main_done:
    mov     byte [rel icn_failed], 1
    pop     rbp
    ret
