; Auto-generated by icon_emit.c — Tiny-ICON Byrd Box x64
bits 64
default rel

section .rodata
icn_str_0:  db  115, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_1:  db  115, 32, 124, 124, 58, 61, 32, 34, 88, 34, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_2:  db  115, 32, 58, 61, 32, 34, 120, 34, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_3:  db  115, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_4:  db  115, 32, 124, 124, 58, 61, 32, 34, 120, 120, 34, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_5:  db  115, 32, 58, 61, 32, 34, 120, 34, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_6:  db  115, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_7:  db  115, 32, 124, 124, 58, 61, 32, 34, 120, 34, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_8:  db  115, 32, 58, 61, 32, 34, 120, 34, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_9:  db  115, 32, 58, 61, 32, 34, 97, 98, 99, 100, 34, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_10:  db  32, 45, 45, 45, 45, 62, 32, 0
icn_str_11:  db  115, 32, 61, 61, 58, 61, 32, 34, 88, 34, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_12:  db  115, 32, 58, 61, 32, 34, 120, 34, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_13:  db  115, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_14:  db  115, 32, 61, 61, 58, 61, 32, 34, 120, 120, 34, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_15:  db  115, 32, 58, 61, 32, 34, 120, 34, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_16:  db  115, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_17:  db  115, 32, 61, 61, 58, 61, 32, 34, 120, 34, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_18:  db  115, 32, 58, 61, 32, 34, 120, 34, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_19:  db  115, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_20:  db  115, 32, 124, 124, 58, 61, 32, 34, 97, 98, 99, 34, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_21:  db  115, 32, 58, 61, 32, 34, 120, 34, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_22:  db  115, 91, 48, 45, 58, 54, 93, 32, 58, 61, 32, 34, 117, 34, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_23:  db  115, 91, 54, 93, 32, 58, 61, 32, 34, 116, 34, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_24:  db  123, 115, 91, 50, 93, 32, 58, 61, 58, 32, 115, 91, 51, 93, 59, 115, 125, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_25:  db  123, 115, 91, 49, 43, 58, 50, 93, 32, 58, 61, 32, 34, 121, 34, 59, 115, 125, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_26:  db  123, 115, 91, 49, 93, 32, 58, 61, 32, 34, 97, 98, 99, 34, 59, 115, 125, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_27:  db  123, 115, 91, 45, 49, 58, 48, 93, 32, 58, 61, 32, 34, 34, 59, 115, 125, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_28:  db  123, 115, 91, 49, 58, 50, 93, 32, 58, 61, 32, 34, 120, 120, 34, 59, 115, 125, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_29:  db  115, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_30:  db  115, 32, 61, 61, 58, 61, 32, 34, 97, 98, 99, 34, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_31:  db  115, 32, 58, 61, 32, 34, 120, 34, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_32:  db  115, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_33:  db  34, 120, 34, 32, 62, 62, 32, 34, 120, 34, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_34:  db  34, 120, 120, 34, 32, 62, 62, 61, 32, 34, 120, 34, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_35:  db  34, 120, 34, 32, 62, 62, 61, 32, 34, 120, 120, 34, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_36:  db  34, 120, 34, 32, 62, 62, 61, 32, 34, 120, 34, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_37:  db  34, 120, 120, 34, 32, 60, 60, 61, 32, 34, 120, 120, 120, 34, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_38:  db  34, 120, 120, 120, 34, 32, 60, 60, 61, 32, 34, 120, 120, 34, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_39:  db  34, 120, 120, 34, 32, 60, 60, 61, 32, 34, 120, 120, 34, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_40:  db  34, 88, 34, 32, 60, 60, 32, 34, 120, 34, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_41:  db  34, 120, 34, 32, 60, 60, 32, 34, 88, 34, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_42:  db  34, 120, 34, 32, 60, 60, 32, 34, 120, 34, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_43:  db  123, 115, 91, 49, 58, 48, 93, 32, 58, 61, 58, 32, 115, 91, 48, 58, 49, 93, 59, 115, 125, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_44:  db  101, 118, 101, 114, 121, 32, 105, 32, 58, 61, 32, 49, 32, 116, 111, 32, 57, 32, 100, 111, 32, 119, 114, 105, 116, 101, 40, 114, 101, 112, 108, 40, 34, 50, 34, 44, 105, 41, 32, 43, 32, 49, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_45:  db  101, 118, 101, 114, 121, 32, 105, 32, 58, 61, 32, 49, 32, 116, 111, 32, 57, 32, 100, 111, 32, 119, 114, 105, 116, 101, 40, 105, 110, 116, 101, 103, 101, 114, 40, 114, 101, 112, 108, 40, 34, 50, 34, 44, 105, 41, 41, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_46:  db  34, 88, 34, 32, 126, 61, 61, 32, 34, 120, 34, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_47:  db  34, 120, 34, 32, 126, 61, 61, 32, 34, 88, 34, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_48:  db  34, 120, 34, 32, 126, 61, 61, 32, 34, 120, 34, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_49:  db  34, 88, 34, 32, 61, 61, 32, 34, 120, 34, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_50:  db  34, 120, 34, 32, 61, 61, 32, 34, 88, 34, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_51:  db  34, 120, 34, 32, 61, 61, 32, 34, 120, 34, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_52:  db  34, 88, 34, 32, 62, 62, 32, 34, 120, 34, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_53:  db  34, 120, 34, 32, 62, 62, 32, 34, 88, 34, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_54:  db  51, 32, 126, 61, 61, 61, 32, 42, 34, 97, 98, 99, 34, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_55:  db  50, 32, 126, 61, 61, 61, 32, 43, 50, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_56:  db  99, 49, 32, 42, 42, 32, 99, 50, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_57:  db  99, 49, 32, 45, 45, 32, 99, 50, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_58:  db  99, 49, 32, 43, 43, 32, 99, 50, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_59:  db  99, 50, 32, 58, 61, 32, 39, 97, 101, 117, 111, 105, 39, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_60:  db  99, 49, 32, 58, 61, 32, 39, 97, 98, 99, 100, 101, 39, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_61:  db  101, 118, 101, 114, 121, 32, 105, 32, 58, 61, 32, 49, 32, 116, 111, 32, 51, 48, 32, 100, 111, 32, 119, 114, 105, 116, 101, 40, 40, 114, 101, 112, 108, 40, 34, 48, 34, 44, 105, 41, 32, 124, 124, 32, 34, 50, 34, 41, 32, 43, 32, 49, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_62:  db  101, 118, 101, 114, 121, 32, 105, 32, 58, 61, 32, 49, 32, 116, 111, 32, 51, 48, 32, 100, 111, 32, 119, 114, 105, 116, 101, 40, 105, 110, 116, 101, 103, 101, 114, 40, 114, 101, 112, 108, 40, 34, 48, 34, 44, 105, 41, 32, 124, 124, 32, 34, 50, 34, 41, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_63:  db  109, 97, 110, 121, 40, 38, 108, 99, 97, 115, 101, 44, 34, 116, 104, 105, 115, 32, 105, 115, 32, 97, 32, 84, 101, 115, 116, 34, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_64:  db  117, 112, 116, 111, 40, 39, 53, 54, 100, 38, 39, 44, 38, 108, 99, 97, 115, 101, 44, 49, 53, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_65:  db  117, 112, 116, 111, 40, 39, 53, 54, 100, 38, 39, 44, 38, 117, 99, 97, 115, 101, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_66:  db  117, 112, 116, 111, 40, 39, 53, 54, 100, 38, 39, 44, 38, 108, 99, 97, 115, 101, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_67:  db  101, 118, 101, 114, 121, 32, 119, 114, 105, 116, 101, 40, 109, 97, 116, 99, 104, 40, 34, 97, 98, 99, 34, 44, 34, 120, 97, 98, 99, 97, 98, 99, 97, 98, 99, 97, 98, 99, 34, 44, 49, 32, 116, 111, 32, 49, 48, 44, 49, 32, 116, 111, 32, 49, 48, 41, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_68:  db  109, 97, 116, 99, 104, 40, 34, 97, 98, 99, 34, 44, 34, 120, 97, 98, 99, 97, 98, 99, 97, 98, 99, 97, 98, 99, 34, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_69:  db  109, 97, 116, 99, 104, 40, 34, 97, 98, 99, 34, 44, 34, 97, 98, 99, 97, 98, 99, 97, 98, 99, 97, 98, 99, 34, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_70:  db  101, 118, 101, 114, 121, 32, 119, 114, 105, 116, 101, 40, 97, 110, 121, 40, 39, 97, 101, 105, 111, 117, 39, 44, 38, 108, 99, 97, 115, 101, 44, 49, 32, 116, 111, 32, 49, 53, 44, 49, 48, 32, 116, 111, 32, 50, 48, 41, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_71:  db  97, 110, 121, 40, 39, 97, 101, 105, 111, 117, 39, 44, 38, 117, 99, 97, 115, 101, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_72:  db  97, 110, 121, 40, 39, 97, 101, 105, 111, 117, 39, 44, 38, 108, 99, 97, 115, 101, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_73:  db  39, 97, 98, 99, 39, 32, 126, 61, 61, 61, 32, 40, 39, 97, 98, 99, 39, 32, 43, 43, 32, 39, 39, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_74:  db  98, 97, 108, 40, 44, 44, 44, 34, 40, 41, 43, 40, 41, 34, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_75:  db  98, 97, 108, 40, 39, 43, 39, 44, 39, 40, 91, 39, 44, 39, 93, 41, 39, 44, 34, 40, 91, 50, 42, 120, 41, 43, 51, 93, 43, 40, 53, 42, 121, 93, 34, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_76:  db  98, 97, 108, 40, 39, 43, 39, 44, 39, 91, 39, 44, 39, 91, 39, 44, 34, 91, 91, 50, 42, 120, 91, 43, 51, 91, 43, 91, 53, 42, 121, 91, 34, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_77:  db  101, 118, 101, 114, 121, 32, 119, 114, 105, 116, 101, 40, 98, 97, 108, 40, 39, 43, 39, 44, 39, 40, 39, 44, 39, 41, 39, 44, 34, 40, 40, 50, 42, 120, 41, 43, 51, 41, 43, 40, 53, 42, 121, 41, 34, 44, 49, 32, 116, 111, 32, 49, 48, 41, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_78:  db  98, 97, 108, 40, 39, 43, 39, 44, 39, 40, 39, 44, 39, 41, 39, 44, 34, 40, 40, 50, 42, 120, 41, 43, 51, 41, 43, 40, 53, 42, 121, 41, 34, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_79:  db  98, 97, 108, 40, 39, 45, 39, 44, 39, 40, 39, 44, 39, 41, 39, 44, 34, 45, 51, 53, 34, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_80:  db  101, 118, 101, 114, 121, 32, 119, 114, 105, 116, 101, 40, 102, 105, 110, 100, 40, 34, 97, 97, 34, 44, 34, 120, 120, 97, 97, 97, 97, 97, 97, 34, 44, 52, 44, 55, 41, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_81:  db  101, 118, 101, 114, 121, 32, 119, 114, 105, 116, 101, 40, 102, 105, 110, 100, 40, 34, 97, 97, 34, 44, 34, 120, 120, 97, 97, 97, 97, 97, 97, 34, 41, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_82:  db  102, 105, 110, 100, 40, 34, 97, 97, 34, 44, 34, 120, 120, 97, 97, 97, 97, 97, 97, 34, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_83:  db  109, 97, 110, 121, 40, 38, 108, 99, 97, 115, 101, 44, 34, 116, 104, 105, 115, 32, 105, 115, 32, 97, 32, 84, 101, 115, 116, 34, 44, 53, 44, 57, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_84:  db  109, 97, 110, 121, 40, 38, 108, 99, 97, 115, 101, 44, 34, 116, 104, 105, 115, 32, 105, 115, 32, 97, 32, 84, 101, 115, 116, 34, 44, 53, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_85:  db  98, 97, 108, 40, 38, 99, 115, 101, 116, 44, 44, 44, 34, 40, 41, 43, 40, 41, 34, 41, 32, 45, 45, 45, 45, 62, 32, 0

section .bss
    icn_retval: resq 1
    icn_failed: resb 1
    icn_suspended: resb 1
    icn_suspend_resume: resq 1
    icn_suspend_rbp: resq 1

section .text
    global _start
    extern icn_write_int
    extern icn_write_str
    extern icn_push
    extern icn_pop
    extern icn_str_concat
    extern icn_str_eq
    extern icn_any
    extern icn_many
    extern icn_upto
    extern icn_str_find
    extern icn_match
    extern icn_tab
    extern icn_move
    extern icn_subject
    extern icn_pos
    extern icn_str_cmp
    extern icn_strlen
    extern icn_pow
    extern icn_str_subscript
    extern icn_str_section
    extern icn_bang_char_at
    extern icn_match_pat
    extern icn_cset_complement
    extern icn_cset_union
    extern icn_cset_diff
    extern icn_cset_inter

_start:
    call    icn_main
    mov     rax, 60
    xor     rdi, rdi
    syscall


; === procedure p1 ===
    ; CALL write  id=0
icn_1_α:
    lea     rdi, [rel icn_str_0]
    jmp     icon_0_call
icn_1_β:
    jmp     icn_u_p1_done
icn_0_α:
    jmp     icn_1_α
icn_0_β:
    jmp     icn_1_β
icon_0_call:
    call    icn_write_str
    jmp     icn_u_p1_done
    ; CALL write  id=2
icn_3_α:
    lea     rdi, [rel icn_str_1]
    jmp     icon_2_call
icn_3_β:
    jmp     icn_0_α
icn_2_α:
    jmp     icn_3_α
icn_2_β:
    jmp     icn_3_β
icon_2_call:
    call    icn_write_str
    jmp     icn_0_α
    ; CALL write  id=4
icn_5_α:
    lea     rdi, [rel icn_str_2]
    jmp     icon_4_call
icn_5_β:
    jmp     icn_2_α
icn_4_α:
    jmp     icn_5_α
icn_4_β:
    jmp     icn_5_β
icon_4_call:
    call    icn_write_str
    jmp     icn_2_α
    ; CALL write  id=6
icn_7_α:
    lea     rdi, [rel icn_str_3]
    jmp     icon_6_call
icn_7_β:
    jmp     icn_4_α
icn_6_α:
    jmp     icn_7_α
icn_6_β:
    jmp     icn_7_β
icon_6_call:
    call    icn_write_str
    jmp     icn_4_α
    ; CALL write  id=8
icn_9_α:
    lea     rdi, [rel icn_str_4]
    jmp     icon_8_call
icn_9_β:
    jmp     icn_6_α
icn_8_α:
    jmp     icn_9_α
icn_8_β:
    jmp     icn_9_β
icon_8_call:
    call    icn_write_str
    jmp     icn_6_α
    ; CALL write  id=10
icn_11_α:
    lea     rdi, [rel icn_str_5]
    jmp     icon_10_call
icn_11_β:
    jmp     icn_8_α
icn_10_α:
    jmp     icn_11_α
icn_10_β:
    jmp     icn_11_β
icon_10_call:
    call    icn_write_str
    jmp     icn_8_α
    ; CALL write  id=12
icn_13_α:
    lea     rdi, [rel icn_str_6]
    jmp     icon_12_call
icn_13_β:
    jmp     icn_10_α
icn_12_α:
    jmp     icn_13_α
icn_12_β:
    jmp     icn_13_β
icon_12_call:
    call    icn_write_str
    jmp     icn_10_α
    ; CALL write  id=14
icn_15_α:
    lea     rdi, [rel icn_str_7]
    jmp     icon_14_call
icn_15_β:
    jmp     icn_12_α
icn_14_α:
    jmp     icn_15_α
icn_14_β:
    jmp     icn_15_β
icon_14_call:
    call    icn_write_str
    jmp     icn_12_α
    ; CALL write  id=16
icn_17_α:
    lea     rdi, [rel icn_str_8]
    jmp     icon_16_call
icn_17_β:
    jmp     icn_14_α
icn_16_α:
    jmp     icn_17_α
icn_16_β:
    jmp     icn_17_β
icon_16_call:
    call    icn_write_str
    jmp     icn_14_α
    ; CALL write  id=18
icn_19_α:
    lea     rdi, [rel icn_str_9]
    jmp     icon_18_call
icn_19_β:
    jmp     icn_16_α
icn_18_α:
    jmp     icn_19_α
icn_18_β:
    jmp     icn_19_β
icon_18_call:
    call    icn_write_str
    jmp     icn_16_α
    ; CALL write  id=20
icn_21_α:
    lea     rdi, [rel icn_str_10]
    jmp     icon_20_call
icn_21_β:
    jmp     icn_18_α
icn_20_α:
    jmp     icn_21_α
icn_20_β:
    jmp     icn_21_β
icon_20_call:
    call    icn_write_str
    jmp     icn_18_α
icn_u_p1:
    push    rbp
    mov     rbp, rsp
    jmp     icn_20_α
icn_u_p1_ret:
    pop     rbp
    ret
icn_u_p1_done:
    mov     byte [rel icn_failed], 1
    pop     rbp
    ret

; === procedure p2 ===
    ; CALL write  id=22
icn_23_α:
    lea     rdi, [rel icn_str_11]
    jmp     icon_22_call
icn_23_β:
    jmp     icn_u_p2_done
icn_22_α:
    jmp     icn_23_α
icn_22_β:
    jmp     icn_23_β
icon_22_call:
    call    icn_write_str
    jmp     icn_u_p2_done
    ; CALL write  id=24
icn_25_α:
    lea     rdi, [rel icn_str_12]
    jmp     icon_24_call
icn_25_β:
    jmp     icn_22_α
icn_24_α:
    jmp     icn_25_α
icn_24_β:
    jmp     icn_25_β
icon_24_call:
    call    icn_write_str
    jmp     icn_22_α
    ; CALL write  id=26
icn_27_α:
    lea     rdi, [rel icn_str_13]
    jmp     icon_26_call
icn_27_β:
    jmp     icn_24_α
icn_26_α:
    jmp     icn_27_α
icn_26_β:
    jmp     icn_27_β
icon_26_call:
    call    icn_write_str
    jmp     icn_24_α
    ; CALL write  id=28
icn_29_α:
    lea     rdi, [rel icn_str_14]
    jmp     icon_28_call
icn_29_β:
    jmp     icn_26_α
icn_28_α:
    jmp     icn_29_α
icn_28_β:
    jmp     icn_29_β
icon_28_call:
    call    icn_write_str
    jmp     icn_26_α
    ; CALL write  id=30
icn_31_α:
    lea     rdi, [rel icn_str_15]
    jmp     icon_30_call
icn_31_β:
    jmp     icn_28_α
icn_30_α:
    jmp     icn_31_α
icn_30_β:
    jmp     icn_31_β
icon_30_call:
    call    icn_write_str
    jmp     icn_28_α
    ; CALL write  id=32
icn_33_α:
    lea     rdi, [rel icn_str_16]
    jmp     icon_32_call
icn_33_β:
    jmp     icn_30_α
icn_32_α:
    jmp     icn_33_α
icn_32_β:
    jmp     icn_33_β
icon_32_call:
    call    icn_write_str
    jmp     icn_30_α
    ; CALL write  id=34
icn_35_α:
    lea     rdi, [rel icn_str_17]
    jmp     icon_34_call
icn_35_β:
    jmp     icn_32_α
icn_34_α:
    jmp     icn_35_α
icn_34_β:
    jmp     icn_35_β
icon_34_call:
    call    icn_write_str
    jmp     icn_32_α
    ; CALL write  id=36
icn_37_α:
    lea     rdi, [rel icn_str_18]
    jmp     icon_36_call
icn_37_β:
    jmp     icn_34_α
icn_36_α:
    jmp     icn_37_α
icn_36_β:
    jmp     icn_37_β
icon_36_call:
    call    icn_write_str
    jmp     icn_34_α
    ; CALL write  id=38
icn_39_α:
    lea     rdi, [rel icn_str_19]
    jmp     icon_38_call
icn_39_β:
    jmp     icn_36_α
icn_38_α:
    jmp     icn_39_α
icn_38_β:
    jmp     icn_39_β
icon_38_call:
    call    icn_write_str
    jmp     icn_36_α
    ; CALL write  id=40
icn_41_α:
    lea     rdi, [rel icn_str_20]
    jmp     icon_40_call
icn_41_β:
    jmp     icn_38_α
icn_40_α:
    jmp     icn_41_α
icn_40_β:
    jmp     icn_41_β
icon_40_call:
    call    icn_write_str
    jmp     icn_38_α
    ; CALL write  id=42
icn_43_α:
    lea     rdi, [rel icn_str_21]
    jmp     icon_42_call
icn_43_β:
    jmp     icn_40_α
icn_42_α:
    jmp     icn_43_α
icn_42_β:
    jmp     icn_43_β
icon_42_call:
    call    icn_write_str
    jmp     icn_40_α
icn_u_p2:
    push    rbp
    mov     rbp, rsp
    jmp     icn_42_α
icn_u_p2_ret:
    pop     rbp
    ret
icn_u_p2_done:
    mov     byte [rel icn_failed], 1
    pop     rbp
    ret

; === procedure p3 ===
    ; CALL write  id=44
icn_45_α:
    lea     rdi, [rel icn_str_22]
    jmp     icon_44_call
icn_45_β:
    jmp     icn_u_p3_done
icn_44_α:
    jmp     icn_45_α
icn_44_β:
    jmp     icn_45_β
icon_44_call:
    call    icn_write_str
    jmp     icn_u_p3_done
    ; CALL write  id=46
icn_47_α:
    lea     rdi, [rel icn_str_23]
    jmp     icon_46_call
icn_47_β:
    jmp     icn_44_α
icn_46_α:
    jmp     icn_47_α
icn_46_β:
    jmp     icn_47_β
icon_46_call:
    call    icn_write_str
    jmp     icn_44_α
    ; CALL write  id=48
icn_49_α:
    lea     rdi, [rel icn_str_24]
    jmp     icon_48_call
icn_49_β:
    jmp     icn_46_α
icn_48_α:
    jmp     icn_49_α
icn_48_β:
    jmp     icn_49_β
icon_48_call:
    call    icn_write_str
    jmp     icn_46_α
    ; CALL write  id=50
icn_51_α:
    lea     rdi, [rel icn_str_25]
    jmp     icon_50_call
icn_51_β:
    jmp     icn_48_α
icn_50_α:
    jmp     icn_51_α
icn_50_β:
    jmp     icn_51_β
icon_50_call:
    call    icn_write_str
    jmp     icn_48_α
    ; CALL write  id=52
icn_53_α:
    lea     rdi, [rel icn_str_26]
    jmp     icon_52_call
icn_53_β:
    jmp     icn_50_α
icn_52_α:
    jmp     icn_53_α
icn_52_β:
    jmp     icn_53_β
icon_52_call:
    call    icn_write_str
    jmp     icn_50_α
    ; CALL write  id=54
icn_55_α:
    lea     rdi, [rel icn_str_27]
    jmp     icon_54_call
icn_55_β:
    jmp     icn_52_α
icn_54_α:
    jmp     icn_55_α
icn_54_β:
    jmp     icn_55_β
icon_54_call:
    call    icn_write_str
    jmp     icn_52_α
    ; CALL write  id=56
icn_57_α:
    lea     rdi, [rel icn_str_28]
    jmp     icon_56_call
icn_57_β:
    jmp     icn_54_α
icn_56_α:
    jmp     icn_57_α
icn_56_β:
    jmp     icn_57_β
icon_56_call:
    call    icn_write_str
    jmp     icn_54_α
    ; CALL write  id=58
icn_59_α:
    lea     rdi, [rel icn_str_29]
    jmp     icon_58_call
icn_59_β:
    jmp     icn_56_α
icn_58_α:
    jmp     icn_59_α
icn_58_β:
    jmp     icn_59_β
icon_58_call:
    call    icn_write_str
    jmp     icn_56_α
    ; CALL write  id=60
icn_61_α:
    lea     rdi, [rel icn_str_30]
    jmp     icon_60_call
icn_61_β:
    jmp     icn_58_α
icn_60_α:
    jmp     icn_61_α
icn_60_β:
    jmp     icn_61_β
icon_60_call:
    call    icn_write_str
    jmp     icn_58_α
    ; CALL write  id=62
icn_63_α:
    lea     rdi, [rel icn_str_31]
    jmp     icon_62_call
icn_63_β:
    jmp     icn_60_α
icn_62_α:
    jmp     icn_63_α
icn_62_β:
    jmp     icn_63_β
icon_62_call:
    call    icn_write_str
    jmp     icn_60_α
    ; CALL write  id=64
icn_65_α:
    lea     rdi, [rel icn_str_32]
    jmp     icon_64_call
icn_65_β:
    jmp     icn_62_α
icn_64_α:
    jmp     icn_65_α
icn_64_β:
    jmp     icn_65_β
icon_64_call:
    call    icn_write_str
    jmp     icn_62_α
icn_u_p3:
    push    rbp
    mov     rbp, rsp
    jmp     icn_64_α
icn_u_p3_ret:
    pop     rbp
    ret
icn_u_p3_done:
    mov     byte [rel icn_failed], 1
    pop     rbp
    ret

; === procedure p4 ===
    ; CALL write  id=66
icn_67_α:
    lea     rdi, [rel icn_str_33]
    jmp     icon_66_call
icn_67_β:
    jmp     icn_u_p4_done
icn_66_α:
    jmp     icn_67_α
icn_66_β:
    jmp     icn_67_β
icon_66_call:
    call    icn_write_str
    jmp     icn_u_p4_done
    ; CALL write  id=68
icn_69_α:
    lea     rdi, [rel icn_str_34]
    jmp     icon_68_call
icn_69_β:
    jmp     icn_66_α
icn_68_α:
    jmp     icn_69_α
icn_68_β:
    jmp     icn_69_β
icon_68_call:
    call    icn_write_str
    jmp     icn_66_α
    ; CALL write  id=70
icn_71_α:
    lea     rdi, [rel icn_str_35]
    jmp     icon_70_call
icn_71_β:
    jmp     icn_68_α
icn_70_α:
    jmp     icn_71_α
icn_70_β:
    jmp     icn_71_β
icon_70_call:
    call    icn_write_str
    jmp     icn_68_α
    ; CALL write  id=72
icn_73_α:
    lea     rdi, [rel icn_str_36]
    jmp     icon_72_call
icn_73_β:
    jmp     icn_70_α
icn_72_α:
    jmp     icn_73_α
icn_72_β:
    jmp     icn_73_β
icon_72_call:
    call    icn_write_str
    jmp     icn_70_α
    ; CALL write  id=74
icn_75_α:
    lea     rdi, [rel icn_str_37]
    jmp     icon_74_call
icn_75_β:
    jmp     icn_72_α
icn_74_α:
    jmp     icn_75_α
icn_74_β:
    jmp     icn_75_β
icon_74_call:
    call    icn_write_str
    jmp     icn_72_α
    ; CALL write  id=76
icn_77_α:
    lea     rdi, [rel icn_str_38]
    jmp     icon_76_call
icn_77_β:
    jmp     icn_74_α
icn_76_α:
    jmp     icn_77_α
icn_76_β:
    jmp     icn_77_β
icon_76_call:
    call    icn_write_str
    jmp     icn_74_α
    ; CALL write  id=78
icn_79_α:
    lea     rdi, [rel icn_str_39]
    jmp     icon_78_call
icn_79_β:
    jmp     icn_76_α
icn_78_α:
    jmp     icn_79_α
icn_78_β:
    jmp     icn_79_β
icon_78_call:
    call    icn_write_str
    jmp     icn_76_α
    ; CALL write  id=80
icn_81_α:
    lea     rdi, [rel icn_str_40]
    jmp     icon_80_call
icn_81_β:
    jmp     icn_78_α
icn_80_α:
    jmp     icn_81_α
icn_80_β:
    jmp     icn_81_β
icon_80_call:
    call    icn_write_str
    jmp     icn_78_α
    ; CALL write  id=82
icn_83_α:
    lea     rdi, [rel icn_str_41]
    jmp     icon_82_call
icn_83_β:
    jmp     icn_80_α
icn_82_α:
    jmp     icn_83_α
icn_82_β:
    jmp     icn_83_β
icon_82_call:
    call    icn_write_str
    jmp     icn_80_α
    ; CALL write  id=84
icn_85_α:
    lea     rdi, [rel icn_str_42]
    jmp     icon_84_call
icn_85_β:
    jmp     icn_82_α
icn_84_α:
    jmp     icn_85_α
icn_84_β:
    jmp     icn_85_β
icon_84_call:
    call    icn_write_str
    jmp     icn_82_α
    ; CALL write  id=86
icn_87_α:
    lea     rdi, [rel icn_str_43]
    jmp     icon_86_call
icn_87_β:
    jmp     icn_84_α
icn_86_α:
    jmp     icn_87_α
icn_86_β:
    jmp     icn_87_β
icon_86_call:
    call    icn_write_str
    jmp     icn_84_α
icn_u_p4:
    push    rbp
    mov     rbp, rsp
    jmp     icn_86_α
icn_u_p4_ret:
    pop     rbp
    ret
icn_u_p4_done:
    mov     byte [rel icn_failed], 1
    pop     rbp
    ret

; === procedure p5 ===
    ; CALL write  id=88
icn_89_α:
    lea     rdi, [rel icn_str_44]
    jmp     icon_88_call
icn_89_β:
    jmp     icn_u_p5_done
icn_88_α:
    jmp     icn_89_α
icn_88_β:
    jmp     icn_89_β
icon_88_call:
    call    icn_write_str
    jmp     icn_u_p5_done
    ; CALL write  id=90
icn_91_α:
    lea     rdi, [rel icn_str_45]
    jmp     icon_90_call
icn_91_β:
    jmp     icn_88_α
icn_90_α:
    jmp     icn_91_α
icn_90_β:
    jmp     icn_91_β
icon_90_call:
    call    icn_write_str
    jmp     icn_88_α
    ; CALL write  id=92
icn_93_α:
    lea     rdi, [rel icn_str_46]
    jmp     icon_92_call
icn_93_β:
    jmp     icn_90_α
icn_92_α:
    jmp     icn_93_α
icn_92_β:
    jmp     icn_93_β
icon_92_call:
    call    icn_write_str
    jmp     icn_90_α
    ; CALL write  id=94
icn_95_α:
    lea     rdi, [rel icn_str_47]
    jmp     icon_94_call
icn_95_β:
    jmp     icn_92_α
icn_94_α:
    jmp     icn_95_α
icn_94_β:
    jmp     icn_95_β
icon_94_call:
    call    icn_write_str
    jmp     icn_92_α
    ; CALL write  id=96
icn_97_α:
    lea     rdi, [rel icn_str_48]
    jmp     icon_96_call
icn_97_β:
    jmp     icn_94_α
icn_96_α:
    jmp     icn_97_α
icn_96_β:
    jmp     icn_97_β
icon_96_call:
    call    icn_write_str
    jmp     icn_94_α
    ; CALL write  id=98
icn_99_α:
    lea     rdi, [rel icn_str_49]
    jmp     icon_98_call
icn_99_β:
    jmp     icn_96_α
icn_98_α:
    jmp     icn_99_α
icn_98_β:
    jmp     icn_99_β
icon_98_call:
    call    icn_write_str
    jmp     icn_96_α
    ; CALL write  id=100
icn_101_α:
    lea     rdi, [rel icn_str_50]
    jmp     icon_100_call
icn_101_β:
    jmp     icn_98_α
icn_100_α:
    jmp     icn_101_α
icn_100_β:
    jmp     icn_101_β
icon_100_call:
    call    icn_write_str
    jmp     icn_98_α
    ; CALL write  id=102
icn_103_α:
    lea     rdi, [rel icn_str_51]
    jmp     icon_102_call
icn_103_β:
    jmp     icn_100_α
icn_102_α:
    jmp     icn_103_α
icn_102_β:
    jmp     icn_103_β
icon_102_call:
    call    icn_write_str
    jmp     icn_100_α
    ; CALL write  id=104
icn_105_α:
    lea     rdi, [rel icn_str_52]
    jmp     icon_104_call
icn_105_β:
    jmp     icn_102_α
icn_104_α:
    jmp     icn_105_α
icn_104_β:
    jmp     icn_105_β
icon_104_call:
    call    icn_write_str
    jmp     icn_102_α
    ; CALL write  id=106
icn_107_α:
    lea     rdi, [rel icn_str_53]
    jmp     icon_106_call
icn_107_β:
    jmp     icn_104_α
icn_106_α:
    jmp     icn_107_α
icn_106_β:
    jmp     icn_107_β
icon_106_call:
    call    icn_write_str
    jmp     icn_104_α
icn_u_p5:
    push    rbp
    mov     rbp, rsp
    jmp     icn_106_α
icn_u_p5_ret:
    pop     rbp
    ret
icn_u_p5_done:
    mov     byte [rel icn_failed], 1
    pop     rbp
    ret

; === procedure p6 ===
    ; CALL write  id=108
icn_109_α:
    lea     rdi, [rel icn_str_54]
    jmp     icon_108_call
icn_109_β:
    jmp     icn_u_p6_done
icn_108_α:
    jmp     icn_109_α
icn_108_β:
    jmp     icn_109_β
icon_108_call:
    call    icn_write_str
    jmp     icn_u_p6_done
    ; CALL write  id=110
icn_111_α:
    lea     rdi, [rel icn_str_55]
    jmp     icon_110_call
icn_111_β:
    jmp     icn_108_α
icn_110_α:
    jmp     icn_111_α
icn_110_β:
    jmp     icn_111_β
icon_110_call:
    call    icn_write_str
    jmp     icn_108_α
    ; CALL write  id=112
icn_113_α:
    lea     rdi, [rel icn_str_56]
    jmp     icon_112_call
icn_113_β:
    jmp     icn_110_α
icn_112_α:
    jmp     icn_113_α
icn_112_β:
    jmp     icn_113_β
icon_112_call:
    call    icn_write_str
    jmp     icn_110_α
    ; CALL write  id=114
icn_115_α:
    lea     rdi, [rel icn_str_57]
    jmp     icon_114_call
icn_115_β:
    jmp     icn_112_α
icn_114_α:
    jmp     icn_115_α
icn_114_β:
    jmp     icn_115_β
icon_114_call:
    call    icn_write_str
    jmp     icn_112_α
    ; CALL write  id=116
icn_117_α:
    lea     rdi, [rel icn_str_58]
    jmp     icon_116_call
icn_117_β:
    jmp     icn_114_α
icn_116_α:
    jmp     icn_117_α
icn_116_β:
    jmp     icn_117_β
icon_116_call:
    call    icn_write_str
    jmp     icn_114_α
    ; CALL write  id=118
icn_119_α:
    lea     rdi, [rel icn_str_59]
    jmp     icon_118_call
icn_119_β:
    jmp     icn_116_α
icn_118_α:
    jmp     icn_119_α
icn_118_β:
    jmp     icn_119_β
icon_118_call:
    call    icn_write_str
    jmp     icn_116_α
    ; CALL write  id=120
icn_121_α:
    lea     rdi, [rel icn_str_60]
    jmp     icon_120_call
icn_121_β:
    jmp     icn_118_α
icn_120_α:
    jmp     icn_121_α
icn_120_β:
    jmp     icn_121_β
icon_120_call:
    call    icn_write_str
    jmp     icn_118_α
    ; CALL write  id=122
icn_123_α:
    lea     rdi, [rel icn_str_61]
    jmp     icon_122_call
icn_123_β:
    jmp     icn_120_α
icn_122_α:
    jmp     icn_123_α
icn_122_β:
    jmp     icn_123_β
icon_122_call:
    call    icn_write_str
    jmp     icn_120_α
    ; CALL write  id=124
icn_125_α:
    lea     rdi, [rel icn_str_62]
    jmp     icon_124_call
icn_125_β:
    jmp     icn_122_α
icn_124_α:
    jmp     icn_125_α
icn_124_β:
    jmp     icn_125_β
icon_124_call:
    call    icn_write_str
    jmp     icn_122_α
icn_u_p6:
    push    rbp
    mov     rbp, rsp
    jmp     icn_124_α
icn_u_p6_ret:
    pop     rbp
    ret
icn_u_p6_done:
    mov     byte [rel icn_failed], 1
    pop     rbp
    ret

; === procedure p7 ===
    ; CALL write  id=126
icn_127_α:
    lea     rdi, [rel icn_str_63]
    jmp     icon_126_call
icn_127_β:
    jmp     icn_u_p7_done
icn_126_α:
    jmp     icn_127_α
icn_126_β:
    jmp     icn_127_β
icon_126_call:
    call    icn_write_str
    jmp     icn_u_p7_done
    ; CALL write  id=128
icn_129_α:
    lea     rdi, [rel icn_str_64]
    jmp     icon_128_call
icn_129_β:
    jmp     icn_126_α
icn_128_α:
    jmp     icn_129_α
icn_128_β:
    jmp     icn_129_β
icon_128_call:
    call    icn_write_str
    jmp     icn_126_α
    ; CALL write  id=130
icn_131_α:
    lea     rdi, [rel icn_str_65]
    jmp     icon_130_call
icn_131_β:
    jmp     icn_128_α
icn_130_α:
    jmp     icn_131_α
icn_130_β:
    jmp     icn_131_β
icon_130_call:
    call    icn_write_str
    jmp     icn_128_α
    ; CALL write  id=132
icn_133_α:
    lea     rdi, [rel icn_str_66]
    jmp     icon_132_call
icn_133_β:
    jmp     icn_130_α
icn_132_α:
    jmp     icn_133_α
icn_132_β:
    jmp     icn_133_β
icon_132_call:
    call    icn_write_str
    jmp     icn_130_α
    ; CALL write  id=134
icn_135_α:
    lea     rdi, [rel icn_str_67]
    jmp     icon_134_call
icn_135_β:
    jmp     icn_132_α
icn_134_α:
    jmp     icn_135_α
icn_134_β:
    jmp     icn_135_β
icon_134_call:
    call    icn_write_str
    jmp     icn_132_α
    ; CALL write  id=136
icn_137_α:
    lea     rdi, [rel icn_str_68]
    jmp     icon_136_call
icn_137_β:
    jmp     icn_134_α
icn_136_α:
    jmp     icn_137_α
icn_136_β:
    jmp     icn_137_β
icon_136_call:
    call    icn_write_str
    jmp     icn_134_α
    ; CALL write  id=138
icn_139_α:
    lea     rdi, [rel icn_str_69]
    jmp     icon_138_call
icn_139_β:
    jmp     icn_136_α
icn_138_α:
    jmp     icn_139_α
icn_138_β:
    jmp     icn_139_β
icon_138_call:
    call    icn_write_str
    jmp     icn_136_α
    ; CALL write  id=140
icn_141_α:
    lea     rdi, [rel icn_str_70]
    jmp     icon_140_call
icn_141_β:
    jmp     icn_138_α
icn_140_α:
    jmp     icn_141_α
icn_140_β:
    jmp     icn_141_β
icon_140_call:
    call    icn_write_str
    jmp     icn_138_α
    ; CALL write  id=142
icn_143_α:
    lea     rdi, [rel icn_str_71]
    jmp     icon_142_call
icn_143_β:
    jmp     icn_140_α
icn_142_α:
    jmp     icn_143_α
icn_142_β:
    jmp     icn_143_β
icon_142_call:
    call    icn_write_str
    jmp     icn_140_α
    ; CALL write  id=144
icn_145_α:
    lea     rdi, [rel icn_str_72]
    jmp     icon_144_call
icn_145_β:
    jmp     icn_142_α
icn_144_α:
    jmp     icn_145_α
icn_144_β:
    jmp     icn_145_β
icon_144_call:
    call    icn_write_str
    jmp     icn_142_α
    ; CALL write  id=146
icn_147_α:
    lea     rdi, [rel icn_str_73]
    jmp     icon_146_call
icn_147_β:
    jmp     icn_144_α
icn_146_α:
    jmp     icn_147_α
icn_146_β:
    jmp     icn_147_β
icon_146_call:
    call    icn_write_str
    jmp     icn_144_α
icn_u_p7:
    push    rbp
    mov     rbp, rsp
    jmp     icn_146_α
icn_u_p7_ret:
    pop     rbp
    ret
icn_u_p7_done:
    mov     byte [rel icn_failed], 1
    pop     rbp
    ret

; === procedure p8 ===
    ; CALL write  id=148
icn_149_α:
    lea     rdi, [rel icn_str_74]
    jmp     icon_148_call
icn_149_β:
    jmp     icn_u_p8_done
icn_148_α:
    jmp     icn_149_α
icn_148_β:
    jmp     icn_149_β
icon_148_call:
    call    icn_write_str
    jmp     icn_u_p8_done
    ; CALL write  id=150
icn_151_α:
    lea     rdi, [rel icn_str_75]
    jmp     icon_150_call
icn_151_β:
    jmp     icn_148_α
icn_150_α:
    jmp     icn_151_α
icn_150_β:
    jmp     icn_151_β
icon_150_call:
    call    icn_write_str
    jmp     icn_148_α
    ; CALL write  id=152
icn_153_α:
    lea     rdi, [rel icn_str_76]
    jmp     icon_152_call
icn_153_β:
    jmp     icn_150_α
icn_152_α:
    jmp     icn_153_α
icn_152_β:
    jmp     icn_153_β
icon_152_call:
    call    icn_write_str
    jmp     icn_150_α
    ; CALL write  id=154
icn_155_α:
    lea     rdi, [rel icn_str_77]
    jmp     icon_154_call
icn_155_β:
    jmp     icn_152_α
icn_154_α:
    jmp     icn_155_α
icn_154_β:
    jmp     icn_155_β
icon_154_call:
    call    icn_write_str
    jmp     icn_152_α
    ; CALL write  id=156
icn_157_α:
    lea     rdi, [rel icn_str_78]
    jmp     icon_156_call
icn_157_β:
    jmp     icn_154_α
icn_156_α:
    jmp     icn_157_α
icn_156_β:
    jmp     icn_157_β
icon_156_call:
    call    icn_write_str
    jmp     icn_154_α
    ; CALL write  id=158
icn_159_α:
    lea     rdi, [rel icn_str_79]
    jmp     icon_158_call
icn_159_β:
    jmp     icn_156_α
icn_158_α:
    jmp     icn_159_α
icn_158_β:
    jmp     icn_159_β
icon_158_call:
    call    icn_write_str
    jmp     icn_156_α
    ; CALL write  id=160
icn_161_α:
    lea     rdi, [rel icn_str_80]
    jmp     icon_160_call
icn_161_β:
    jmp     icn_158_α
icn_160_α:
    jmp     icn_161_α
icn_160_β:
    jmp     icn_161_β
icon_160_call:
    call    icn_write_str
    jmp     icn_158_α
    ; CALL write  id=162
icn_163_α:
    lea     rdi, [rel icn_str_81]
    jmp     icon_162_call
icn_163_β:
    jmp     icn_160_α
icn_162_α:
    jmp     icn_163_α
icn_162_β:
    jmp     icn_163_β
icon_162_call:
    call    icn_write_str
    jmp     icn_160_α
    ; CALL write  id=164
icn_165_α:
    lea     rdi, [rel icn_str_82]
    jmp     icon_164_call
icn_165_β:
    jmp     icn_162_α
icn_164_α:
    jmp     icn_165_α
icn_164_β:
    jmp     icn_165_β
icon_164_call:
    call    icn_write_str
    jmp     icn_162_α
    ; CALL write  id=166
icn_167_α:
    lea     rdi, [rel icn_str_83]
    jmp     icon_166_call
icn_167_β:
    jmp     icn_164_α
icn_166_α:
    jmp     icn_167_α
icn_166_β:
    jmp     icn_167_β
icon_166_call:
    call    icn_write_str
    jmp     icn_164_α
    ; CALL write  id=168
icn_169_α:
    lea     rdi, [rel icn_str_84]
    jmp     icon_168_call
icn_169_β:
    jmp     icn_166_α
icn_168_α:
    jmp     icn_169_α
icn_168_β:
    jmp     icn_169_β
icon_168_call:
    call    icn_write_str
    jmp     icn_166_α
icn_u_p8:
    push    rbp
    mov     rbp, rsp
    jmp     icn_168_α
icn_u_p8_ret:
    pop     rbp
    ret
icn_u_p8_done:
    mov     byte [rel icn_failed], 1
    pop     rbp
    ret

; === procedure p9 ===
    ; CALL write  id=170
icn_171_α:
    lea     rdi, [rel icn_str_85]
    jmp     icon_170_call
icn_171_β:
    jmp     icn_u_p9_done
icn_170_α:
    jmp     icn_171_α
icn_170_β:
    jmp     icn_171_β
icon_170_call:
    call    icn_write_str
    jmp     icn_u_p9_done
icn_u_p9:
    push    rbp
    mov     rbp, rsp
    jmp     icn_170_α
icn_u_p9_ret:
    pop     rbp
    ret
icn_u_p9_done:
    mov     byte [rel icn_failed], 1
    pop     rbp
    ret

; === procedure main ===
    ; CALL p9  id=172
icn_172_α:
    jmp     icon_172_docall
icn_172_β:
    jmp     icn_main_done
icon_172_docall:
    call    icn_u_p9
    movzx   rax, byte [rel icn_failed]
    test    rax, rax
    jnz     icn_main_done
    mov     rax, [rel icn_retval]
    push    rax
    jmp     icn_main_done
    ; CALL p8  id=173
icn_173_α:
    jmp     icon_173_docall
icn_173_β:
    jmp     icn_172_α
icon_173_docall:
    call    icn_u_p8
    movzx   rax, byte [rel icn_failed]
    test    rax, rax
    jnz     icn_172_α
    mov     rax, [rel icn_retval]
    push    rax
    jmp     icn_172_α
    ; CALL p7  id=174
icn_174_α:
    jmp     icon_174_docall
icn_174_β:
    jmp     icn_173_α
icon_174_docall:
    call    icn_u_p7
    movzx   rax, byte [rel icn_failed]
    test    rax, rax
    jnz     icn_173_α
    mov     rax, [rel icn_retval]
    push    rax
    jmp     icn_173_α
    ; CALL p6  id=175
icn_175_α:
    jmp     icon_175_docall
icn_175_β:
    jmp     icn_174_α
icon_175_docall:
    call    icn_u_p6
    movzx   rax, byte [rel icn_failed]
    test    rax, rax
    jnz     icn_174_α
    mov     rax, [rel icn_retval]
    push    rax
    jmp     icn_174_α
    ; CALL p5  id=176
icn_176_α:
    jmp     icon_176_docall
icn_176_β:
    jmp     icn_175_α
icon_176_docall:
    call    icn_u_p5
    movzx   rax, byte [rel icn_failed]
    test    rax, rax
    jnz     icn_175_α
    mov     rax, [rel icn_retval]
    push    rax
    jmp     icn_175_α
    ; CALL p4  id=177
icn_177_α:
    jmp     icon_177_docall
icn_177_β:
    jmp     icn_176_α
icon_177_docall:
    call    icn_u_p4
    movzx   rax, byte [rel icn_failed]
    test    rax, rax
    jnz     icn_176_α
    mov     rax, [rel icn_retval]
    push    rax
    jmp     icn_176_α
    ; CALL p3  id=178
icn_178_α:
    jmp     icon_178_docall
icn_178_β:
    jmp     icn_177_α
icon_178_docall:
    call    icn_u_p3
    movzx   rax, byte [rel icn_failed]
    test    rax, rax
    jnz     icn_177_α
    mov     rax, [rel icn_retval]
    push    rax
    jmp     icn_177_α
    ; CALL p2  id=179
icn_179_α:
    jmp     icon_179_docall
icn_179_β:
    jmp     icn_178_α
icon_179_docall:
    call    icn_u_p2
    movzx   rax, byte [rel icn_failed]
    test    rax, rax
    jnz     icn_178_α
    mov     rax, [rel icn_retval]
    push    rax
    jmp     icn_178_α
    ; CALL p1  id=180
icn_180_α:
    jmp     icon_180_docall
icn_180_β:
    jmp     icn_179_α
icon_180_docall:
    call    icn_u_p1
    movzx   rax, byte [rel icn_failed]
    test    rax, rax
    jnz     icn_179_α
    mov     rax, [rel icn_retval]
    push    rax
    jmp     icn_179_α
icn_main:
    push    rbp
    mov     rbp, rsp
    jmp     icn_180_α
icn_main_done:
    mov     byte [rel icn_failed], 1
    pop     rbp
    ret
