; Auto-generated by icon_emit.c — Tiny-ICON Byrd Box x64
bits 64
default rel

section .rodata
icn_str_0:  db  105, 103, 110, 111, 114, 101, 32, 116, 104, 105, 115, 32, 105, 102, 32, 121, 111, 117, 32, 119, 105, 115, 104, 46, 0
icn_str_1:  db  73, 110, 32, 97, 100, 100, 105, 116, 105, 111, 110, 44, 32, 115, 111, 109, 101, 32, 112, 108, 97, 116, 102, 111, 114, 109, 115, 32, 109, 97, 121, 32, 115, 104, 111, 119, 32, 48, 46, 48, 32, 97, 115, 32, 34, 45, 48, 46, 48, 34, 46, 32, 32, 89, 111, 117, 32, 99, 97, 110, 0
icn_str_2:  db  97, 115, 32, 115, 104, 111, 119, 110, 32, 105, 110, 32, 116, 104, 101, 32, 115, 116, 97, 110, 100, 97, 114, 100, 32, 114, 101, 115, 117, 108, 116, 115, 44, 32, 116, 104, 101, 114, 101, 39, 115, 32, 110, 111, 116, 104, 105, 110, 103, 32, 116, 111, 32, 119, 111, 114, 114, 121, 32, 97, 98, 111, 117, 116, 46, 0
icn_str_3:  db  112, 114, 111, 100, 117, 99, 101, 100, 32, 105, 110, 32, 108, 111, 99, 97, 108, 32, 116, 101, 115, 116, 115, 32, 97, 114, 101, 32, 97, 112, 112, 114, 111, 120, 105, 109, 97, 116, 101, 108, 121, 32, 116, 104, 101, 32, 115, 97, 109, 101, 32, 105, 110, 32, 109, 97, 103, 110, 105, 116, 117, 100, 101, 0
icn_str_4:  db  99, 111, 110, 118, 101, 114, 116, 32, 102, 108, 111, 97, 116, 105, 110, 103, 45, 112, 111, 105, 110, 116, 32, 110, 117, 109, 98, 101, 114, 115, 32, 116, 111, 32, 115, 116, 114, 105, 110, 103, 115, 46, 32, 32, 73, 102, 32, 116, 104, 101, 32, 118, 97, 108, 117, 101, 115, 0
icn_str_5:  db  105, 110, 32, 102, 108, 111, 97, 116, 105, 110, 103, 45, 112, 111, 105, 110, 116, 32, 112, 114, 101, 99, 105, 115, 105, 111, 110, 32, 97, 110, 100, 32, 100, 101, 116, 97, 105, 108, 115, 32, 111, 102, 32, 116, 104, 101, 32, 114, 111, 117, 116, 105, 110, 101, 115, 32, 116, 104, 97, 116, 0
icn_str_6:  db  100, 105, 102, 102, 101, 114, 101, 110, 99, 101, 115, 32, 102, 114, 111, 109, 32, 112, 108, 97, 116, 102, 111, 114, 109, 32, 116, 111, 32, 112, 108, 97, 116, 102, 111, 114, 109, 32, 98, 101, 99, 97, 117, 115, 101, 32, 111, 102, 32, 100, 105, 102, 102, 101, 114, 101, 110, 99, 101, 115, 0
icn_str_7:  db  84, 104, 105, 115, 32, 116, 101, 115, 116, 32, 111, 102, 32, 102, 108, 111, 97, 116, 105, 110, 103, 45, 112, 111, 105, 110, 116, 32, 97, 114, 105, 116, 104, 109, 101, 116, 105, 99, 32, 105, 115, 32, 108, 105, 107, 101, 108, 121, 32, 116, 111, 32, 115, 104, 111, 119, 0
icn_str_8:  db  110, 117, 109, 101, 114, 105, 99, 40, 34, 48, 46, 51, 34, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_9:  db  110, 117, 109, 101, 114, 105, 99, 40, 34, 46, 51, 34, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_10:  db  110, 117, 109, 101, 114, 105, 99, 40, 34, 46, 34, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_11:  db  110, 117, 109, 101, 114, 105, 99, 40, 50, 46, 55, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_12:  db  110, 117, 109, 101, 114, 105, 99, 40, 50, 46, 48, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_13:  db  105, 110, 116, 101, 103, 101, 114, 40, 34, 51, 101, 53, 48, 48, 34, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_14:  db  105, 110, 116, 101, 103, 101, 114, 40, 34, 101, 50, 34, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_15:  db  105, 110, 116, 101, 103, 101, 114, 40, 34, 32, 46, 32, 51, 34, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_16:  db  105, 110, 116, 101, 103, 101, 114, 40, 34, 48, 46, 51, 34, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_17:  db  105, 110, 116, 101, 103, 101, 114, 40, 34, 46, 51, 34, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_18:  db  105, 110, 116, 101, 103, 101, 114, 40, 34, 46, 34, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_19:  db  105, 110, 116, 101, 103, 101, 114, 40, 50, 46, 55, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_20:  db  105, 110, 116, 101, 103, 101, 114, 40, 50, 46, 48, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_21:  db  73, 109, 97, 103, 101, 40, 50, 46, 48, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_22:  db  73, 109, 97, 103, 101, 40, 48, 46, 48, 48, 48, 54, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_23:  db  73, 109, 97, 103, 101, 40, 50, 101, 49, 51, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_24:  db  97, 98, 115, 40, 51, 46, 48, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_25:  db  50, 46, 48, 32, 126, 61, 61, 61, 32, 43, 50, 46, 48, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_26:  db  101, 118, 101, 114, 121, 32, 105, 32, 58, 61, 32, 49, 32, 116, 111, 32, 51, 48, 32, 100, 111, 32, 119, 114, 105, 116, 101, 40, 105, 110, 116, 101, 103, 101, 114, 40, 114, 101, 112, 108, 40, 34, 48, 34, 44, 105, 41, 32, 124, 124, 32, 34, 50, 34, 41, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_27:  db  101, 118, 101, 114, 121, 32, 105, 32, 58, 61, 32, 49, 32, 116, 111, 32, 53, 48, 32, 100, 111, 32, 119, 114, 105, 116, 101, 40, 114, 101, 97, 108, 40, 114, 101, 112, 108, 40, 34, 48, 34, 44, 105, 41, 32, 124, 124, 32, 34, 50, 46, 34, 41, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_28:  db  101, 118, 101, 114, 121, 32, 49, 32, 116, 111, 32, 49, 48, 32, 100, 111, 32, 119, 114, 105, 116, 101, 40, 63, 48, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_29:  db  63, 51, 48, 46, 48, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_30:  db  50, 46, 48, 32, 61, 61, 61, 32, 43, 50, 46, 48, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_31:  db  102, 97, 105, 108, 101, 100, 0
icn_str_32:  db  46, 50, 0
icn_str_33:  db  102, 97, 105, 108, 101, 100, 0
icn_str_34:  db  102, 97, 105, 108, 101, 100, 0
icn_str_35:  db  45, 51, 54, 46, 32, 94, 32, 45, 57, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_36:  db  45, 51, 54, 46, 32, 94, 32, 57, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_37:  db  51, 54, 46, 32, 94, 32, 57, 46, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_38:  db  51, 54, 32, 94, 32, 57, 46, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_39:  db  51, 54, 46, 32, 94, 32, 57, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_40:  db  110, 117, 109, 101, 114, 105, 99, 40, 101, 50, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_41:  db  110, 117, 109, 101, 114, 105, 99, 40, 48, 46, 51, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_42:  db  110, 117, 109, 101, 114, 105, 99, 40, 50, 46, 55, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_43:  db  110, 117, 109, 101, 114, 105, 99, 40, 50, 46, 48, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_44:  db  114, 101, 97, 108, 40, 34, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 34, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_45:  db  114, 101, 97, 108, 40, 34, 50, 114, 48, 34, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_46:  db  114, 101, 97, 108, 40, 34, 49, 114, 49, 34, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_47:  db  114, 101, 97, 108, 40, 34, 51, 54, 114, 67, 65, 84, 34, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_48:  db  114, 101, 97, 108, 40, 34, 51, 54, 82, 99, 97, 116, 34, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_49:  db  114, 101, 97, 108, 40, 34, 51, 54, 114, 99, 97, 116, 34, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_50:  db  114, 101, 97, 108, 40, 34, 49, 54, 114, 102, 102, 34, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_51:  db  114, 101, 97, 108, 40, 34, 55, 114, 32, 52, 34, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_52:  db  114, 101, 97, 108, 40, 34, 52, 114, 32, 55, 34, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_53:  db  114, 101, 97, 108, 40, 34, 52, 114, 55, 34, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_54:  db  114, 101, 97, 108, 40, 34, 55, 114, 52, 34, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_55:  db  114, 101, 97, 108, 40, 34, 51, 101, 53, 48, 48, 34, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_56:  db  114, 101, 97, 108, 40, 34, 101, 50, 34, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_57:  db  114, 101, 97, 108, 40, 34, 32, 46, 32, 51, 34, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_58:  db  114, 101, 97, 108, 40, 34, 48, 46, 51, 34, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_59:  db  114, 101, 97, 108, 40, 34, 46, 51, 34, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_60:  db  114, 101, 97, 108, 40, 34, 46, 34, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_61:  db  114, 101, 97, 108, 40, 34, 43, 34, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_62:  db  114, 101, 97, 108, 40, 34, 45, 34, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_63:  db  114, 101, 97, 108, 40, 34, 32, 34, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_64:  db  114, 101, 97, 108, 40, 34, 45, 45, 50, 34, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_65:  db  114, 101, 97, 108, 40, 34, 34, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_66:  db  114, 101, 97, 108, 40, 34, 32, 45, 32, 32, 32, 32, 50, 32, 34, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_67:  db  114, 101, 97, 108, 40, 34, 45, 32, 50, 34, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_68:  db  114, 101, 97, 108, 40, 34, 45, 50, 34, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_69:  db  114, 101, 97, 108, 40, 34, 43, 50, 34, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_70:  db  114, 101, 97, 108, 40, 34, 50, 32, 34, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_71:  db  114, 101, 97, 108, 40, 34, 32, 50, 34, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_72:  db  114, 101, 97, 108, 40, 34, 50, 34, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_73:  db  114, 101, 97, 108, 40, 50, 46, 55, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_74:  db  114, 101, 97, 108, 40, 50, 46, 48, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_75:  db  114, 101, 97, 108, 40, 50, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_76:  db  110, 117, 109, 101, 114, 105, 99, 40, 34, 51, 101, 53, 48, 48, 34, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_77:  db  110, 117, 109, 101, 114, 105, 99, 40, 34, 101, 50, 34, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_78:  db  110, 117, 109, 101, 114, 105, 99, 40, 34, 32, 46, 32, 51, 34, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_79:  db  73, 109, 97, 103, 101, 40, 48, 46, 48, 48, 48, 54, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_80:  db  73, 109, 97, 103, 101, 40, 50, 101, 49, 51, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_81:  db  116, 114, 105, 109, 40, 51, 46, 49, 52, 49, 53, 57, 44, 53, 56, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_82:  db  99, 111, 112, 121, 40, 49, 46, 48, 41, 32, 45, 45, 45, 45, 62, 32, 0
icn_str_83:  db  101, 43, 0
icn_str_84:  db  46, 0
icn_str_85:  db  48, 0
icn_str_86:  db  46, 0
icn_str_87:  db  46, 0
icn_str_88:  db  101, 0
icn_str_89:  db  114, 101, 97, 108, 0

section .bss
    icn_retval: resq 1
    icn_cc73_lptr: resq 1
    icn_cc73_rptr: resq 1
    icn_77_I: resq 1
    icon_77_bound: resq 1
    icon_77_e1cur: resq 1
    icon_77_e2seen: resq 1
    icn_gvar_i: resq 1
    icn_88_I: resq 1
    icon_88_bound: resq 1
    icon_88_e1cur: resq 1
    icon_88_e2seen: resq 1
    icn_99_I: resq 1
    icon_99_bound: resq 1
    icon_99_e1cur: resq 1
    icon_99_e2seen: resq 1
    icn_scan_oldsubj_201: resq 1
    icn_scan_oldpos_201: resq 1
    icn_scan_oldsubj_205: resq 1
    icn_scan_oldpos_205: resq 1
    icn_gvar_head: resq 1
    icn_cc208_lptr: resq 1
    icn_cc208_rptr: resq 1
    icn_gvar_tail: resq 1
    icn_gvar_span: resq 1
    icn_scan_oldsubj_219: resq 1
    icn_scan_oldpos_219: resq 1
    icn_cc222_lptr: resq 1
    icn_cc222_rptr: resq 1
    icn_gvar_exp: resq 1
    icn_cc228_lptr: resq 1
    icn_cc228_rptr: resq 1
    icn_cc230_lptr: resq 1
    icn_cc230_rptr: resq 1
    icn_cc235_lptr: resq 1
    icn_cc235_rptr: resq 1
    icn_cc244_lptr: resq 1
    icn_cc244_rptr: resq 1
    icn_sq250_lptr: resq 1
    icn_sq250_rptr: resq 1
    icn_failed: resb 1
    icn_suspended: resb 1
    icn_suspend_resume: resq 1
    icn_suspend_rbp: resq 1

section .text
    global _start
    extern icn_write_int
    extern icn_write_str
    extern icn_push
    extern icn_pop
    extern icn_str_concat
    extern icn_str_eq
    extern icn_any
    extern icn_many
    extern icn_upto
    extern icn_str_find
    extern icn_match
    extern icn_tab
    extern icn_move
    extern icn_subject
    extern icn_pos
    extern icn_str_cmp
    extern icn_strlen
    extern icn_pow
    extern icn_str_subscript
    extern icn_str_section
    extern icn_bang_char_at
    extern icn_match_pat
    extern icn_cset_complement
    extern icn_cset_union
    extern icn_cset_diff
    extern icn_cset_inter

_start:
    call    icn_main
    mov     rax, 60
    xor     rdi, rdi
    syscall


; === procedure main ===
    ; CALL p3  id=0
icn_0_α:
    jmp     icon_0_docall
icn_0_β:
    jmp     icn_main_done
icon_0_docall:
    call    icn_u_p3
    movzx   rax, byte [rel icn_failed]
    test    rax, rax
    jnz     icn_main_done
    mov     rax, [rel icn_retval]
    push    rax
    jmp     icn_main_done
    ; CALL p2  id=1
icn_1_α:
    jmp     icon_1_docall
icn_1_β:
    jmp     icn_0_α
icon_1_docall:
    call    icn_u_p2
    movzx   rax, byte [rel icn_failed]
    test    rax, rax
    jnz     icn_0_α
    mov     rax, [rel icn_retval]
    push    rax
    jmp     icn_0_α
    ; CALL p1  id=2
icn_2_α:
    jmp     icon_2_docall
icn_2_β:
    jmp     icn_1_α
icon_2_docall:
    call    icn_u_p1
    movzx   rax, byte [rel icn_failed]
    test    rax, rax
    jnz     icn_1_α
    mov     rax, [rel icn_retval]
    push    rax
    jmp     icn_1_α
    ; CALL write  id=3
icn_4_α:
    lea     rdi, [rel icn_str_0]
    jmp     icon_3_call
icn_4_β:
    jmp     icn_2_α
icn_3_α:
    jmp     icn_4_α
icn_3_β:
    jmp     icn_4_β
icon_3_call:
    call    icn_write_str
    jmp     icn_2_α
    ; CALL write  id=5
icn_6_α:
    lea     rdi, [rel icn_str_1]
    jmp     icon_5_call
icn_6_β:
    jmp     icn_3_α
icn_5_α:
    jmp     icn_6_α
icn_5_β:
    jmp     icn_6_β
icon_5_call:
    call    icn_write_str
    jmp     icn_3_α
    ; CALL write  id=7
icn_8_α:
    lea     rdi, [rel icn_str_2]
    jmp     icon_7_call
icn_8_β:
    jmp     icn_5_α
icn_7_α:
    jmp     icn_8_α
icn_7_β:
    jmp     icn_8_β
icon_7_call:
    call    icn_write_str
    jmp     icn_5_α
    ; CALL write  id=9
icn_10_α:
    lea     rdi, [rel icn_str_3]
    jmp     icon_9_call
icn_10_β:
    jmp     icn_7_α
icn_9_α:
    jmp     icn_10_α
icn_9_β:
    jmp     icn_10_β
icon_9_call:
    call    icn_write_str
    jmp     icn_7_α
    ; CALL write  id=11
icn_12_α:
    lea     rdi, [rel icn_str_4]
    jmp     icon_11_call
icn_12_β:
    jmp     icn_9_α
icn_11_α:
    jmp     icn_12_α
icn_11_β:
    jmp     icn_12_β
icon_11_call:
    call    icn_write_str
    jmp     icn_9_α
    ; CALL write  id=13
icn_14_α:
    lea     rdi, [rel icn_str_5]
    jmp     icon_13_call
icn_14_β:
    jmp     icn_11_α
icn_13_α:
    jmp     icn_14_α
icn_13_β:
    jmp     icn_14_β
icon_13_call:
    call    icn_write_str
    jmp     icn_11_α
    ; CALL write  id=15
icn_16_α:
    lea     rdi, [rel icn_str_6]
    jmp     icon_15_call
icn_16_β:
    jmp     icn_13_α
icn_15_α:
    jmp     icn_16_α
icn_15_β:
    jmp     icn_16_β
icon_15_call:
    call    icn_write_str
    jmp     icn_13_α
    ; CALL write  id=17
icn_18_α:
    lea     rdi, [rel icn_str_7]
    jmp     icon_17_call
icn_18_β:
    jmp     icn_15_α
icn_17_α:
    jmp     icn_18_α
icn_17_β:
    jmp     icn_18_β
icon_17_call:
    call    icn_write_str
    jmp     icn_15_α
icn_main:
    push    rbp
    mov     rbp, rsp
    jmp     icn_17_α
icn_main_done:
    mov     byte [rel icn_failed], 1
    pop     rbp
    ret

; === procedure p1 ===
    ; CALL write  id=19
icn_20_α:
    lea     rdi, [rel icn_str_8]
    jmp     icon_19_call
icn_20_β:
    jmp     icn_u_p1_done
icn_19_α:
    jmp     icn_20_α
icn_19_β:
    jmp     icn_20_β
icon_19_call:
    call    icn_write_str
    jmp     icn_u_p1_done
    ; CALL write  id=21
icn_22_α:
    lea     rdi, [rel icn_str_9]
    jmp     icon_21_call
icn_22_β:
    jmp     icn_19_α
icn_21_α:
    jmp     icn_22_α
icn_21_β:
    jmp     icn_22_β
icon_21_call:
    call    icn_write_str
    jmp     icn_19_α
    ; CALL write  id=23
icn_24_α:
    lea     rdi, [rel icn_str_10]
    jmp     icon_23_call
icn_24_β:
    jmp     icn_21_α
icn_23_α:
    jmp     icn_24_α
icn_23_β:
    jmp     icn_24_β
icon_23_call:
    call    icn_write_str
    jmp     icn_21_α
    ; CALL write  id=25
icn_26_α:
    lea     rdi, [rel icn_str_11]
    jmp     icon_25_call
icn_26_β:
    jmp     icn_23_α
icn_25_α:
    jmp     icn_26_α
icn_25_β:
    jmp     icn_26_β
icon_25_call:
    call    icn_write_str
    jmp     icn_23_α
    ; CALL write  id=27
icn_28_α:
    lea     rdi, [rel icn_str_12]
    jmp     icon_27_call
icn_28_β:
    jmp     icn_25_α
icn_27_α:
    jmp     icn_28_α
icn_27_β:
    jmp     icn_28_β
icon_27_call:
    call    icn_write_str
    jmp     icn_25_α
    ; CALL write  id=29
icn_30_α:
    lea     rdi, [rel icn_str_13]
    jmp     icon_29_call
icn_30_β:
    jmp     icn_27_α
icn_29_α:
    jmp     icn_30_α
icn_29_β:
    jmp     icn_30_β
icon_29_call:
    call    icn_write_str
    jmp     icn_27_α
    ; CALL write  id=31
icn_32_α:
    lea     rdi, [rel icn_str_14]
    jmp     icon_31_call
icn_32_β:
    jmp     icn_29_α
icn_31_α:
    jmp     icn_32_α
icn_31_β:
    jmp     icn_32_β
icon_31_call:
    call    icn_write_str
    jmp     icn_29_α
    ; CALL write  id=33
icn_34_α:
    lea     rdi, [rel icn_str_15]
    jmp     icon_33_call
icn_34_β:
    jmp     icn_31_α
icn_33_α:
    jmp     icn_34_α
icn_33_β:
    jmp     icn_34_β
icon_33_call:
    call    icn_write_str
    jmp     icn_31_α
    ; CALL write  id=35
icn_36_α:
    lea     rdi, [rel icn_str_16]
    jmp     icon_35_call
icn_36_β:
    jmp     icn_33_α
icn_35_α:
    jmp     icn_36_α
icn_35_β:
    jmp     icn_36_β
icon_35_call:
    call    icn_write_str
    jmp     icn_33_α
    ; CALL write  id=37
icn_38_α:
    lea     rdi, [rel icn_str_17]
    jmp     icon_37_call
icn_38_β:
    jmp     icn_35_α
icn_37_α:
    jmp     icn_38_α
icn_37_β:
    jmp     icn_38_β
icon_37_call:
    call    icn_write_str
    jmp     icn_35_α
    ; CALL write  id=39
icn_40_α:
    lea     rdi, [rel icn_str_18]
    jmp     icon_39_call
icn_40_β:
    jmp     icn_37_α
icn_39_α:
    jmp     icn_40_α
icn_39_β:
    jmp     icn_40_β
icon_39_call:
    call    icn_write_str
    jmp     icn_37_α
    ; CALL write  id=41
icn_42_α:
    lea     rdi, [rel icn_str_19]
    jmp     icon_41_call
icn_42_β:
    jmp     icn_39_α
icn_41_α:
    jmp     icn_42_α
icn_41_β:
    jmp     icn_42_β
icon_41_call:
    call    icn_write_str
    jmp     icn_39_α
    ; CALL write  id=43
icn_44_α:
    lea     rdi, [rel icn_str_20]
    jmp     icon_43_call
icn_44_β:
    jmp     icn_41_α
icn_43_α:
    jmp     icn_44_α
icn_43_β:
    jmp     icn_44_β
icon_43_call:
    call    icn_write_str
    jmp     icn_41_α
    ; CALL write  id=45
icn_46_α:
    lea     rdi, [rel icn_str_21]
    jmp     icon_45_call
icn_46_β:
    jmp     icn_43_α
icn_45_α:
    jmp     icn_46_α
icn_45_β:
    jmp     icn_46_β
icon_45_call:
    call    icn_write_str
    jmp     icn_43_α
    ; CALL write  id=47
icn_48_α:
    lea     rdi, [rel icn_str_22]
    jmp     icon_47_call
icn_48_β:
    jmp     icn_45_α
icn_47_α:
    jmp     icn_48_α
icn_47_β:
    jmp     icn_48_β
icon_47_call:
    call    icn_write_str
    jmp     icn_45_α
    ; CALL write  id=49
icn_50_α:
    lea     rdi, [rel icn_str_23]
    jmp     icon_49_call
icn_50_β:
    jmp     icn_47_α
icn_49_α:
    jmp     icn_50_α
icn_49_β:
    jmp     icn_50_β
icon_49_call:
    call    icn_write_str
    jmp     icn_47_α
    ; CALL write  id=51
icn_52_α:
    lea     rdi, [rel icn_str_24]
    jmp     icon_51_call
icn_52_β:
    jmp     icn_49_α
icn_51_α:
    jmp     icn_52_α
icn_51_β:
    jmp     icn_52_β
icon_51_call:
    call    icn_write_str
    jmp     icn_49_α
    ; CALL write  id=53
icn_54_α:
    lea     rdi, [rel icn_str_25]
    jmp     icon_53_call
icn_54_β:
    jmp     icn_51_α
icn_53_α:
    jmp     icn_54_α
icn_53_β:
    jmp     icn_54_β
icon_53_call:
    call    icn_write_str
    jmp     icn_51_α
    ; CALL write  id=55
icn_56_α:
    lea     rdi, [rel icn_str_26]
    jmp     icon_55_call
icn_56_β:
    jmp     icn_53_α
icn_55_α:
    jmp     icn_56_α
icn_55_β:
    jmp     icn_56_β
icon_55_call:
    call    icn_write_str
    jmp     icn_53_α
    ; CALL write  id=57
icn_58_α:
    lea     rdi, [rel icn_str_27]
    jmp     icon_57_call
icn_58_β:
    jmp     icn_55_α
icn_57_α:
    jmp     icn_58_α
icn_57_β:
    jmp     icn_58_β
icon_57_call:
    call    icn_write_str
    jmp     icn_55_α
    ; CALL write  id=59
icn_60_α:
    lea     rdi, [rel icn_str_28]
    jmp     icon_59_call
icn_60_β:
    jmp     icn_57_α
icn_59_α:
    jmp     icn_60_α
icn_59_β:
    jmp     icn_60_β
icon_59_call:
    call    icn_write_str
    jmp     icn_57_α
icn_u_p1:
    push    rbp
    mov     rbp, rsp
    jmp     icn_59_α
icn_u_p1_ret:
    pop     rbp
    ret
icn_u_p1_done:
    mov     byte [rel icn_failed], 1
    pop     rbp
    ret

; === procedure p2 ===
    ; CALL write  id=61
icn_62_α:
    lea     rdi, [rel icn_str_29]
    jmp     icon_61_call
icn_62_β:
    jmp     icn_u_p2_done
icn_61_α:
    jmp     icn_62_α
icn_61_β:
    jmp     icn_62_β
icon_61_call:
    call    icn_write_str
    jmp     icn_u_p2_done
    ; CALL write  id=63
icn_64_α:
    lea     rdi, [rel icn_str_30]
    jmp     icon_63_call
icn_64_β:
    jmp     icn_61_α
icn_63_α:
    jmp     icn_64_α
icn_63_β:
    jmp     icn_64_β
icon_63_call:
    call    icn_write_str
    jmp     icn_61_α
    ; CALL write  id=65
icn_67_α:
    lea     rdi, [rel icn_str_31]
    jmp     icon_65_call
icn_67_β:
    jmp     icn_63_α
    ; EVERY  id=68
    ; CALL write  id=69
    ; CALL Image  id=70
    ; ADD  id=71
    ; INT 1  id=72
icn_72_α:
    push    1
    jmp     icon_71_compute
icn_72_β:
    jmp     icon_71_lb
    ; CONCAT  id=73
icn_74_α:
    lea     rdi, [rel icn_str_32]
    jmp     icon_73_rrelay
icn_74_β:
    jmp     icon_73_lb
    ; CALL repl  id=75
icn_75_α:
    jmp     icon_68_genb
icn_75_β:
    jmp     icon_68_genb
icon_73_lrelay:
    pop     rax
    mov     [rel icn_cc73_lptr], rax
    jmp     icon_73_lstore
icon_73_rrelay:
    mov     [rel icn_cc73_rptr], rdi
    jmp     icon_73_compute
icon_73_lb:
    jmp     icn_75_β
icn_73_α:
    mov     qword [rbp-24], 0
    jmp     icn_75_α
icn_73_β:
    mov     qword [rbp-24], 1
    jmp     icn_75_α
icon_73_lstore:
    cmp     qword [rbp-24], 0
    je      icn_74_α
    jmp     icn_74_β
icon_73_compute:
    mov     rdi, [rel icn_cc73_lptr]
    mov     rsi, [rel icn_cc73_rptr]
    call    icn_str_concat
    push    rax
    jmp     icon_71_lstore
icon_71_lb:
    jmp     icn_73_β
icn_71_α:
    mov     qword [rbp-16], 0
    jmp     icn_73_α
icn_71_β:
    jmp     icn_72_β
icon_71_lstore:
    pop     rax
    mov     [rbp-8], rax
    cmp     qword [rbp-16], 0
    je      icn_72_α
    jmp     icn_72_β
icon_71_compute:
    pop     rax
    mov     rcx, [rbp-8]
    add     rcx, rax
    push    rcx
    jmp     icon_70_push0
icon_70_push0:
    pop     rdi
    call    icn_push
    jmp     icon_70_docall
icn_70_α:
    jmp     icn_71_α
icn_70_β:
    jmp     icon_68_genb
icon_70_docall:
    call    icn_u_Image
    movzx   rax, byte [rel icn_failed]
    test    rax, rax
    jnz     icon_68_genb
    mov     rax, [rel icn_retval]
    push    rax
    jmp     icon_69_call
icn_69_α:
    jmp     icn_70_α
icn_69_β:
    jmp     icn_70_β
icon_69_call:
    pop     rdi
    call    icn_write_int
    jmp     icon_68_genb
    ; TO  id=77
    ; INT 37  id=78
icn_78_α:
    push    37
    jmp     icon_77_init
icn_78_β:
    jmp     icon_77_e1b
    ; INT 1  id=79
icn_79_α:
    push    1
    jmp     icn_78_α
icn_79_β:
    jmp     icn_67_α
icon_77_e1b:
    mov     qword [rel icon_77_e2seen], 0
    jmp     icn_79_β
icon_77_e2b:
    jmp     icn_78_β
icn_77_α:
    mov     qword [rel icon_77_e2seen], 0
    jmp     icn_79_α
icn_77_β:
    inc     qword [rel icn_77_I]
    jmp     icn_77_code
icon_77_init:
    pop     rax
    mov     [rel icon_77_bound], rax
    cmp     qword [rel icon_77_e2seen], 0
    jne     icon_77_init_e2adv
    pop     rax
    mov     [rel icon_77_e1cur], rax
    mov     [rel icn_77_I], rax
    mov     qword [rel icon_77_e2seen], 1
    jmp     icn_77_code
icon_77_init_e2adv:
    mov     rax, [rel icon_77_e1cur]
    mov     [rel icn_77_I], rax
    jmp     icn_77_code
icn_77_code:
    mov     rax, [rel icn_77_I]
    cmp     rax, [rel icon_77_bound]
    jg      icon_77_e2b
    push    rax
    jmp     icon_76_store
icn_76_α:
    jmp     icn_77_α
icn_76_β:
    jmp     icn_77_β
icon_76_store:
    pop     rax
    mov     [rel icn_gvar_i], rax
    jmp     icon_68_body
icon_68_body:
    jmp     icn_69_α
icon_68_genb:
    jmp     icn_76_β
icn_68_α:
    jmp     icn_76_α
icn_68_β:
    jmp     icn_67_α
icn_66_α:
    jmp     icn_68_α
icn_66_β:
    jmp     icn_68_β
icn_65_α:
    jmp     icn_66_α
icn_65_β:
    jmp     icn_66_β
icon_65_call:
    pop     rdi
    call    icn_write_int
    jmp     icn_63_α
    ; CALL write  id=80
icn_82_α:
    lea     rdi, [rel icn_str_33]
    jmp     icon_80_call
icn_82_β:
    jmp     icn_65_α
    ; EVERY  id=83
    ; CALL write  id=84
    ; CALL Image  id=85
    ; CALL real  id=86
icn_86_α:
    jmp     icon_83_genb
icn_86_β:
    jmp     icon_83_genb
icon_85_push0:
    pop     rdi
    call    icn_push
    jmp     icon_85_docall
icn_85_α:
    jmp     icn_86_α
icn_85_β:
    jmp     icon_83_genb
icon_85_docall:
    call    icn_u_Image
    movzx   rax, byte [rel icn_failed]
    test    rax, rax
    jnz     icon_83_genb
    mov     rax, [rel icn_retval]
    push    rax
    jmp     icon_84_call
icn_84_α:
    jmp     icn_85_α
icn_84_β:
    jmp     icn_85_β
icon_84_call:
    pop     rdi
    call    icn_write_int
    jmp     icon_83_genb
    ; TO  id=88
    ; INT 37  id=89
icn_89_α:
    push    37
    jmp     icon_88_init
icn_89_β:
    jmp     icon_88_e1b
    ; INT 1  id=90
icn_90_α:
    push    1
    jmp     icn_89_α
icn_90_β:
    jmp     icn_82_α
icon_88_e1b:
    mov     qword [rel icon_88_e2seen], 0
    jmp     icn_90_β
icon_88_e2b:
    jmp     icn_89_β
icn_88_α:
    mov     qword [rel icon_88_e2seen], 0
    jmp     icn_90_α
icn_88_β:
    inc     qword [rel icn_88_I]
    jmp     icn_88_code
icon_88_init:
    pop     rax
    mov     [rel icon_88_bound], rax
    cmp     qword [rel icon_88_e2seen], 0
    jne     icon_88_init_e2adv
    pop     rax
    mov     [rel icon_88_e1cur], rax
    mov     [rel icn_88_I], rax
    mov     qword [rel icon_88_e2seen], 1
    jmp     icn_88_code
icon_88_init_e2adv:
    mov     rax, [rel icon_88_e1cur]
    mov     [rel icn_88_I], rax
    jmp     icn_88_code
icn_88_code:
    mov     rax, [rel icn_88_I]
    cmp     rax, [rel icon_88_bound]
    jg      icon_88_e2b
    push    rax
    jmp     icon_87_store
icn_87_α:
    jmp     icn_88_α
icn_87_β:
    jmp     icn_88_β
icon_87_store:
    pop     rax
    mov     [rel icn_gvar_i], rax
    jmp     icon_83_body
icon_83_body:
    jmp     icn_84_α
icon_83_genb:
    jmp     icn_87_β
icn_83_α:
    jmp     icn_87_α
icn_83_β:
    jmp     icn_82_α
icn_81_α:
    jmp     icn_83_α
icn_81_β:
    jmp     icn_83_β
icn_80_α:
    jmp     icn_81_α
icn_80_β:
    jmp     icn_81_β
icon_80_call:
    pop     rdi
    call    icn_write_int
    jmp     icn_65_α
    ; CALL write  id=91
icn_93_α:
    lea     rdi, [rel icn_str_34]
    jmp     icon_91_call
icn_93_β:
    jmp     icn_80_α
    ; EVERY  id=94
    ; CALL write  id=95
    ; CALL Image  id=96
    ; CALL real  id=97
icn_97_α:
    jmp     icon_94_genb
icn_97_β:
    jmp     icon_94_genb
icon_96_push0:
    pop     rdi
    call    icn_push
    jmp     icon_96_docall
icn_96_α:
    jmp     icn_97_α
icn_96_β:
    jmp     icon_94_genb
icon_96_docall:
    call    icn_u_Image
    movzx   rax, byte [rel icn_failed]
    test    rax, rax
    jnz     icon_94_genb
    mov     rax, [rel icn_retval]
    push    rax
    jmp     icon_95_call
icn_95_α:
    jmp     icn_96_α
icn_95_β:
    jmp     icn_96_β
icon_95_call:
    pop     rdi
    call    icn_write_int
    jmp     icon_94_genb
    ; TO  id=99
    ; INT 37  id=100
icn_100_α:
    push    37
    jmp     icon_99_init
icn_100_β:
    jmp     icon_99_e1b
    ; INT 1  id=101
icn_101_α:
    push    1
    jmp     icn_100_α
icn_101_β:
    jmp     icn_93_α
icon_99_e1b:
    mov     qword [rel icon_99_e2seen], 0
    jmp     icn_101_β
icon_99_e2b:
    jmp     icn_100_β
icn_99_α:
    mov     qword [rel icon_99_e2seen], 0
    jmp     icn_101_α
icn_99_β:
    inc     qword [rel icn_99_I]
    jmp     icn_99_code
icon_99_init:
    pop     rax
    mov     [rel icon_99_bound], rax
    cmp     qword [rel icon_99_e2seen], 0
    jne     icon_99_init_e2adv
    pop     rax
    mov     [rel icon_99_e1cur], rax
    mov     [rel icn_99_I], rax
    mov     qword [rel icon_99_e2seen], 1
    jmp     icn_99_code
icon_99_init_e2adv:
    mov     rax, [rel icon_99_e1cur]
    mov     [rel icn_99_I], rax
    jmp     icn_99_code
icn_99_code:
    mov     rax, [rel icn_99_I]
    cmp     rax, [rel icon_99_bound]
    jg      icon_99_e2b
    push    rax
    jmp     icon_98_store
icn_98_α:
    jmp     icn_99_α
icn_98_β:
    jmp     icn_99_β
icon_98_store:
    pop     rax
    mov     [rel icn_gvar_i], rax
    jmp     icon_94_body
icon_94_body:
    jmp     icn_95_α
icon_94_genb:
    jmp     icn_98_β
icn_94_α:
    jmp     icn_98_α
icn_94_β:
    jmp     icn_93_α
icn_92_α:
    jmp     icn_94_α
icn_92_β:
    jmp     icn_94_β
icn_91_α:
    jmp     icn_92_α
icn_91_β:
    jmp     icn_92_β
icon_91_call:
    pop     rdi
    call    icn_write_int
    jmp     icn_80_α
    ; CALL write  id=102
icn_103_α:
    lea     rdi, [rel icn_str_35]
    jmp     icon_102_call
icn_103_β:
    jmp     icn_91_α
icn_102_α:
    jmp     icn_103_α
icn_102_β:
    jmp     icn_103_β
icon_102_call:
    call    icn_write_str
    jmp     icn_91_α
    ; CALL write  id=104
icn_105_α:
    lea     rdi, [rel icn_str_36]
    jmp     icon_104_call
icn_105_β:
    jmp     icn_102_α
icn_104_α:
    jmp     icn_105_α
icn_104_β:
    jmp     icn_105_β
icon_104_call:
    call    icn_write_str
    jmp     icn_102_α
    ; CALL write  id=106
icn_107_α:
    lea     rdi, [rel icn_str_37]
    jmp     icon_106_call
icn_107_β:
    jmp     icn_104_α
icn_106_α:
    jmp     icn_107_α
icn_106_β:
    jmp     icn_107_β
icon_106_call:
    call    icn_write_str
    jmp     icn_104_α
    ; CALL write  id=108
icn_109_α:
    lea     rdi, [rel icn_str_38]
    jmp     icon_108_call
icn_109_β:
    jmp     icn_106_α
icn_108_α:
    jmp     icn_109_α
icn_108_β:
    jmp     icn_109_β
icon_108_call:
    call    icn_write_str
    jmp     icn_106_α
    ; CALL write  id=110
icn_111_α:
    lea     rdi, [rel icn_str_39]
    jmp     icon_110_call
icn_111_β:
    jmp     icn_108_α
icn_110_α:
    jmp     icn_111_α
icn_110_β:
    jmp     icn_111_β
icon_110_call:
    call    icn_write_str
    jmp     icn_108_α
    ; CALL write  id=112
icn_113_α:
    lea     rdi, [rel icn_str_40]
    jmp     icon_112_call
icn_113_β:
    jmp     icn_110_α
icn_112_α:
    jmp     icn_113_α
icn_112_β:
    jmp     icn_113_β
icon_112_call:
    call    icn_write_str
    jmp     icn_110_α
    ; CALL write  id=114
icn_115_α:
    lea     rdi, [rel icn_str_41]
    jmp     icon_114_call
icn_115_β:
    jmp     icn_112_α
icn_114_α:
    jmp     icn_115_α
icn_114_β:
    jmp     icn_115_β
icon_114_call:
    call    icn_write_str
    jmp     icn_112_α
    ; CALL write  id=116
icn_117_α:
    lea     rdi, [rel icn_str_42]
    jmp     icon_116_call
icn_117_β:
    jmp     icn_114_α
icn_116_α:
    jmp     icn_117_α
icn_116_β:
    jmp     icn_117_β
icon_116_call:
    call    icn_write_str
    jmp     icn_114_α
    ; CALL write  id=118
icn_119_α:
    lea     rdi, [rel icn_str_43]
    jmp     icon_118_call
icn_119_β:
    jmp     icn_116_α
icn_118_α:
    jmp     icn_119_α
icn_118_β:
    jmp     icn_119_β
icon_118_call:
    call    icn_write_str
    jmp     icn_116_α
    ; CALL write  id=120
icn_121_α:
    lea     rdi, [rel icn_str_44]
    jmp     icon_120_call
icn_121_β:
    jmp     icn_118_α
icn_120_α:
    jmp     icn_121_α
icn_120_β:
    jmp     icn_121_β
icon_120_call:
    call    icn_write_str
    jmp     icn_118_α
    ; CALL write  id=122
icn_123_α:
    lea     rdi, [rel icn_str_45]
    jmp     icon_122_call
icn_123_β:
    jmp     icn_120_α
icn_122_α:
    jmp     icn_123_α
icn_122_β:
    jmp     icn_123_β
icon_122_call:
    call    icn_write_str
    jmp     icn_120_α
    ; CALL write  id=124
icn_125_α:
    lea     rdi, [rel icn_str_46]
    jmp     icon_124_call
icn_125_β:
    jmp     icn_122_α
icn_124_α:
    jmp     icn_125_α
icn_124_β:
    jmp     icn_125_β
icon_124_call:
    call    icn_write_str
    jmp     icn_122_α
    ; CALL write  id=126
icn_127_α:
    lea     rdi, [rel icn_str_47]
    jmp     icon_126_call
icn_127_β:
    jmp     icn_124_α
icn_126_α:
    jmp     icn_127_α
icn_126_β:
    jmp     icn_127_β
icon_126_call:
    call    icn_write_str
    jmp     icn_124_α
    ; CALL write  id=128
icn_129_α:
    lea     rdi, [rel icn_str_48]
    jmp     icon_128_call
icn_129_β:
    jmp     icn_126_α
icn_128_α:
    jmp     icn_129_α
icn_128_β:
    jmp     icn_129_β
icon_128_call:
    call    icn_write_str
    jmp     icn_126_α
    ; CALL write  id=130
icn_131_α:
    lea     rdi, [rel icn_str_49]
    jmp     icon_130_call
icn_131_β:
    jmp     icn_128_α
icn_130_α:
    jmp     icn_131_α
icn_130_β:
    jmp     icn_131_β
icon_130_call:
    call    icn_write_str
    jmp     icn_128_α
    ; CALL write  id=132
icn_133_α:
    lea     rdi, [rel icn_str_50]
    jmp     icon_132_call
icn_133_β:
    jmp     icn_130_α
icn_132_α:
    jmp     icn_133_α
icn_132_β:
    jmp     icn_133_β
icon_132_call:
    call    icn_write_str
    jmp     icn_130_α
    ; CALL write  id=134
icn_135_α:
    lea     rdi, [rel icn_str_51]
    jmp     icon_134_call
icn_135_β:
    jmp     icn_132_α
icn_134_α:
    jmp     icn_135_α
icn_134_β:
    jmp     icn_135_β
icon_134_call:
    call    icn_write_str
    jmp     icn_132_α
    ; CALL write  id=136
icn_137_α:
    lea     rdi, [rel icn_str_52]
    jmp     icon_136_call
icn_137_β:
    jmp     icn_134_α
icn_136_α:
    jmp     icn_137_α
icn_136_β:
    jmp     icn_137_β
icon_136_call:
    call    icn_write_str
    jmp     icn_134_α
    ; CALL write  id=138
icn_139_α:
    lea     rdi, [rel icn_str_53]
    jmp     icon_138_call
icn_139_β:
    jmp     icn_136_α
icn_138_α:
    jmp     icn_139_α
icn_138_β:
    jmp     icn_139_β
icon_138_call:
    call    icn_write_str
    jmp     icn_136_α
    ; CALL write  id=140
icn_141_α:
    lea     rdi, [rel icn_str_54]
    jmp     icon_140_call
icn_141_β:
    jmp     icn_138_α
icn_140_α:
    jmp     icn_141_α
icn_140_β:
    jmp     icn_141_β
icon_140_call:
    call    icn_write_str
    jmp     icn_138_α
    ; CALL write  id=142
icn_143_α:
    lea     rdi, [rel icn_str_55]
    jmp     icon_142_call
icn_143_β:
    jmp     icn_140_α
icn_142_α:
    jmp     icn_143_α
icn_142_β:
    jmp     icn_143_β
icon_142_call:
    call    icn_write_str
    jmp     icn_140_α
    ; CALL write  id=144
icn_145_α:
    lea     rdi, [rel icn_str_56]
    jmp     icon_144_call
icn_145_β:
    jmp     icn_142_α
icn_144_α:
    jmp     icn_145_α
icn_144_β:
    jmp     icn_145_β
icon_144_call:
    call    icn_write_str
    jmp     icn_142_α
    ; CALL write  id=146
icn_147_α:
    lea     rdi, [rel icn_str_57]
    jmp     icon_146_call
icn_147_β:
    jmp     icn_144_α
icn_146_α:
    jmp     icn_147_α
icn_146_β:
    jmp     icn_147_β
icon_146_call:
    call    icn_write_str
    jmp     icn_144_α
    ; CALL write  id=148
icn_149_α:
    lea     rdi, [rel icn_str_58]
    jmp     icon_148_call
icn_149_β:
    jmp     icn_146_α
icn_148_α:
    jmp     icn_149_α
icn_148_β:
    jmp     icn_149_β
icon_148_call:
    call    icn_write_str
    jmp     icn_146_α
    ; CALL write  id=150
icn_151_α:
    lea     rdi, [rel icn_str_59]
    jmp     icon_150_call
icn_151_β:
    jmp     icn_148_α
icn_150_α:
    jmp     icn_151_α
icn_150_β:
    jmp     icn_151_β
icon_150_call:
    call    icn_write_str
    jmp     icn_148_α
    ; CALL write  id=152
icn_153_α:
    lea     rdi, [rel icn_str_60]
    jmp     icon_152_call
icn_153_β:
    jmp     icn_150_α
icn_152_α:
    jmp     icn_153_α
icn_152_β:
    jmp     icn_153_β
icon_152_call:
    call    icn_write_str
    jmp     icn_150_α
    ; CALL write  id=154
icn_155_α:
    lea     rdi, [rel icn_str_61]
    jmp     icon_154_call
icn_155_β:
    jmp     icn_152_α
icn_154_α:
    jmp     icn_155_α
icn_154_β:
    jmp     icn_155_β
icon_154_call:
    call    icn_write_str
    jmp     icn_152_α
    ; CALL write  id=156
icn_157_α:
    lea     rdi, [rel icn_str_62]
    jmp     icon_156_call
icn_157_β:
    jmp     icn_154_α
icn_156_α:
    jmp     icn_157_α
icn_156_β:
    jmp     icn_157_β
icon_156_call:
    call    icn_write_str
    jmp     icn_154_α
    ; CALL write  id=158
icn_159_α:
    lea     rdi, [rel icn_str_63]
    jmp     icon_158_call
icn_159_β:
    jmp     icn_156_α
icn_158_α:
    jmp     icn_159_α
icn_158_β:
    jmp     icn_159_β
icon_158_call:
    call    icn_write_str
    jmp     icn_156_α
    ; CALL write  id=160
icn_161_α:
    lea     rdi, [rel icn_str_64]
    jmp     icon_160_call
icn_161_β:
    jmp     icn_158_α
icn_160_α:
    jmp     icn_161_α
icn_160_β:
    jmp     icn_161_β
icon_160_call:
    call    icn_write_str
    jmp     icn_158_α
    ; CALL write  id=162
icn_163_α:
    lea     rdi, [rel icn_str_65]
    jmp     icon_162_call
icn_163_β:
    jmp     icn_160_α
icn_162_α:
    jmp     icn_163_α
icn_162_β:
    jmp     icn_163_β
icon_162_call:
    call    icn_write_str
    jmp     icn_160_α
    ; CALL write  id=164
icn_165_α:
    lea     rdi, [rel icn_str_66]
    jmp     icon_164_call
icn_165_β:
    jmp     icn_162_α
icn_164_α:
    jmp     icn_165_α
icn_164_β:
    jmp     icn_165_β
icon_164_call:
    call    icn_write_str
    jmp     icn_162_α
    ; CALL write  id=166
icn_167_α:
    lea     rdi, [rel icn_str_67]
    jmp     icon_166_call
icn_167_β:
    jmp     icn_164_α
icn_166_α:
    jmp     icn_167_α
icn_166_β:
    jmp     icn_167_β
icon_166_call:
    call    icn_write_str
    jmp     icn_164_α
    ; CALL write  id=168
icn_169_α:
    lea     rdi, [rel icn_str_68]
    jmp     icon_168_call
icn_169_β:
    jmp     icn_166_α
icn_168_α:
    jmp     icn_169_α
icn_168_β:
    jmp     icn_169_β
icon_168_call:
    call    icn_write_str
    jmp     icn_166_α
    ; CALL write  id=170
icn_171_α:
    lea     rdi, [rel icn_str_69]
    jmp     icon_170_call
icn_171_β:
    jmp     icn_168_α
icn_170_α:
    jmp     icn_171_α
icn_170_β:
    jmp     icn_171_β
icon_170_call:
    call    icn_write_str
    jmp     icn_168_α
    ; CALL write  id=172
icn_173_α:
    lea     rdi, [rel icn_str_70]
    jmp     icon_172_call
icn_173_β:
    jmp     icn_170_α
icn_172_α:
    jmp     icn_173_α
icn_172_β:
    jmp     icn_173_β
icon_172_call:
    call    icn_write_str
    jmp     icn_170_α
    ; CALL write  id=174
icn_175_α:
    lea     rdi, [rel icn_str_71]
    jmp     icon_174_call
icn_175_β:
    jmp     icn_172_α
icn_174_α:
    jmp     icn_175_α
icn_174_β:
    jmp     icn_175_β
icon_174_call:
    call    icn_write_str
    jmp     icn_172_α
    ; CALL write  id=176
icn_177_α:
    lea     rdi, [rel icn_str_72]
    jmp     icon_176_call
icn_177_β:
    jmp     icn_174_α
icn_176_α:
    jmp     icn_177_α
icn_176_β:
    jmp     icn_177_β
icon_176_call:
    call    icn_write_str
    jmp     icn_174_α
    ; CALL write  id=178
icn_179_α:
    lea     rdi, [rel icn_str_73]
    jmp     icon_178_call
icn_179_β:
    jmp     icn_176_α
icn_178_α:
    jmp     icn_179_α
icn_178_β:
    jmp     icn_179_β
icon_178_call:
    call    icn_write_str
    jmp     icn_176_α
    ; CALL write  id=180
icn_181_α:
    lea     rdi, [rel icn_str_74]
    jmp     icon_180_call
icn_181_β:
    jmp     icn_178_α
icn_180_α:
    jmp     icn_181_α
icn_180_β:
    jmp     icn_181_β
icon_180_call:
    call    icn_write_str
    jmp     icn_178_α
    ; CALL write  id=182
icn_183_α:
    lea     rdi, [rel icn_str_75]
    jmp     icon_182_call
icn_183_β:
    jmp     icn_180_α
icn_182_α:
    jmp     icn_183_α
icn_182_β:
    jmp     icn_183_β
icon_182_call:
    call    icn_write_str
    jmp     icn_180_α
    ; CALL write  id=184
icn_185_α:
    lea     rdi, [rel icn_str_76]
    jmp     icon_184_call
icn_185_β:
    jmp     icn_182_α
icn_184_α:
    jmp     icn_185_α
icn_184_β:
    jmp     icn_185_β
icon_184_call:
    call    icn_write_str
    jmp     icn_182_α
    ; CALL write  id=186
icn_187_α:
    lea     rdi, [rel icn_str_77]
    jmp     icon_186_call
icn_187_β:
    jmp     icn_184_α
icn_186_α:
    jmp     icn_187_α
icn_186_β:
    jmp     icn_187_β
icon_186_call:
    call    icn_write_str
    jmp     icn_184_α
    ; CALL write  id=188
icn_189_α:
    lea     rdi, [rel icn_str_78]
    jmp     icon_188_call
icn_189_β:
    jmp     icn_186_α
icn_188_α:
    jmp     icn_189_α
icn_188_β:
    jmp     icn_189_β
icon_188_call:
    call    icn_write_str
    jmp     icn_186_α
icn_u_p2:
    push    rbp
    mov     rbp, rsp
    sub     rsp, 32
    jmp     icn_188_α
icn_u_p2_ret:
    add     rsp, 32
    pop     rbp
    ret
icn_u_p2_done:
    mov     byte [rel icn_failed], 1
    add     rsp, 32
    pop     rbp
    ret

; === procedure p3 ===
    ; CALL write  id=190
icn_191_α:
    lea     rdi, [rel icn_str_79]
    jmp     icon_190_call
icn_191_β:
    jmp     icn_u_p3_done
icn_190_α:
    jmp     icn_191_α
icn_190_β:
    jmp     icn_191_β
icon_190_call:
    call    icn_write_str
    jmp     icn_u_p3_done
    ; CALL write  id=192
icn_193_α:
    lea     rdi, [rel icn_str_80]
    jmp     icon_192_call
icn_193_β:
    jmp     icn_190_α
icn_192_α:
    jmp     icn_193_α
icn_192_β:
    jmp     icn_193_β
icon_192_call:
    call    icn_write_str
    jmp     icn_190_α
    ; CALL write  id=194
icn_195_α:
    lea     rdi, [rel icn_str_81]
    jmp     icon_194_call
icn_195_β:
    jmp     icn_192_α
icn_194_α:
    jmp     icn_195_α
icn_194_β:
    jmp     icn_195_β
icon_194_call:
    call    icn_write_str
    jmp     icn_192_α
    ; CALL write  id=196
icn_197_α:
    lea     rdi, [rel icn_str_82]
    jmp     icon_196_call
icn_197_β:
    jmp     icn_194_α
icn_196_α:
    jmp     icn_197_α
icn_196_β:
    jmp     icn_197_β
icon_196_call:
    call    icn_write_str
    jmp     icn_194_α
icn_u_p3:
    push    rbp
    mov     rbp, rsp
    jmp     icn_196_α
icn_u_p3_ret:
    pop     rbp
    ret
icn_u_p3_done:
    mov     byte [rel icn_failed], 1
    pop     rbp
    ret

; === procedure Image ===
    ; CALL image  id=200
icn_200_α:
    jmp     icon_199_ret_store
icn_200_β:
    jmp     icon_199_ret_store
icn_199_α:
    jmp     icn_200_α
icn_199_β:
    jmp     icn_u_Image_ret
icon_199_ret_store:
    pop     rax
    mov     [rel icn_retval], rax
    mov     byte [rel icn_failed], 0
    jmp     icn_u_Image_ret
    ; VAR x  id=202
icn_202_α:
    mov     rax, [rbp-8]
    push    rax
    jmp     icon_201_scan_setup
icn_202_β:
    jmp     icn_u_Image_done
    ; VAR head  id=206
icn_206_α:
    mov     rax, [rel icn_gvar_head]
    push    rax
    jmp     icon_205_scan_setup
icn_206_β:
    jmp     icon_201_scan_bfail
    ; CONCAT  id=208
    ; VAR tail  id=209
icn_209_α:
    mov     rax, [rel icn_gvar_tail]
    push    rax
    jmp     icon_208_rrelay
icn_209_β:
    jmp     icon_208_lb
    ; CALL tab  id=210
    ; INT 0  id=212
icn_212_α:
    push    0
    jmp     icon_210_taft
icn_212_β:
    jmp     icon_207_ret_store
    ; VAR span  id=213
icn_213_α:
    mov     rax, [rel icn_gvar_span]
    push    rax
    jmp     icon_210_taft
icn_213_β:
    jmp     icn_212_α
icn_211_α:
    jmp     icn_213_α
icn_211_β:
    jmp     icn_213_β
icn_210_α:
    jmp     icn_211_α
icn_210_β:
    jmp     icon_207_ret_store
icon_210_taft:
    pop     rdi
    call    icn_tab
    test    rax, rax
    jz      icon_207_ret_store
    push    rax
    jmp     icon_208_lrelay
icon_208_lrelay:
    pop     rax
    mov     [rel icn_cc208_lptr], rax
    jmp     icon_208_lstore
icon_208_rrelay:
    pop     rax
    mov     [rel icn_cc208_rptr], rax
    jmp     icon_208_compute
icon_208_lb:
    jmp     icn_210_β
icn_208_α:
    mov     qword [rbp-16], 0
    jmp     icn_210_α
icn_208_β:
    mov     qword [rbp-16], 1
    jmp     icn_210_α
icon_208_lstore:
    cmp     qword [rbp-16], 0
    je      icn_209_α
    jmp     icn_209_β
icon_208_compute:
    mov     rdi, [rel icn_cc208_lptr]
    mov     rsi, [rel icn_cc208_rptr]
    call    icn_str_concat
    push    rax
    jmp     icon_207_ret_store
icn_207_α:
    jmp     icn_208_α
icn_207_β:
    jmp     icn_u_Image_ret
icon_207_ret_store:
    pop     rax
    mov     [rel icn_retval], rax
    mov     byte [rel icn_failed], 0
    jmp     icn_u_Image_ret
    ; SCAN  id=205
icn_205_α:
    jmp     icn_206_α
icn_205_β:
    jmp     icon_205_scan_bret
icon_205_scan_setup:
    pop     rax
    push    rax
    mov     rcx, [rel icn_subject]
    mov     [rel icn_scan_oldsubj_205], rcx
    mov     rcx, [rel icn_pos]
    mov     [rel icn_scan_oldpos_205], rcx
    pop     rax
    mov     [rel icn_subject], rax
    mov     qword [rel icn_pos], 0
    jmp     icn_207_α
icon_205_scan_bok:
    mov     rax, [rel icn_scan_oldsubj_205]
    mov     [rel icn_subject], rax
    mov     rax, [rel icn_scan_oldpos_205]
    mov     [rel icn_pos], rax
    jmp     icon_201_scan_bok
icon_205_scan_bfail:
    mov     rax, [rel icn_scan_oldsubj_205]
    mov     [rel icn_subject], rax
    mov     rax, [rel icn_scan_oldpos_205]
    mov     [rel icn_pos], rax
    jmp     icn_206_β
icon_205_scan_bret:
    mov     rax, [rel icn_scan_oldsubj_205]
    mov     [rel icn_subject], rax
    mov     rax, [rel icn_scan_oldpos_205]
    mov     [rel icn_pos], rax
    jmp     icn_207_β
    ; CALL tab  id=215
    ; INT 0  id=216
icn_216_α:
    push    0
    jmp     icon_215_taft
icn_216_β:
    jmp     icon_201_scan_bfail
icn_215_α:
    jmp     icn_216_α
icn_215_β:
    jmp     icon_201_scan_bfail
icon_215_taft:
    pop     rdi
    call    icn_tab
    test    rax, rax
    jz      icon_201_scan_bfail
    push    rax
    jmp     icon_214_store
icn_214_α:
    jmp     icn_215_α
icn_214_β:
    jmp     icn_215_β
icon_214_store:
    pop     rax
    mov     [rel icn_gvar_tail], rax
    jmp     icon_204_seq_0
icon_204_seq_0:
    add     rsp, 8
    jmp     icn_205_α
icn_204_α:
    jmp     icn_214_α
icn_204_β:
    jmp     icon_201_scan_bfail
    ; VAR head  id=220
icn_220_α:
    mov     rax, [rel icn_gvar_head]
    push    rax
    jmp     icon_219_scan_setup
icn_220_β:
    jmp     icon_201_scan_bfail
    ; CONCAT  id=222
    ; ADD  id=223
    ; VAR exp  id=224
icn_224_α:
    mov     rax, [rel icn_gvar_exp]
    push    rax
    jmp     icon_223_compute
icn_224_β:
    jmp     icon_223_lb
    ; SUB  id=225
    ; INT 3  id=226
icn_226_α:
    push    3
    jmp     icon_225_compute
icn_226_β:
    jmp     icon_225_lb
    ; VAR span  id=227
icn_227_α:
    mov     rax, [rel icn_gvar_span]
    push    rax
    jmp     icon_225_lstore
icn_227_β:
    jmp     icon_222_lb
icon_225_lb:
    jmp     icn_227_β
icn_225_α:
    mov     qword [rbp-56], 0
    jmp     icn_227_α
icn_225_β:
    mov     qword [rbp-56], 1
    jmp     icn_227_α
icon_225_lstore:
    pop     rax
    mov     [rbp-48], rax
    cmp     qword [rbp-56], 0
    je      icn_226_α
    jmp     icn_226_β
icon_225_compute:
    pop     rax
    mov     rcx, [rbp-48]
    sub     rcx, rax
    push    rcx
    jmp     icon_223_lstore
icon_223_lb:
    jmp     icn_225_β
icn_223_α:
    mov     qword [rbp-40], 0
    jmp     icn_225_α
icn_223_β:
    jmp     icn_224_β
icon_223_lstore:
    pop     rax
    mov     [rbp-32], rax
    cmp     qword [rbp-40], 0
    je      icn_224_α
    jmp     icn_224_β
icon_223_compute:
    pop     rax
    mov     rcx, [rbp-32]
    add     rcx, rax
    push    rcx
    jmp     icon_222_rrelay
    ; CONCAT  id=228
icn_229_α:
    lea     rdi, [rel icn_str_83]
    jmp     icon_228_rrelay
icn_229_β:
    jmp     icon_228_lb
    ; CONCAT  id=230
    ; CALL move  id=231
    ; SUB  id=232
    ; INT 3  id=233
icn_233_α:
    push    3
    jmp     icon_232_compute
icn_233_β:
    jmp     icon_232_lb
    ; VAR span  id=234
icn_234_α:
    mov     rax, [rel icn_gvar_span]
    push    rax
    jmp     icon_232_lstore
icn_234_β:
    jmp     icon_230_lb
icon_232_lb:
    jmp     icn_234_β
icn_232_α:
    mov     qword [rbp-88], 0
    jmp     icn_234_α
icn_232_β:
    mov     qword [rbp-88], 1
    jmp     icn_234_α
icon_232_lstore:
    pop     rax
    mov     [rbp-80], rax
    cmp     qword [rbp-88], 0
    je      icn_233_α
    jmp     icn_233_β
icon_232_compute:
    pop     rax
    mov     rcx, [rbp-80]
    sub     rcx, rax
    push    rcx
    jmp     icon_231_mvaft
icn_231_α:
    jmp     icn_232_α
icn_231_β:
    jmp     icon_230_lb
icon_231_mvaft:
    pop     rdi
    call    icn_move
    test    rax, rax
    jz      icon_230_lb
    push    rax
    jmp     icon_230_rrelay
    ; CONCAT  id=235
icn_236_α:
    lea     rdi, [rel icn_str_84]
    jmp     icon_235_rrelay
icn_236_β:
    jmp     icon_235_lb
    ; CALL move  id=237
    ; INT 1  id=238
icn_238_α:
    push    1
    jmp     icon_237_mvaft
icn_238_β:
    jmp     icon_221_ret_store
icn_237_α:
    jmp     icn_238_α
icn_237_β:
    jmp     icon_221_ret_store
icon_237_mvaft:
    pop     rdi
    call    icn_move
    test    rax, rax
    jz      icon_221_ret_store
    push    rax
    jmp     icon_235_lrelay
icon_235_lrelay:
    pop     rax
    mov     [rel icn_cc235_lptr], rax
    jmp     icon_235_lstore
icon_235_rrelay:
    mov     [rel icn_cc235_rptr], rdi
    jmp     icon_235_compute
icon_235_lb:
    jmp     icn_237_β
icn_235_α:
    mov     qword [rbp-96], 0
    jmp     icn_237_α
icn_235_β:
    mov     qword [rbp-96], 1
    jmp     icn_237_α
icon_235_lstore:
    cmp     qword [rbp-96], 0
    je      icn_236_α
    jmp     icn_236_β
icon_235_compute:
    mov     rdi, [rel icn_cc235_lptr]
    mov     rsi, [rel icn_cc235_rptr]
    call    icn_str_concat
    push    rax
    jmp     icon_230_lrelay
icon_230_lrelay:
    pop     rax
    mov     [rel icn_cc230_lptr], rax
    jmp     icon_230_lstore
icon_230_rrelay:
    pop     rax
    mov     [rel icn_cc230_rptr], rax
    jmp     icon_230_compute
icon_230_lb:
    jmp     icn_235_β
icn_230_α:
    mov     qword [rbp-72], 0
    jmp     icn_235_α
icn_230_β:
    jmp     icn_231_β
icon_230_lstore:
    cmp     qword [rbp-72], 0
    je      icn_231_α
    jmp     icn_231_β
icon_230_compute:
    mov     rdi, [rel icn_cc230_lptr]
    mov     rsi, [rel icn_cc230_rptr]
    call    icn_str_concat
    push    rax
    jmp     icon_228_lrelay
icon_228_lrelay:
    pop     rax
    mov     [rel icn_cc228_lptr], rax
    jmp     icon_228_lstore
icon_228_rrelay:
    mov     [rel icn_cc228_rptr], rdi
    jmp     icon_228_compute
icon_228_lb:
    jmp     icn_230_β
icn_228_α:
    mov     qword [rbp-64], 0
    jmp     icn_230_α
icn_228_β:
    jmp     icn_229_β
icon_228_lstore:
    cmp     qword [rbp-64], 0
    je      icn_229_α
    jmp     icn_229_β
icon_228_compute:
    mov     rdi, [rel icn_cc228_lptr]
    mov     rsi, [rel icn_cc228_rptr]
    call    icn_str_concat
    push    rax
    jmp     icon_222_lrelay
icon_222_lrelay:
    pop     rax
    mov     [rel icn_cc222_lptr], rax
    jmp     icon_222_lstore
icon_222_rrelay:
    pop     rax
    mov     [rel icn_cc222_rptr], rax
    jmp     icon_222_compute
icon_222_lb:
    jmp     icn_228_β
icn_222_α:
    mov     qword [rbp-24], 0
    jmp     icn_228_α
icn_222_β:
    jmp     icn_223_β
icon_222_lstore:
    cmp     qword [rbp-24], 0
    je      icn_223_α
    jmp     icn_223_β
icon_222_compute:
    mov     rdi, [rel icn_cc222_lptr]
    mov     rsi, [rel icn_cc222_rptr]
    call    icn_str_concat
    push    rax
    jmp     icon_221_ret_store
icn_221_α:
    jmp     icn_222_α
icn_221_β:
    jmp     icn_u_Image_ret
icon_221_ret_store:
    pop     rax
    mov     [rel icn_retval], rax
    mov     byte [rel icn_failed], 0
    jmp     icn_u_Image_ret
    ; SCAN  id=219
icn_219_α:
    jmp     icn_220_α
icn_219_β:
    jmp     icon_219_scan_bret
icon_219_scan_setup:
    pop     rax
    push    rax
    mov     rcx, [rel icn_subject]
    mov     [rel icn_scan_oldsubj_219], rcx
    mov     rcx, [rel icn_pos]
    mov     [rel icn_scan_oldpos_219], rcx
    pop     rax
    mov     [rel icn_subject], rax
    mov     qword [rel icn_pos], 0
    jmp     icn_221_α
icon_219_scan_bok:
    mov     rax, [rel icn_scan_oldsubj_219]
    mov     [rel icn_subject], rax
    mov     rax, [rel icn_scan_oldpos_219]
    mov     [rel icn_pos], rax
    jmp     icon_201_scan_bok
icon_219_scan_bfail:
    mov     rax, [rel icn_scan_oldsubj_219]
    mov     [rel icn_subject], rax
    mov     rax, [rel icn_scan_oldpos_219]
    mov     [rel icn_pos], rax
    jmp     icn_220_β
icon_219_scan_bret:
    mov     rax, [rel icn_scan_oldsubj_219]
    mov     [rel icn_subject], rax
    mov     rax, [rel icn_scan_oldpos_219]
    mov     [rel icn_pos], rax
    jmp     icn_221_β
    ; VAR head  id=241
icn_241_α:
    mov     rax, [rel icn_gvar_head]
    push    rax
    jmp     icon_240_ret_store
icn_241_β:
    jmp     icon_240_ret_store
icn_240_α:
    jmp     icn_241_α
icn_240_β:
    jmp     icn_u_Image_ret
icon_240_ret_store:
    pop     rax
    mov     [rel icn_retval], rax
    mov     byte [rel icn_failed], 0
    jmp     icn_u_Image_ret
    ; CONCAT  id=244
icn_246_α:
    lea     rdi, [rel icn_str_85]
    jmp     icon_244_rrelay
icn_246_β:
    jmp     icon_244_lb
    ; CALL move  id=247
    ; INT 1  id=248
icn_248_α:
    push    1
    jmp     icon_247_mvaft
icn_248_β:
    jmp     icn_246_α
icn_247_α:
    jmp     icn_248_α
icn_247_β:
    jmp     icn_246_α
icon_247_mvaft:
    pop     rdi
    call    icn_move
    test    rax, rax
    jz      icn_246_α
    push    rax
    jmp     icon_244_rrelay
icn_245_α:
    jmp     icn_247_α
icn_245_β:
    jmp     icn_247_β
    ; VAR head  id=249
icn_249_α:
    mov     rax, [rel icn_gvar_head]
    push    rax
    jmp     icon_244_lrelay
icn_249_β:
    jmp     icon_201_scan_bfail
icon_244_lrelay:
    pop     rax
    mov     [rel icn_cc244_lptr], rax
    jmp     icon_244_lstore
icon_244_rrelay:
    pop     rax
    mov     [rel icn_cc244_rptr], rax
    jmp     icon_244_compute
icon_244_lb:
    jmp     icn_249_β
icn_244_α:
    mov     qword [rbp-104], 0
    jmp     icn_249_α
icn_244_β:
    mov     qword [rbp-104], 1
    jmp     icn_249_α
icon_244_lstore:
    cmp     qword [rbp-104], 0
    je      icn_245_α
    jmp     icn_245_β
icon_244_compute:
    mov     rdi, [rel icn_cc244_lptr]
    mov     rsi, [rel icn_cc244_rptr]
    call    icn_str_concat
    push    rax
    jmp     icon_243_aug_store
icn_243_α:
    jmp     icn_244_α
icn_243_β:
    jmp     icn_244_β
icon_243_aug_store:
    pop     rax
    mov     [rel icn_gvar_head], rax
    jmp     icon_239_seq_0
    ; SEQ  id=250
icn_251_α:
    lea     rdi, [rel icn_str_86]
    jmp     icon_250_rrelay
icn_251_β:
    jmp     icon_250_lb
    ; INT 1  id=254
icn_254_α:
    push    1
    jmp     icon_253_neg
icn_254_β:
    jmp     icon_242_else
icn_253_α:
    jmp     icn_254_α
icn_253_β:
    jmp     icn_254_β
icon_253_neg:
    pop     rax
    neg     rax
    push    rax
    jmp     icon_252_sub_gi
    ; VAR head  id=255
icn_255_α:
    mov     rax, [rel icn_gvar_head]
    push    rax
    jmp     icon_252_sub_go
icn_255_β:
    jmp     icon_242_else
icn_252_α:
    jmp     icn_255_α
icn_252_β:
    jmp     icn_253_β
icon_252_sub_gi:
    pop     rax
    mov     [rbp-112], rax
    jmp     icn_255_α
icon_252_sub_go:
    pop     rdi
    mov     rsi, [rbp-112]
    dec     rsi
    call    icn_str_subscript
    push    rax
    jmp     icon_250_lrelay
icon_250_lrelay:
    pop     rax
    mov     [rel icn_sq250_lptr], rax
    jmp     icon_250_lstore
icon_250_rrelay:
    mov     [rel icn_sq250_rptr], rdi
    jmp     icon_250_check
icon_250_lb:
    jmp     icn_252_β
icn_250_α:
    jmp     icn_252_α
icn_250_β:
    jmp     icn_251_β
icon_250_lstore:
    jmp     icn_251_α
icon_250_check:
    mov     rdi, [rel icn_sq250_lptr]
    mov     rsi, [rel icn_sq250_rptr]
    call    icn_str_eq
    test    rax, rax
    jz      icn_251_β
    push    0
    jmp     icon_242_then
icon_242_then:
    add     rsp, 8
    jmp     icn_243_α
icon_242_else:
    jmp     icon_201_scan_bfail
icn_242_α:
    jmp     icn_250_α
icn_242_β:
    jmp     icn_250_β
icon_239_seq_0:
    add     rsp, 8
    jmp     icn_240_α
icn_239_α:
    jmp     icn_242_α
icn_239_β:
    jmp     icon_201_scan_bfail
    ; CALL tab  id=258
    ; CALL upto  id=259
icn_260_α:
    lea     rdi, [rel icn_str_87]
    jmp     icon_259_sbuiltin
icn_260_β:
    jmp     icon_218_else
icn_259_α:
    jmp     icn_260_α
icn_259_β:
    jmp     icn_260_β
icon_259_sbuiltin:
    call    icn_upto
    test    rax, rax
    jz      icon_218_else
    push    rax
    jmp     icon_258_taft
icn_258_α:
    jmp     icn_259_α
icn_258_β:
    jmp     icon_218_else
icon_258_taft:
    pop     rdi
    call    icn_tab
    test    rax, rax
    jz      icon_218_else
    push    rax
    jmp     icon_257_size_relay
icn_257_α:
    jmp     icn_258_α
icn_257_β:
    jmp     icn_258_β
icon_257_size_relay:
    pop     rdi
    call    icn_strlen
    push    rax
    jmp     icon_256_store
icn_256_α:
    jmp     icn_257_α
icn_256_β:
    jmp     icn_257_β
icon_256_store:
    pop     rax
    mov     [rel icn_gvar_exp], rax
    jmp     icon_218_then
icon_218_then:
    add     rsp, 8
    jmp     icn_219_α
icon_218_else:
    jmp     icn_239_α
icn_218_α:
    jmp     icn_256_α
icn_218_β:
    jmp     icn_256_β
    ; CALL tab  id=262
    ; INT 0  id=264
icn_264_α:
    push    0
    jmp     icon_262_taft
icn_264_β:
    jmp     icon_201_scan_bfail
    ; SUB  id=265
    ; INT 1  id=266
icn_266_α:
    push    1
    jmp     icon_265_compute
icn_266_β:
    jmp     icon_265_lb
    ; VAR span  id=267
icn_267_α:
    mov     rax, [rel icn_gvar_span]
    push    rax
    jmp     icon_265_lstore
icn_267_β:
    jmp     icn_264_α
icon_265_lb:
    jmp     icn_267_β
icn_265_α:
    mov     qword [rbp-128], 0
    jmp     icn_267_α
icn_265_β:
    mov     qword [rbp-128], 1
    jmp     icn_267_α
icon_265_lstore:
    pop     rax
    mov     [rbp-120], rax
    cmp     qword [rbp-128], 0
    je      icn_266_α
    jmp     icn_266_β
icon_265_compute:
    pop     rax
    mov     rcx, [rbp-120]
    sub     rcx, rax
    push    rcx
    jmp     icon_262_taft
icn_263_α:
    jmp     icn_265_α
icn_263_β:
    jmp     icn_265_β
icn_262_α:
    jmp     icn_263_α
icn_262_β:
    jmp     icon_201_scan_bfail
icon_262_taft:
    pop     rdi
    call    icn_tab
    test    rax, rax
    jz      icon_201_scan_bfail
    push    rax
    jmp     icon_261_store
icn_261_α:
    jmp     icn_262_α
icn_261_β:
    jmp     icn_262_β
icon_261_store:
    pop     rax
    mov     [rel icn_gvar_head], rax
    jmp     icon_217_seq_0
icon_217_seq_0:
    add     rsp, 8
    jmp     icn_218_α
icn_217_α:
    jmp     icn_261_α
icn_217_β:
    jmp     icon_201_scan_bfail
    ; CALL tab  id=269
    ; CALL upto  id=270
icn_271_α:
    lea     rdi, [rel icn_str_88]
    jmp     icon_270_sbuiltin
icn_271_β:
    jmp     icon_203_else
icn_270_α:
    jmp     icn_271_α
icn_270_β:
    jmp     icn_271_β
icon_270_sbuiltin:
    call    icn_upto
    test    rax, rax
    jz      icon_203_else
    push    rax
    jmp     icon_269_taft
icn_269_α:
    jmp     icn_270_α
icn_269_β:
    jmp     icon_203_else
icon_269_taft:
    pop     rdi
    call    icn_tab
    test    rax, rax
    jz      icon_203_else
    push    rax
    jmp     icon_268_store
icn_268_α:
    jmp     icn_269_α
icn_268_β:
    jmp     icn_269_β
icon_268_store:
    pop     rax
    mov     [rel icn_gvar_head], rax
    jmp     icon_203_then
icon_203_then:
    add     rsp, 8
    jmp     icn_204_α
icon_203_else:
    jmp     icn_217_α
icn_203_α:
    jmp     icn_268_α
icn_203_β:
    jmp     icn_268_β
    ; SCAN  id=201
icn_201_α:
    jmp     icn_202_α
icn_201_β:
    jmp     icon_201_scan_bret
icon_201_scan_setup:
    pop     rax
    push    rax
    mov     rcx, [rel icn_subject]
    mov     [rel icn_scan_oldsubj_201], rcx
    mov     rcx, [rel icn_pos]
    mov     [rel icn_scan_oldpos_201], rcx
    pop     rax
    mov     [rel icn_subject], rax
    mov     qword [rel icn_pos], 0
    jmp     icn_203_α
icon_201_scan_bok:
    mov     rax, [rel icn_scan_oldsubj_201]
    mov     [rel icn_subject], rax
    mov     rax, [rel icn_scan_oldpos_201]
    mov     [rel icn_pos], rax
    jmp     icn_u_Image_done
icon_201_scan_bfail:
    mov     rax, [rel icn_scan_oldsubj_201]
    mov     [rel icn_subject], rax
    mov     rax, [rel icn_scan_oldpos_201]
    mov     [rel icn_pos], rax
    jmp     icn_202_β
icon_201_scan_bret:
    mov     rax, [rel icn_scan_oldsubj_201]
    mov     [rel icn_subject], rax
    mov     rax, [rel icn_scan_oldpos_201]
    mov     [rel icn_pos], rax
    jmp     icn_203_β
icn_273_α:
    lea     rdi, [rel icn_str_89]
    jmp     icon_272_sr_gr
icn_273_β:
    jmp     icon_198_else
    ; CALL type  id=274
icn_274_α:
    jmp     icon_198_else
icn_274_β:
    jmp     icon_198_else
icn_272_α:
    jmp     icn_274_α
icn_272_β:
    jmp     icn_273_β
icon_272_sr_gr:
    pop     rax
    mov     [rbp-136], rax
    jmp     icn_274_α
icon_272_sr_gl:
    pop     rdi
    mov     rsi, [rbp-136]
    call    icn_str_cmp
    test    eax, eax
    je     icon_198_else
    push    qword [rbp-136]
    jmp     icon_198_then
icon_198_then:
    add     rsp, 8
    jmp     icn_199_α
icon_198_else:
    jmp     icn_201_α
icn_198_α:
    jmp     icn_272_α
icn_198_β:
    jmp     icn_272_β
    ; INT 9  id=276
icn_276_α:
    push    9
    jmp     icon_275_store
icn_276_β:
    jmp     icn_198_α
icn_275_α:
    jmp     icn_276_α
icn_275_β:
    jmp     icn_276_β
icon_275_store:
    pop     rax
    mov     [rel icn_gvar_span], rax
    jmp     icn_198_α
icn_u_Image:
    push    rbp
    mov     rbp, rsp
    sub     rsp, 144
    call    icn_pop
    mov     [rbp-8], rax
    jmp     icn_275_α
icn_u_Image_ret:
    add     rsp, 144
    pop     rbp
    ret
icn_u_Image_done:
    mov     byte [rel icn_failed], 1
    add     rsp, 144
    pop     rbp
    ret
