; Auto-generated by icon_emit.c — Tiny-ICON Byrd Box x64
bits 64
default rel

section .rodata
icn_str_0:  db  102, 0

section .bss
    icn_retval: resq 1
    icon_6_bang_str: resq 1
    icon_6_bang_pos: resq 1
    icn_gvar_b: resq 1
    icn_gvar_a: resq 1
    icn_cc23_lptr: resq 1
    icn_cc23_rptr: resq 1
    icn_24_I: resq 1
    icon_24_bound: resq 1
    icon_24_e1cur: resq 1
    icon_24_e2seen: resq 1
    icn_32_I: resq 1
    icon_32_bound: resq 1
    icon_32_e1cur: resq 1
    icon_32_e2seen: resq 1
    icon_39_bang_str: resq 1
    icon_39_bang_pos: resq 1
    icon_55_bang_str: resq 1
    icon_55_bang_pos: resq 1
    icn_failed: resb 1
    icn_suspended: resb 1
    icn_suspend_resume: resq 1
    icn_suspend_rbp: resq 1

section .text
    global _start
    extern icn_write_int
    extern icn_write_str
    extern icn_push
    extern icn_pop
    extern icn_str_concat
    extern icn_str_eq
    extern icn_any
    extern icn_many
    extern icn_upto
    extern icn_str_find
    extern icn_match
    extern icn_tab
    extern icn_move
    extern icn_subject
    extern icn_pos
    extern icn_str_cmp
    extern icn_strlen
    extern icn_pow
    extern icn_str_subscript
    extern icn_str_section
    extern icn_bang_char_at
    extern icn_match_pat
    extern icn_cset_complement
    extern icn_cset_union
    extern icn_cset_diff
    extern icn_cset_inter

_start:
    call    icn_main
    mov     rax, 60
    xor     rdi, rdi
    syscall


; === procedure main ===
    ; EVERY  id=0
    ; CALL writes  id=1
icn_1_α:
    jmp     icn_main_done
icn_1_β:
    jmp     icn_main_done
icon_0_genb:
    jmp     icn_1_β
icn_0_α:
    jmp     icn_1_α
icn_0_β:
    jmp     icn_main_done
    ; EVERY  id=2
    ; ADD  id=4
    ; INT 70  id=5
icn_5_α:
    push    70
    jmp     icon_4_compute
icn_5_β:
    jmp     icon_4_lb
    ; VAR b  id=7
icn_7_α:
    mov     rax, [rel icn_gvar_b]
    push    rax
    jmp     icon_6_bang_as
icn_7_β:
    jmp     icn_0_α
icon_6_bang_as:
    pop     rax
    mov     [rel icon_6_bang_str], rax
    mov     qword [rel icon_6_bang_pos], 0
icon_6_bang_chk:
    mov     rdi, [rel icon_6_bang_str]
    call    icn_strlen
    cmp     [rel icon_6_bang_pos], rax
    jge     icn_0_α
    mov     rdi, [rel icon_6_bang_str]
    mov     rsi, [rel icon_6_bang_pos]
    call    icn_bang_char_at
    push    rax
    inc     qword [rel icon_6_bang_pos]
    jmp     icon_4_lstore
icn_6_α:
    jmp     icn_7_α
icn_6_β:
    jmp     icon_6_bang_chk
icon_4_lb:
    jmp     icn_6_β
icn_4_α:
    mov     qword [rbp-16], 0
    jmp     icn_6_α
icn_4_β:
    jmp     icn_5_β
icon_4_lstore:
    pop     rax
    mov     [rbp-8], rax
    cmp     qword [rbp-16], 0
    je      icn_5_α
    jmp     icn_5_β
icon_4_compute:
    pop     rax
    mov     rcx, [rbp-8]
    add     rcx, rax
    push    rcx
    jmp     icon_3_aug_store
icn_3_α:
    jmp     icn_4_α
icn_3_β:
    jmp     icn_4_β
icon_3_aug_store:
    pop     rax
    jmp     icon_2_genb
icon_2_genb:
    jmp     icn_3_β
icn_2_α:
    jmp     icn_3_α
icn_2_β:
    jmp     icn_0_α
    ; ADD  id=9
    ; INT 20  id=10
icn_10_α:
    push    20
    jmp     icon_9_compute
icn_10_β:
    jmp     icon_9_lb
icn_11_α:
    push    0
    jmp     icon_9_lstore
icn_11_β:
    jmp     icn_2_α
icon_9_lb:
    jmp     icn_11_β
icn_9_α:
    mov     qword [rbp-32], 0
    jmp     icn_11_α
icn_9_β:
    jmp     icn_10_β
icon_9_lstore:
    pop     rax
    mov     [rbp-24], rax
    cmp     qword [rbp-32], 0
    je      icn_10_α
    jmp     icn_10_β
icon_9_compute:
    pop     rax
    mov     rcx, [rbp-24]
    add     rcx, rax
    push    rcx
    jmp     icon_8_aug_store
icn_8_α:
    jmp     icn_9_α
icn_8_β:
    jmp     icn_9_β
icon_8_aug_store:
    pop     rax
    jmp     icn_2_α
    ; ADD  id=13
    ; INT 10  id=14
icn_14_α:
    push    10
    jmp     icon_13_compute
icn_14_β:
    jmp     icon_13_lb
icn_15_α:
    push    0
    jmp     icon_13_lstore
icn_15_β:
    jmp     icn_8_α
icon_13_lb:
    jmp     icn_15_β
icn_13_α:
    mov     qword [rbp-48], 0
    jmp     icn_15_α
icn_13_β:
    jmp     icn_14_β
icon_13_lstore:
    pop     rax
    mov     [rbp-40], rax
    cmp     qword [rbp-48], 0
    je      icn_14_α
    jmp     icn_14_β
icon_13_compute:
    pop     rax
    mov     rcx, [rbp-40]
    add     rcx, rax
    push    rcx
    jmp     icon_12_aug_store
icn_12_α:
    jmp     icn_13_α
icn_12_β:
    jmp     icn_13_β
icon_12_aug_store:
    pop     rax
    jmp     icn_8_α
    ; CALL rec  id=17
icn_17_α:
    jmp     icn_12_α
icn_17_β:
    jmp     icn_12_α
icn_16_α:
    jmp     icn_17_α
icn_16_β:
    jmp     icn_17_β
icon_16_store:
    pop     rax
    mov     [rel icn_gvar_b], rax
    jmp     icn_12_α
    ; CALL rec  id=19
icn_19_α:
    jmp     icn_16_α
icn_19_β:
    jmp     icn_16_α
icn_18_α:
    jmp     icn_19_α
icn_18_β:
    jmp     icn_19_β
icon_18_store:
    pop     rax
    mov     [rel icn_gvar_a], rax
    jmp     icn_16_α
    ; EVERY  id=20
    ; CALL write  id=21
    ; CONCAT  id=23
    ; TO  id=24
    ; INT 3  id=25
icn_25_α:
    push    3
    jmp     icon_24_init
icn_25_β:
    jmp     icon_24_e1b
    ; INT 1  id=26
icn_26_α:
    push    1
    jmp     icn_25_α
icn_26_β:
    jmp     icon_23_lb
icon_24_e1b:
    mov     qword [rel icon_24_e2seen], 0
    jmp     icn_26_β
icon_24_e2b:
    jmp     icn_25_β
icn_24_α:
    mov     qword [rel icon_24_e2seen], 0
    jmp     icn_26_α
icn_24_β:
    inc     qword [rel icn_24_I]
    jmp     icn_24_code
icon_24_init:
    pop     rax
    mov     [rel icon_24_bound], rax
    cmp     qword [rel icon_24_e2seen], 0
    jne     icon_24_init_e2adv
    pop     rax
    mov     [rel icon_24_e1cur], rax
    mov     [rel icn_24_I], rax
    mov     qword [rel icon_24_e2seen], 1
    jmp     icn_24_code
icon_24_init_e2adv:
    mov     rax, [rel icon_24_e1cur]
    mov     [rel icn_24_I], rax
    jmp     icn_24_code
icn_24_code:
    mov     rax, [rel icn_24_I]
    cmp     rax, [rel icon_24_bound]
    jg      icon_24_e2b
    push    rax
    jmp     icon_23_rrelay
icn_27_α:
    lea     rdi, [rel icn_str_0]
    jmp     icon_23_lrelay
icn_27_β:
    jmp     icn_18_α
icon_23_lrelay:
    mov     [rel icn_cc23_lptr], rdi
    jmp     icon_23_lstore
icon_23_rrelay:
    pop     rax
    mov     [rel icn_cc23_rptr], rax
    jmp     icon_23_compute
icon_23_lb:
    jmp     icn_27_β
icn_23_α:
    mov     qword [rbp-64], 0
    jmp     icn_27_α
icn_23_β:
    mov     qword [rbp-64], 1
    jmp     icn_27_α
icon_23_lstore:
    cmp     qword [rbp-64], 0
    je      icn_24_α
    jmp     icn_24_β
icon_23_compute:
    mov     rdi, [rel icn_cc23_lptr]
    mov     rsi, [rel icn_cc23_rptr]
    call    icn_str_concat
    push    rax
    jmp     icon_22_sub_gi
    ; VAR b  id=28
icn_28_α:
    mov     rax, [rel icn_gvar_b]
    push    rax
    jmp     icon_22_sub_go
icn_28_β:
    jmp     icn_18_α
icn_22_α:
    jmp     icn_28_α
icn_22_β:
    jmp     icn_23_β
icon_22_sub_gi:
    pop     rax
    mov     [rbp-56], rax
    jmp     icn_28_α
icon_22_sub_go:
    pop     rdi
    mov     rsi, [rbp-56]
    dec     rsi
    call    icn_str_subscript
    push    rax
    jmp     icon_21_call
icn_21_α:
    jmp     icn_22_α
icn_21_β:
    jmp     icn_22_β
icon_21_call:
    pop     rdi
    call    icn_write_int
    jmp     icon_20_genb
icon_20_genb:
    jmp     icn_21_β
icn_20_α:
    jmp     icn_21_α
icn_20_β:
    jmp     icn_18_α
    ; EVERY  id=29
    ; CALL write  id=30
    ; TO  id=32
    ; INT 3  id=33
icn_33_α:
    push    3
    jmp     icon_32_init
icn_33_β:
    jmp     icon_32_e1b
    ; INT 1  id=34
icn_34_α:
    push    1
    jmp     icn_33_α
icn_34_β:
    jmp     icn_20_α
icon_32_e1b:
    mov     qword [rel icon_32_e2seen], 0
    jmp     icn_34_β
icon_32_e2b:
    jmp     icn_33_β
icn_32_α:
    mov     qword [rel icon_32_e2seen], 0
    jmp     icn_34_α
icn_32_β:
    inc     qword [rel icn_32_I]
    jmp     icn_32_code
icon_32_init:
    pop     rax
    mov     [rel icon_32_bound], rax
    cmp     qword [rel icon_32_e2seen], 0
    jne     icon_32_init_e2adv
    pop     rax
    mov     [rel icon_32_e1cur], rax
    mov     [rel icn_32_I], rax
    mov     qword [rel icon_32_e2seen], 1
    jmp     icn_32_code
icon_32_init_e2adv:
    mov     rax, [rel icon_32_e1cur]
    mov     [rel icn_32_I], rax
    jmp     icn_32_code
icn_32_code:
    mov     rax, [rel icn_32_I]
    cmp     rax, [rel icon_32_bound]
    jg      icon_32_e2b
    push    rax
    jmp     icon_31_sub_gi
    ; VAR b  id=35
icn_35_α:
    mov     rax, [rel icn_gvar_b]
    push    rax
    jmp     icon_31_sub_go
icn_35_β:
    jmp     icn_20_α
icn_31_α:
    jmp     icn_35_α
icn_31_β:
    jmp     icn_32_β
icon_31_sub_gi:
    pop     rax
    mov     [rbp-72], rax
    jmp     icn_35_α
icon_31_sub_go:
    pop     rdi
    mov     rsi, [rbp-72]
    dec     rsi
    call    icn_str_subscript
    push    rax
    jmp     icon_30_call
icn_30_α:
    jmp     icn_31_α
icn_30_β:
    jmp     icn_31_β
icon_30_call:
    pop     rdi
    call    icn_write_int
    jmp     icon_29_genb
icon_29_genb:
    jmp     icn_30_β
icn_29_α:
    jmp     icn_30_α
icn_29_β:
    jmp     icn_20_α
    ; CALL rec  id=37
icn_37_α:
    jmp     icn_29_α
icn_37_β:
    jmp     icn_29_α
icn_36_α:
    jmp     icn_37_α
icn_36_β:
    jmp     icn_37_β
icon_36_store:
    pop     rax
    mov     [rel icn_gvar_b], rax
    jmp     icn_29_α
    ; CALL write  id=38
    ; VAR b  id=40
icn_40_α:
    mov     rax, [rel icn_gvar_b]
    push    rax
    jmp     icon_39_bang_as
icn_40_β:
    jmp     icn_36_α
icon_39_bang_as:
    pop     rax
    mov     [rel icon_39_bang_str], rax
    mov     qword [rel icon_39_bang_pos], 0
icon_39_bang_chk:
    mov     rdi, [rel icon_39_bang_str]
    call    icn_strlen
    cmp     [rel icon_39_bang_pos], rax
    jge     icn_36_α
    mov     rdi, [rel icon_39_bang_str]
    mov     rsi, [rel icon_39_bang_pos]
    call    icn_bang_char_at
    push    rax
    inc     qword [rel icon_39_bang_pos]
    jmp     icon_38_call
icn_39_α:
    jmp     icn_40_α
icn_39_β:
    jmp     icon_39_bang_chk
icn_38_α:
    jmp     icn_39_α
icn_38_β:
    jmp     icn_39_β
icon_38_call:
    pop     rdi
    call    icn_write_int
    jmp     icn_36_α
    ; INT 15  id=42
icn_42_α:
    push    15
    jmp     icon_41_store
icn_42_β:
    jmp     icn_38_α
icn_41_α:
    jmp     icn_42_α
icn_41_β:
    jmp     icn_42_β
icon_41_store:
    pop     rax
    jmp     icn_38_α
    ; CALL write  id=43
    ; VAR b  id=45
icn_45_α:
    mov     rax, [rel icn_gvar_b]
    push    rax
    jmp     icon_44_rand
icn_45_β:
    jmp     icn_41_α
icn_44_α:
    jmp     icn_45_α
icn_44_β:
    jmp     icn_45_β
icon_44_rand:
    pop     rdi
    extern  icn_random
    call    icn_random
    push    rax
    jmp     icon_43_call
icn_43_α:
    jmp     icn_44_α
icn_43_β:
    jmp     icn_44_β
icon_43_call:
    pop     rdi
    call    icn_write_int
    jmp     icn_41_α
    ; CALL simple  id=47
icn_47_α:
    jmp     icn_43_α
icn_47_β:
    jmp     icn_43_α
icn_46_α:
    jmp     icn_47_α
icn_46_β:
    jmp     icn_47_β
icon_46_store:
    pop     rax
    mov     [rel icn_gvar_b], rax
    jmp     icn_43_α
    ; CALL write  id=48
icn_49_α:
    push    0
    jmp     icon_48_call
icn_49_β:
    jmp     icn_46_α
icn_48_α:
    jmp     icn_49_α
icn_48_β:
    jmp     icn_49_β
icon_48_call:
    pop     rdi
    call    icn_write_int
    jmp     icn_46_α
    ; EVERY  id=50
    ; INT 13  id=52
icn_52_α:
    push    13
    jmp     icon_51_store
icn_52_β:
    jmp     icn_48_α
icn_51_α:
    jmp     icn_52_α
icn_51_β:
    jmp     icn_52_β
icon_51_store:
    pop     rax
    jmp     icon_50_genb
icon_50_genb:
    jmp     icn_51_β
icn_50_α:
    jmp     icn_51_α
icn_50_β:
    jmp     icn_48_α
    ; EVERY  id=53
    ; CALL write  id=54
    ; VAR a  id=56
icn_56_α:
    mov     rax, [rel icn_gvar_a]
    push    rax
    jmp     icon_55_bang_as
icn_56_β:
    jmp     icn_50_α
icon_55_bang_as:
    pop     rax
    mov     [rel icon_55_bang_str], rax
    mov     qword [rel icon_55_bang_pos], 0
icon_55_bang_chk:
    mov     rdi, [rel icon_55_bang_str]
    call    icn_strlen
    cmp     [rel icon_55_bang_pos], rax
    jge     icn_50_α
    mov     rdi, [rel icon_55_bang_str]
    mov     rsi, [rel icon_55_bang_pos]
    call    icn_bang_char_at
    push    rax
    inc     qword [rel icon_55_bang_pos]
    jmp     icon_54_call
icn_55_α:
    jmp     icn_56_α
icn_55_β:
    jmp     icon_55_bang_chk
icn_54_α:
    jmp     icn_55_α
icn_54_β:
    jmp     icn_55_β
icon_54_call:
    pop     rdi
    call    icn_write_int
    jmp     icon_53_genb
icon_53_genb:
    jmp     icn_54_β
icn_53_α:
    jmp     icn_54_α
icn_53_β:
    jmp     icn_50_α
    ; CALL rec  id=58
icn_58_α:
    jmp     icn_53_α
icn_58_β:
    jmp     icn_53_α
icn_57_α:
    jmp     icn_58_α
icn_57_β:
    jmp     icn_58_β
icon_57_store:
    pop     rax
    mov     [rel icn_gvar_a], rax
    jmp     icn_53_α
    ; CALL write  id=59
icn_60_α:
    push    0
    jmp     icon_59_call
icn_60_β:
    jmp     icn_57_α
icn_59_α:
    jmp     icn_60_α
icn_59_β:
    jmp     icn_60_β
icon_59_call:
    pop     rdi
    call    icn_write_int
    jmp     icn_57_α
    ; CALL rec  id=62
icn_62_α:
    jmp     icn_59_α
icn_62_β:
    jmp     icn_59_α
icn_61_α:
    jmp     icn_62_α
icn_61_β:
    jmp     icn_62_β
icon_61_store:
    pop     rax
    mov     [rel icn_gvar_a], rax
    jmp     icn_59_α
    ; CALL write  id=63
icn_64_α:
    push    0
    jmp     icon_63_call
icn_64_β:
    jmp     icn_61_α
icn_63_α:
    jmp     icn_64_α
icn_63_β:
    jmp     icn_64_β
icon_63_call:
    pop     rdi
    call    icn_write_int
    jmp     icn_61_α
    ; INT 8  id=66
icn_66_α:
    push    8
    jmp     icon_65_store
icn_66_β:
    jmp     icn_63_α
icn_65_α:
    jmp     icn_66_α
icn_65_β:
    jmp     icn_66_β
icon_65_store:
    pop     rax
    jmp     icn_63_α
    ; INT 7  id=68
icn_68_α:
    push    7
    jmp     icon_67_store
icn_68_β:
    jmp     icn_65_α
icn_67_α:
    jmp     icn_68_α
icn_67_β:
    jmp     icn_68_β
icon_67_store:
    pop     rax
    jmp     icn_65_α
    ; CALL write  id=69
icn_70_α:
    push    0
    jmp     icon_69_call
icn_70_β:
    jmp     icn_67_α
icn_69_α:
    jmp     icn_70_α
icn_69_β:
    jmp     icn_70_β
icon_69_call:
    pop     rdi
    call    icn_write_int
    jmp     icn_67_α
    ; CALL rec  id=72
icn_72_α:
    jmp     icn_69_α
icn_72_β:
    jmp     icn_69_α
icn_71_α:
    jmp     icn_72_α
icn_71_β:
    jmp     icn_72_β
icon_71_store:
    pop     rax
    mov     [rel icn_gvar_a], rax
    jmp     icn_69_α
    ; CALL write  id=73
icn_74_α:
    push    0
    jmp     icon_73_call
icn_74_β:
    jmp     icn_71_α
icn_73_α:
    jmp     icn_74_α
icn_73_β:
    jmp     icn_74_β
icon_73_call:
    pop     rdi
    call    icn_write_int
    jmp     icn_71_α
    ; INT 4  id=76
icn_76_α:
    push    4
    jmp     icon_75_store
icn_76_β:
    jmp     icn_73_α
icn_75_α:
    jmp     icn_76_α
icn_75_β:
    jmp     icn_76_β
icon_75_store:
    pop     rax
    jmp     icn_73_α
    ; CALL rec  id=78
icn_78_α:
    jmp     icn_75_α
icn_78_β:
    jmp     icn_75_α
icn_77_α:
    jmp     icn_78_α
icn_77_β:
    jmp     icn_78_β
icon_77_store:
    pop     rax
    mov     [rel icn_gvar_a], rax
    jmp     icn_75_α
    ; CALL write  id=79
icn_80_α:
    push    0
    jmp     icon_79_call
icn_80_β:
    jmp     icn_77_α
icn_79_α:
    jmp     icn_80_α
icn_79_β:
    jmp     icn_80_β
icon_79_call:
    pop     rdi
    call    icn_write_int
    jmp     icn_77_α
    ; INT 2  id=82
icn_82_α:
    push    2
    jmp     icon_81_store
icn_82_β:
    jmp     icn_79_α
icn_81_α:
    jmp     icn_82_α
icn_81_β:
    jmp     icn_82_β
icon_81_store:
    pop     rax
    jmp     icn_79_α
    ; INT 1  id=84
icn_84_α:
    push    1
    jmp     icon_83_store
icn_84_β:
    jmp     icn_81_α
icn_83_α:
    jmp     icn_84_α
icn_83_β:
    jmp     icn_84_β
icon_83_store:
    pop     rax
    jmp     icn_81_α
    ; CALL rec  id=86
icn_86_α:
    jmp     icn_83_α
icn_86_β:
    jmp     icn_83_α
icn_85_α:
    jmp     icn_86_α
icn_85_β:
    jmp     icn_86_β
icon_85_store:
    pop     rax
    mov     [rel icn_gvar_a], rax
    jmp     icn_83_α
icn_main:
    push    rbp
    mov     rbp, rsp
    sub     rsp, 80
    jmp     icn_85_α
icn_main_done:
    mov     byte [rel icn_failed], 1
    add     rsp, 80
    pop     rbp
    ret
