; Auto-generated by icon_emit.c — Tiny-ICON Byrd Box x64
bits 64
default rel

section .bss
    icn_retval: resq 1
    icn_gvar_i: resq 1
    icn_9_I: resq 1
    icon_9_bound: resq 1
    icon_9_e1cur: resq 1
    icon_9_e2seen: resq 1
    icn_16_I: resq 1
    icon_16_bound: resq 1
    icon_16_e1cur: resq 1
    icon_16_e2seen: resq 1
    icn_failed: resb 1
    icn_suspended: resb 1
    icn_suspend_resume: resq 1
    icn_suspend_rbp: resq 1

section .text
    global _start
    extern icn_write_int
    extern icn_write_str
    extern icn_push
    extern icn_pop
    extern icn_str_concat
    extern icn_str_eq
    extern icn_any
    extern icn_many
    extern icn_upto
    extern icn_str_find
    extern icn_match
    extern icn_tab
    extern icn_move
    extern icn_subject
    extern icn_pos
    extern icn_str_cmp
    extern icn_strlen
    extern icn_pow
    extern icn_str_subscript
    extern icn_str_section
    extern icn_bang_char_at
    extern icn_match_pat
    extern icn_cset_complement
    extern icn_cset_union
    extern icn_cset_diff
    extern icn_cset_inter

_start:
    call    icn_main
    mov     rax, 60
    xor     rdi, rdi
    syscall


; === procedure main ===
    ; EVERY  id=0
    ; CALL write  id=2
    ; VAR i  id=3
icn_3_α:
    mov     rax, [rel icn_gvar_i]
    push    rax
    jmp     icon_2_call
icn_3_β:
    jmp     icon_0_genb
icn_2_α:
    jmp     icn_3_α
icn_2_β:
    jmp     icn_3_β
icon_2_call:
    pop     rdi
    call    icn_write_int
    jmp     icon_0_genb
icn_5_α:
    jmp     icon_0_genb
icn_5_β:
    jmp     icon_0_genb
    ; EQ  id=6
    ; INT 0  id=7
icn_7_α:
    push    0
    jmp     icon_6_check
icn_7_β:
    jmp     icon_6_lb
    ; MOD  id=8
    ; TO  id=9
    ; SUB  id=10
    ; INT 1  id=11
icn_11_α:
    push    1
    jmp     icon_10_compute
icn_11_β:
    jmp     icon_10_lb
    ; VAR i  id=12
icn_12_α:
    mov     rax, [rel icn_gvar_i]
    push    rax
    jmp     icon_10_lstore
icn_12_β:
    jmp     icon_9_e1b
icon_10_lb:
    jmp     icn_12_β
icn_10_α:
    mov     qword [rbp-40], 0
    jmp     icn_12_α
icn_10_β:
    mov     qword [rbp-40], 1
    jmp     icn_12_α
icon_10_lstore:
    pop     rax
    mov     [rbp-32], rax
    cmp     qword [rbp-40], 0
    je      icn_11_α
    jmp     icn_11_β
icon_10_compute:
    pop     rax
    mov     rcx, [rbp-32]
    sub     rcx, rax
    push    rcx
    jmp     icon_9_init
    ; INT 2  id=13
icn_13_α:
    push    2
    jmp     icn_10_α
icn_13_β:
    jmp     icon_8_lb
icon_9_e1b:
    mov     qword [rel icon_9_e2seen], 0
    jmp     icn_13_β
icon_9_e2b:
    jmp     icn_10_β
icn_9_α:
    mov     qword [rel icon_9_e2seen], 0
    jmp     icn_13_α
icn_9_β:
    inc     qword [rel icn_9_I]
    jmp     icn_9_code
icon_9_init:
    pop     rax
    mov     [rel icon_9_bound], rax
    cmp     qword [rel icon_9_e2seen], 0
    jne     icon_9_init_e2adv
    pop     rax
    mov     [rel icon_9_e1cur], rax
    mov     [rel icn_9_I], rax
    mov     qword [rel icon_9_e2seen], 1
    jmp     icn_9_code
icon_9_init_e2adv:
    mov     rax, [rel icon_9_e1cur]
    mov     [rel icn_9_I], rax
    jmp     icn_9_code
icn_9_code:
    mov     rax, [rel icn_9_I]
    cmp     rax, [rel icon_9_bound]
    jg      icon_9_e2b
    push    rax
    jmp     icon_8_compute
    ; VAR i  id=14
icn_14_α:
    mov     rax, [rel icn_gvar_i]
    push    rax
    jmp     icon_8_lstore
icn_14_β:
    jmp     icon_4_else
icon_8_lb:
    jmp     icn_14_β
icn_8_α:
    mov     qword [rbp-24], 0
    jmp     icn_14_α
icn_8_β:
    mov     qword [rbp-24], 1
    jmp     icn_14_α
icon_8_lstore:
    pop     rax
    mov     [rbp-16], rax
    cmp     qword [rbp-24], 0
    je      icn_9_α
    jmp     icn_9_β
icon_8_compute:
    pop     rax
    mov     rcx, [rbp-16]
    xchg    rax, rcx
    cqo
    idiv    rcx
    mov     rcx, rdx
    push    rcx
    jmp     icon_6_lstore
icon_6_lb:
    jmp     icn_8_β
icn_6_α:
    jmp     icn_8_α
icn_6_β:
    jmp     icn_7_β
icon_6_lstore:
    pop     rax
    mov     [rbp-8], rax
    jmp     icn_7_α
icon_6_check:
    pop     rcx
    mov     rax, [rbp-8]
    cmp     rax, rcx
    jne      icn_7_β
    push    rcx
    jmp     icon_4_then
icon_4_then:
    add     rsp, 8
    jmp     icn_5_α
icon_4_else:
    jmp     icon_0_genb
icn_4_α:
    jmp     icn_6_α
icn_4_β:
    jmp     icn_6_β
icon_1_seq_0:
    add     rsp, 8
    jmp     icn_2_α
icn_1_α:
    jmp     icn_4_α
icn_1_β:
    jmp     icon_0_genb
    ; TO  id=16
    ; INT 100  id=17
icn_17_α:
    push    100
    jmp     icon_16_init
icn_17_β:
    jmp     icon_16_e1b
    ; INT 2  id=18
icn_18_α:
    push    2
    jmp     icn_17_α
icn_18_β:
    jmp     icn_main_done
icon_16_e1b:
    mov     qword [rel icon_16_e2seen], 0
    jmp     icn_18_β
icon_16_e2b:
    jmp     icn_17_β
icn_16_α:
    mov     qword [rel icon_16_e2seen], 0
    jmp     icn_18_α
icn_16_β:
    inc     qword [rel icn_16_I]
    jmp     icn_16_code
icon_16_init:
    pop     rax
    mov     [rel icon_16_bound], rax
    cmp     qword [rel icon_16_e2seen], 0
    jne     icon_16_init_e2adv
    pop     rax
    mov     [rel icon_16_e1cur], rax
    mov     [rel icn_16_I], rax
    mov     qword [rel icon_16_e2seen], 1
    jmp     icn_16_code
icon_16_init_e2adv:
    mov     rax, [rel icon_16_e1cur]
    mov     [rel icn_16_I], rax
    jmp     icn_16_code
icn_16_code:
    mov     rax, [rel icn_16_I]
    cmp     rax, [rel icon_16_bound]
    jg      icon_16_e2b
    push    rax
    jmp     icon_15_store
icn_15_α:
    jmp     icn_16_α
icn_15_β:
    jmp     icn_16_β
icon_15_store:
    pop     rax
    mov     [rel icn_gvar_i], rax
    jmp     icon_0_body
icon_0_body:
    jmp     icn_1_α
icon_0_genb:
    jmp     icn_15_β
icn_0_α:
    jmp     icn_15_α
icn_0_β:
    jmp     icn_main_done
icn_main:
    push    rbp
    mov     rbp, rsp
    sub     rsp, 48
    jmp     icn_0_α
icn_main_done:
    mov     byte [rel icn_failed], 1
    add     rsp, 48
    pop     rbp
    ret
