; Auto-generated by icon_emit.c — Tiny-ICON Byrd Box x64
bits 64
default rel

section .rodata
icn_str_0:  db  100, 111, 110, 101, 0
icn_str_1:  db  110, 111, 112, 101, 0
icn_str_2:  db  97, 98, 99, 0
icn_str_3:  db  98, 99, 100, 0
icn_str_4:  db  108, 101, 115, 115, 0
icn_str_5:  db  98, 99, 100, 0
icn_str_6:  db  97, 98, 99, 0

section .bss
    icn_retval: resq 1
    icn_failed: resb 1
    icn_suspended: resb 1
    icn_suspend_resume: resq 1
    icn_suspend_rbp: resq 1

section .text
    global _start
    extern icn_write_int
    extern icn_write_str
    extern icn_push
    extern icn_pop
    extern icn_str_concat
    extern icn_str_eq
    extern icn_any
    extern icn_many
    extern icn_upto
    extern icn_str_find
    extern icn_match
    extern icn_tab
    extern icn_move
    extern icn_subject
    extern icn_pos
    extern icn_str_cmp
    extern icn_strlen
    extern icn_pow
    extern icn_str_subscript
    extern icn_str_section
    extern icn_bang_char_at
    extern icn_match_pat
    extern icn_cset_complement
    extern icn_cset_union
    extern icn_cset_diff
    extern icn_cset_inter

_start:
    call    icn_main
    mov     rax, 60
    xor     rdi, rdi
    syscall


; === procedure main ===
    ; CALL write  id=0
icn_1_α:
    lea     rdi, [rel icn_str_0]
    jmp     icon_0_call
icn_1_β:
    jmp     icn_main_done
icn_0_α:
    jmp     icn_1_α
icn_0_β:
    jmp     icn_1_β
icon_0_call:
    call    icn_write_str
    jmp     icn_main_done
    ; CALL write  id=3
icn_4_α:
    lea     rdi, [rel icn_str_1]
    jmp     icon_3_call
icn_4_β:
    jmp     icn_0_α
icn_3_α:
    jmp     icn_4_α
icn_3_β:
    jmp     icn_4_β
icon_3_call:
    call    icn_write_str
    jmp     icn_0_α
icn_6_α:
    lea     rdi, [rel icn_str_2]
    jmp     icon_5_sr_gr
icn_6_β:
    jmp     icon_2_else
icn_7_α:
    lea     rdi, [rel icn_str_3]
    jmp     icon_5_sr_gl
icn_7_β:
    jmp     icon_2_else
icn_5_α:
    jmp     icn_7_α
icn_5_β:
    jmp     icn_6_β
icon_5_sr_gr:
    pop     rax
    mov     [rbp-8], rax
    jmp     icn_7_α
icon_5_sr_gl:
    pop     rdi
    mov     rsi, [rbp-8]
    call    icn_str_cmp
    test    eax, eax
    jge     icon_2_else
    push    qword [rbp-8]
    jmp     icon_2_then
icon_2_then:
    add     rsp, 8
    jmp     icn_3_α
icon_2_else:
    jmp     icn_0_α
icn_2_α:
    jmp     icn_5_α
icn_2_β:
    jmp     icn_5_β
    ; CALL write  id=9
icn_10_α:
    lea     rdi, [rel icn_str_4]
    jmp     icon_9_call
icn_10_β:
    jmp     icn_2_α
icn_9_α:
    jmp     icn_10_α
icn_9_β:
    jmp     icn_10_β
icon_9_call:
    call    icn_write_str
    jmp     icn_2_α
icn_12_α:
    lea     rdi, [rel icn_str_5]
    jmp     icon_11_sr_gr
icn_12_β:
    jmp     icon_8_else
icn_13_α:
    lea     rdi, [rel icn_str_6]
    jmp     icon_11_sr_gl
icn_13_β:
    jmp     icon_8_else
icn_11_α:
    jmp     icn_13_α
icn_11_β:
    jmp     icn_12_β
icon_11_sr_gr:
    pop     rax
    mov     [rbp-16], rax
    jmp     icn_13_α
icon_11_sr_gl:
    pop     rdi
    mov     rsi, [rbp-16]
    call    icn_str_cmp
    test    eax, eax
    jge     icon_8_else
    push    qword [rbp-16]
    jmp     icon_8_then
icon_8_then:
    add     rsp, 8
    jmp     icn_9_α
icon_8_else:
    jmp     icn_2_α
icn_8_α:
    jmp     icn_11_α
icn_8_β:
    jmp     icn_11_β
icn_main:
    push    rbp
    mov     rbp, rsp
    sub     rsp, 32
    jmp     icn_8_α
icn_main_done:
    mov     byte [rel icn_failed], 1
    add     rsp, 32
    pop     rbp
    ret
