; generated by scrip-cc -asm (program mode)
; link: gcc -no-pie out.s stmt_rt.o snobol4.o mock_includes.o
;             snobol4_pattern.o engine.o -lgc -lm -o prog
%include "snobol4_asm.mac"
global  main
extern  stmt_init, stmt_strval, stmt_intval
extern  VARVAL_fn, to_int
extern  stmt_realval, stmt_set_null, stmt_set_indirect, stmt_get_indirect, stmt_nreturn_deref
extern  stmt_get, stmt_set, stmt_output, stmt_input
extern  stmt_concat, stmt_is_fail, stmt_finish
extern  stmt_realval, stmt_set_null, stmt_set_indirect
extern  stmt_apply, stmt_goto_dispatch
extern  exec_code
extern  stmt_setup_subject, stmt_apply_replacement
extern  stmt_apply_replacement_splice
extern  stmt_set_capture, stmt_match_var, stmt_match_descr
extern  stmt_pos_var, stmt_rpos_var
extern  stmt_save_subject, stmt_restore_subject
extern  stmt_span_var, stmt_break_var
extern  stmt_breakx_var, stmt_breakx_lit
extern  stmt_any_var, stmt_notany_var, stmt_any_ptr
extern  stmt_break_ptr, stmt_span_ptr
extern  stmt_at_capture
extern  exec_stmt
extern  pat_lit, pat_cat, pat_alt, pat_span, pat_break_, pat_breakx
extern  pat_any_cs, pat_notany, pat_len, pat_pos, pat_rpos
extern  pat_tab, pat_rtab, pat_arb, pat_arbno, pat_rem
extern  pat_fence, pat_fence_p, pat_fail, pat_succeed
extern  pat_abort, pat_bal, pat_ref, pat_ref_val
extern  pat_assign_imm, pat_assign_cond, pat_epsilon
extern  pat_at_cursor
extern  kw_anchor
extern  stmt_aref, stmt_aset, stmt_field_set
extern  stmt_aref2, stmt_aset2
extern  comm_stno
extern  blk_alloc, blk_free, memcpy  ; per-invocation DATA block runtime
extern  pat_ref  ; B-287: deferred *VAR pattern ref (XDSAR)
global  cursor, subject_data, subject_len_val

section .note.GNU-stack noalloc noexec nowrite progbits
section .bss
cursor                   resq 1
subject_len_val          resq 1
scan_start_5             resq 1
rpat0_t                  resq 1
rpat0_p                  resq 1
rpat0_s                  resq 1
conc_tmp0_rax            resq 1
conc_tmp0_rdx            resq 1
subject_data             resb 65536


section .text
main:
;  PROGRAM BODY ========================================================================================================
                            PROG_INIT

; ======================================================================================================================
                            mov         edi, 5
                            call        comm_stno
                            ASSIGN_INT  S_TRIM, 1, Ln_0
                            jmp         Ln_0

; ======================================================================================================================
Ln_0:                       mov         edi, 6
                            call        comm_stno
                            ASSIGN_STR  S_NUMERALS, S_0123456789, Ln_1
                            jmp         Ln_1

; ======================================================================================================================
Ln_1:                       mov         edi, 7
                            call        comm_stno
                            LOAD_STR    S_XX_MI
                            push        rdx
                            push        rax
                            lea         rdi, [rel S_NUMERALS]
                            call        stmt_get
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            mov         rcx, rdx
                            mov         rdx, rax
                            pop         rdi
                            pop         rsi
                            call        stmt_concat
                            push        rdx
                            push        rax
                            lea         rdi, [rel S_UCASE]
                            call        stmt_get
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            mov         rcx, rdx
                            mov         rdx, rax
                            pop         rdi
                            pop         rsi
                            call        stmt_concat
                            push        rdx
                            push        rax
                            lea         rdi, [rel S_LCASE]
                            call        stmt_get
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            mov         rcx, rdx
                            mov         rdx, rax
                            pop         rdi
                            pop         rsi
                            call        stmt_concat
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            FAIL_BR     Ln_2
                            SET_VAR     S_WORD
                            jmp         Ln_2

; ======================================================================================================================
Ln_2:                       mov         edi, 8
                            call        comm_stno
                            CALL1_VAR   S_BREAK, S_WORD
                            push        rdx
                            push        rax
                            CALL1_VAR   S_SPAN, S_WORD
                            mov         rcx, rdx
                            mov         rdx, rax
                            pop         rdi
                            pop         rsi
                            call        stmt_concat
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            FAIL_BR     Ln_3
                            SET_VAR     S_WPAT
                            jmp         Ln_3

Ln_3:
;  NEXTL ===============================================================================================================
L_NEXTL_0:                  mov         edi, 9
                            call        comm_stno
                            lea         rdi, [rel S_INPUT]
                            call        stmt_get
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            FAIL_BR     Lf_4
                            SET_VAR     S_LINE
                            jmp         Ln_4
Lf_4:                       jmp         L_DONE_1

Ln_4:
;  NEXTW ===============================================================================================================
L_NEXTW_2:                  mov         edi, 10
                            call        comm_stno
                            sub         rsp, 48
                            lea         rdi, [rel S_LINE]
                            xor         esi, esi
                            mov         [rsp+32], rdi
                            mov         [rsp+40], rsi
                            lea         rdi, [rel S_WPAT]
                            call        pat_ref
                            mov         [rsp+16], rax
                            mov         [rsp+24], rdx
                            mov         rdi, [rsp+32]
                            mov         rsi, [rsp+40]
                            mov         rdx, [rsp+16]
                            mov         rcx, [rsp+24]
                            mov         qword [rsp+0], 0
                            mov         qword [rsp+8], 0
                            lea         r8, [rsp+0]
                            mov         r9d, 1
                            call        exec_stmt
                            add         rsp, 48
                            test        eax, eax
                            jnz         dyn_done_5
                            jmp         L_NEXTL_0
dyn_done_5:
                            jmp         Ln_5

; ======================================================================================================================
Ln_5:                       mov         edi, 11
                            call        comm_stno
                            CONC2_VI    S_add, S_N, 1
                            FAIL_BR     Lf_6
                            SET_VAR     S_N
                            jmp         L_NEXTW_2
Lf_6:                       jmp         L_NEXTW_2

Ln_6:
;  DONE ================================================================================================================
L_DONE_1:                   mov         edi, 12
                            call        comm_stno
                            CALL1_VAR   S___num_pos, S_N
                            push        rdx
                            push        rax
                            LOAD_STR    S_SP_words
                            mov         rcx, rdx
                            mov         rdx, rax
                            pop         rdi
                            pop         rsi
                            call        stmt_concat
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            FAIL_BR     Ln_7
                            SET_OUTPUT
                            jmp         Ln_7
Ln_7:                       GOTO_ALWAYS L_SNO_END

L_SNO_END:
;  END =================================================================================================================
                            PROG_END

section .text
;  NAMED PATTERN BODIES ================================================================================================

section .text
;  STUB LABELS =========================================================================================================

section .rodata
; (no named pattern boxes in this program)
;  BOX RELOCATION TABLES ===============================================================================================

section .data
S_TRIM               db 84, 82, 73, 77, 0  ; "TRIM"
S_NUMERALS           db 78, 85, 77, 69, 82, 65, 76, 83, 0  ; "NUMERALS"
S_0123456789         db 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 0  ; "0123456789"
S_WORD               db 87, 79, 82, 68, 0  ; "WORD"
S_LCASE              db 76, 67, 65, 83, 69, 0  ; "LCASE"
S_UCASE              db 85, 67, 65, 83, 69, 0  ; "UCASE"
S_XX_MI              db 39, 45, 0  ; "'-"
S_WPAT               db 87, 80, 65, 84, 0  ; "WPAT"
S_SPAN               db 83, 80, 65, 78, 0  ; "SPAN"
S_BREAK              db 66, 82, 69, 65, 75, 0  ; "BREAK"
S_NEXTL              db 78, 69, 88, 84, 76, 0  ; "NEXTL"
S_LINE               db 76, 73, 78, 69, 0  ; "LINE"
S_INPUT              db 73, 78, 80, 85, 84, 0  ; "INPUT"
S_NEXTW              db 78, 69, 88, 84, 87, 0  ; "NEXTW"
S_N                  db 78, 0  ; "N"
S_DONE               db 68, 79, 78, 69, 0  ; "DONE"
S_OUTPUT             db 79, 85, 84, 80, 85, 84, 0  ; "OUTPUT"
S_SP_words           db 32, 119, 111, 114, 100, 115, 0  ; " words"
S_END                db 69, 78, 68, 0  ; "END"
S_add                db 97, 100, 100, 0  ; "add"
S___num_pos          db 95, 95, 110, 117, 109, 95, 112, 111, 115, 0  ; "__num_pos"
