% char_io_driver.pl -- grades GNU Prolog's BipsPl/char_io.pl through the predicates it defines (Lon via the ceo, CEO-1523: every
% Prolog source file of the GNU package is graded through a driver; CEO-700, CEO-1269: a library is graded by its driver,
% NAME_driver beside it). gprolog's answer is char_io.pl's own code; SCRIP is graded three-way against it (m3 = m4 = gprolog).
% Every predicate is called in a mode GNU Prolog's manual documents; an error prints as its ISO formal term only.
% Streams are opened in setup steps (not graded) under an alias, so no stream-term is printed; files live only under
% /tmp/gnu_drv_char_io_K. The 1-arity forms run on a file made the current input/output by set_input/1 / set_output/1
% (ISO), and the current output is restored to user_output after each one. get_key/1,2 and get_key_no_echo/1,2 are driven
% only on a file stream: the manual documents that on a stream not attached to a terminal they return the code of the
% first character and pump the rest of the line up to a character < space, with no echo -- deterministic, no terminal read.
:- initialization(main).

% t(G): every solution of G, or the formal error term G raises.
t(G) :- copy_term(G, C),
        catch(findall(C, C, L), E, true),
        (   var(E) -> R = L
        ;   E = error(F, _) -> R = error(F)
        ;   R = ball(E)
        ),
        \+ \+ ( numbervars(G-R, 0, _), writeq(G), write(' => '), writeq(R), nl ).

% o(G): for a goal whose effect is OUTPUT -- what it printed between < and >, then true, fail or the formal error term.
o(G) :- write('<'),
        catch(( G -> R = true ; R = fail ), E, ( E = error(F, _) -> R = error(F) ; R = ball(E) )),
        write('> '), writeq(R), nl.

main :-
    catch(( open('/tmp/gnu_drv_char_io_1.txt', write, W1), write(W1, 'ab\nc'), close(W1) ), _, true),
    catch(( open('/tmp/gnu_drv_char_io_4.txt', write, W4), write(W4, 'xyz\nqr\n'), close(W4) ), _, true),
    catch(open('/tmp/gnu_drv_char_io_1.txt', read, _, [alias(ci_r)]), _, true),
    catch(open('/tmp/gnu_drv_char_io_3.txt', write, _, [alias(ci_w)]), _, true),
    catch(open('/tmp/gnu_drv_char_io_2.bin', write, _, [type(binary), alias(ci_wb)]), _, true),
    % get_char/2, get_code/2, peek_char/2, peek_code/2 on the text 'ab\nc', through end of file
    t(peek_char(ci_r, _)),
    t(peek_char(ci_r, z)),
    t(get_char(ci_r, _)),
    t(get_char(ci_r, b)),
    t(peek_code(ci_r, _)),
    t(get_code(ci_r, _)),
    t(get_code(ci_r, 0'x)),
    t(peek_char(ci_r, _)),
    t(peek_code(ci_r, _)),
    t(get_char(ci_r, _)),
    t(get_code(ci_r, _)),
    t(get_char(ci_r, 1)),
    t(get_char(ci_r, ab)),
    t(get_code(ci_r, a)),
    t(get_code(ci_r, -5)),
    t(peek_char(ci_r, 1)),
    t(peek_code(ci_r, a)),
    t(peek_code(ci_r, -2)),
    t(get_char(_, _)),
    t(get_char(nosuch, _)),
    t(get_char(1, _)),
    t(get_char(ci_w, _)),
    t(get_code(ci_wb, _)),
    t(peek_char(ci_w, _)),
    t(peek_code(_, _)),
    % unget_char/2, unget_code/2 on a fresh stream, then the past-end-of-stream error under eof_action(error)
    catch(open('/tmp/gnu_drv_char_io_1.txt', read, _, [alias(ci_u), eof_action(error)]), _, true),
    t(unget_char(ci_u, z)),
    t((get_char(ci_u, C1), get_char(ci_u, C2))),
    t(unget_code(ci_u, 0'y)),
    t((get_code(ci_u, _K1), get_code(ci_u, _K2))),
    t(unget_char(ci_u, ab)),
    t(unget_char(ci_u, end_of_file)),
    t(unget_char(ci_u, _)),
    t(unget_code(ci_u, a)),
    t(unget_code(ci_u, -3)),
    t(unget_char(ci_w, a)),
    t(unget_code(_, 97)),
    t((get_char(ci_u, C1), get_char(ci_u, C2))),
    t(get_char(ci_u, _)),
    t(peek_code(ci_u, _)),
    % put_char/2, put_code/2 on a text sink, read back below
    t(put_char(ci_w, h)),
    t(put_code(ci_w, 0'i)),
    t(put_char(ci_w, '\n')),
    t(put_char(ci_w, ab)),
    t(put_char(ci_w, end_of_file)),
    t(put_char(ci_w, _)),
    t(put_code(ci_w, a)),
    t(put_code(ci_w, -1)),
    t(put_code(_, 97)),
    t(put_char(ci_r, a)),
    t(put_code(nosuch, 97)),
    t(put_char(ci_wb, a)),
    % the byte forms on a binary sink and source
    t(put_byte(ci_wb, 1)),
    t(put_byte(ci_wb, 200)),
    t(put_byte(ci_wb, 256)),
    t(put_byte(ci_wb, a)),
    t(put_byte(ci_wb, _)),
    t(put_byte(ci_w, 1)),
    t(put_byte(ci_r, 1)),
    % the 1-arity output forms: the current output is the sink for one goal
    t((set_output(ci_w), put_char(j), put_code(0'k), set_output(user_output))),
    catch(set_output(user_output), _, true),
    t((set_output(ci_wb), put_byte(255), set_output(user_output))),
    catch(set_output(user_output), _, true),
    t((set_output(ci_w), put_char(1), set_output(user_output))),
    catch(set_output(user_output), _, true),
    catch(close(ci_w), _, true),
    catch(close(ci_wb), _, true),
    catch(open('/tmp/gnu_drv_char_io_3.txt', read, _, [alias(ci_r3)]), _, true),
    t((get_char(ci_r3, _A1), get_char(ci_r3, _A2), get_char(ci_r3, _A3), get_char(ci_r3, _A4), get_char(ci_r3, _A5), get_char(ci_r3, _A6))),
    catch(open('/tmp/gnu_drv_char_io_2.bin', read, _, [type(binary), alias(ci_rb)]), _, true),
    t(peek_byte(ci_rb, _)),
    t(peek_byte(ci_rb, 7)),
    t(get_byte(ci_rb, _)),
    t(unget_byte(ci_rb, 9)),
    t((get_byte(ci_rb, _B1), get_byte(ci_rb, _B2), get_byte(ci_rb, _B3))),
    t(peek_byte(ci_rb, _)),
    t(get_byte(ci_rb, _)),
    t(get_byte(ci_rb, a)),
    t(get_byte(ci_rb, 256)),
    t(peek_byte(ci_rb, -2)),
    t(unget_byte(ci_rb, 256)),
    t(unget_byte(ci_rb, _)),
    t(get_byte(ci_r, _)),
    t(peek_byte(ci_r, _)),
    t(unget_byte(ci_r, 1)),
    t(get_char(ci_rb, _)),
    t(get_byte(_, _)),
    % the 1-arity input forms: the current input is a file for a run of goals
    catch(open('/tmp/gnu_drv_char_io_1.txt', read, _, [alias(ci_i)]), _, true),
    catch(set_input(ci_i), _, true),
    t(peek_char(_)),
    t(get_char(_)),
    t(peek_code(_)),
    t(get_code(_)),
    t(unget_char(q)),
    t(get_char(_)),
    t(unget_code(0'w)),
    t(get_code(_)),
    t(get_char(1)),
    t(unget_char(_)),
    t(get_byte(_)),
    catch(set_input(user_input), _, true),
    catch(open('/tmp/gnu_drv_char_io_2.bin', read, _, [type(binary), alias(ci_ib)]), _, true),
    catch(set_input(ci_ib), _, true),
    t(peek_byte(_)),
    t(get_byte(_)),
    t(unget_byte(5)),
    t(get_byte(_)),
    t(unget_byte(a)),
    t(get_char(_)),
    catch(set_input(user_input), _, true),
    % get_key/2, get_key_no_echo/2 and the 1-arity forms on a file stream (the manual's non-terminal behaviour)
    catch(open('/tmp/gnu_drv_char_io_4.txt', read, _, [alias(ci_k)]), _, true),
    t(get_key(ci_k, _)),
    t(get_key_no_echo(ci_k, _)),
    t(get_key(ci_k, _)),
    t(get_key(ci_k, a)),
    t(get_key(_, _)),
    t(get_key_no_echo(ci_wb, _)),
    t(get_key_no_echo(nosuch, _)),
    catch(open('/tmp/gnu_drv_char_io_4.txt', read, _, [alias(ci_k2)]), _, true),
    catch(set_input(ci_k2), _, true),
    t(get_key(_)),
    t(get_key_no_echo(_)),
    t(get_key(_)),
    t(get_key_no_echo(a)),
    catch(set_input(user_input), _, true),
    catch(close(ci_r), _, true), catch(close(ci_u), _, true), catch(close(ci_r3), _, true),
    catch(close(ci_rb), _, true), catch(close(ci_i), _, true), catch(close(ci_ib), _, true),
    catch(close(ci_k), _, true), catch(close(ci_k2), _, true),
    catch(delete_file('/tmp/gnu_drv_char_io_1.txt'), _, true),
    catch(delete_file('/tmp/gnu_drv_char_io_2.bin'), _, true),
    catch(delete_file('/tmp/gnu_drv_char_io_3.txt'), _, true),
    catch(delete_file('/tmp/gnu_drv_char_io_4.txt'), _, true),
    true.
