% read_driver.pl -- grades GNU Prolog's BipsPl/read.pl through the predicates it defines (Lon via the ceo, CEO-1523: every
% Prolog source file of the GNU package is graded through a driver; CEO-700, CEO-1269: a library is graded by its driver,
% read_driver beside it). gprolog's answer is read.pl's own code; SCRIP is graded three-way against it (m3 = m4 = gprolog).
% Every predicate is called in a mode GNU Prolog's manual documents; an error prints as its ISO formal term only.
% stdin is /dev/null, so every read is from a file main writes first under /tmp with ISO open/3 and opens again by alias
% (rd1 terms, rd2 tokens, rd3 syntax errors); the /0-1 forms read the current input after set_input/1 names that alias.
% A syntax error prints its formal term, GNU's message atom included; each file is deleted as soon as it is closed.
:- initialization(main).

% t(G): every solution of G, or the formal error term G raises.
t(G) :- copy_term(G, C),
        catch(findall(C, C, L), E, true),
        (   var(E) -> R = L
        ;   E = error(F, _) -> R = error(F)
        ;   R = ball(E)
        ),
        \+ \+ ( numbervars(G-R, 0, _), writeq(G), write(' => '), writeq(R), nl ).

% o(G): for a goal whose effect is OUTPUT -- what it printed between < and >, then true, fail or the formal error term.
o(G) :- write('<'),
        catch(( G -> R = true ; R = fail ), E, ( E = error(F, _) -> R = error(F) ; R = ball(E) )),
        write('> '), writeq(R), nl.

main :-
    open('/tmp/gnu_drv_read_1.txt', write, W1),
    write(W1, 'foo(X, Y, X).\n[1, 2|T].\n  f(A, _B, C, A).\n''hello world''.\ng(x) .\nh(Z).\nk(1).\nlast.\n'),
    close(W1),
    open('/tmp/gnu_drv_read_1.txt', read, _, [alias(rd1)]),
    t(read(rd1, _)),
    t(last_read_start_line_column(_, _)),
    t(read(rd1, [1,2|_])),
    t(read_term(rd1, _, [variable_names(_), singletons(_)])),
    t(last_read_start_line_column(_, _)),
    t(read_term(rd1, _, [variables(_)])),
    t(read(rd1, foo)),
    set_input(rd1),
    t(read(_)),
    t(read_term(_, [variable_names(_)])),
    set_input(user_input),
    t(read_term(rd1, _, [bad])),
    t(read_term(rd1, _, foo)),
    t(read_term(rd1, _, _)),
    t(read(rd1, _)),
    t(read(rd1, _)),
    close(rd1),
    catch(delete_file('/tmp/gnu_drv_read_1.txt'), _, true),
    t(read(nosuch, _)),
    t(read(user_output, _)),
    t(read(_, _)),
    open('/tmp/gnu_drv_read_2.txt', write, W2),
    write(W2, 'hello ''quoted atom'' 42 -17 3.5 0''a abc 7 foo(X, "str", [a], 2.5e3) .\n'),
    close(W2),
    open('/tmp/gnu_drv_read_2.txt', read, _, [alias(rd2)]),
    t(read_atom(rd2, _)),
    t(read_atom(rd2, _)),
    t(read_integer(rd2, _)),
    t(read_integer(rd2, _)),
    t(read_number(rd2, _)),
    t(read_number(rd2, _)),
    t(read_integer(rd2, _)),
    t(read_atom(rd2, 7)),
    set_input(rd2),
    t(read_atom(_)),
    t(read_integer(_)),
    t(read_token(_)),
    set_input(user_input),
    t(read_token(rd2, _)),
    t(read_token(rd2, _)),
    t(read_token(rd2, _)),
    t(read_token(rd2, _)),
    t(read_token(rd2, _)),
    t(read_token(rd2, _)),
    t(read_token(rd2, _)),
    t(read_token(rd2, _)),
    t(read_token(rd2, _)),
    t(read_token(rd2, _)),
    t(read_token(rd2, _)),
    t(read_token(rd2, _)),
    t(read_token(rd2, _)),
    close(rd2),
    catch(delete_file('/tmp/gnu_drv_read_2.txt'), _, true),
    t(read_atom(nosuch, _)),
    t(read_number(_, _)),
    open('/tmp/gnu_drv_read_3.txt', write, W3),
    write(W3, 'bad( .\nok(1).\nbad2 ) .\nok(2).\nfoo bar.\nok(3).\n'),
    close(W3),
    open('/tmp/gnu_drv_read_3.txt', read, _, [alias(rd3)]),
    t(read(rd3, _)),
    t(read(rd3, _)),
    t(read_term(rd3, _, [syntax_error(fail)])),
    t(read(rd3, _)),
    t(read_term(rd3, _, [syntax_error(error)])),
    t(read(rd3, _)),
    close(rd3),
    catch(delete_file('/tmp/gnu_drv_read_3.txt'), _, true),
    t(current_char_conversion(_, _)),
    t(char_conversion(a, b)),
    t(current_char_conversion(_, _)),
    t(current_char_conversion(a, _)),
    t(char_conversion(a, a)),
    t(current_char_conversion(_, _)),
    t(char_conversion(ab, c)),
    t(char_conversion(_, c)),
    true.
