% stream_driver.pl -- grades GNU Prolog's BipsPl/stream.pl through the predicates it defines (Lon via the ceo, CEO-1523: every
% Prolog source file of the GNU package is graded through a driver; CEO-700, CEO-1269: a library is graded by its driver,
% NAME_driver beside it). gprolog's answer is stream.pl's own code; SCRIP is graded three-way against it (m3 = m4 = gprolog).
% Every predicate is called in a mode GNU Prolog's manual documents; an error prints as its ISO formal term only.
% A stream-term '$stream'(N) is numbered differently by every system, so it is never printed: main opens each stream
% under an alias (a setup step, not graded) and every graded goal names the alias; a predicate that RETURNS a stream-term
% (current_input/1, current_output/1, current_stream/1, current_alias/2, current_mirror/2, the stream-term binding of
% stream_property/2 and of the open predicates) is graded by property inside \+ \+, which prints success, failure or the
% error without the term. A stream position is likewise compared, never printed. Files live only under /tmp/gnu_drv_stream_K.
% NOT DRIVEN: set_stream_alias/2 -- absent from the gprolog 1.4.5 oracle (existence_error(procedure,set_stream_alias/2)); the vendored stream.pl is newer than the oracle
:- initialization(main).

% t(G): every solution of G, or the formal error term G raises.
t(G) :- copy_term(G, C),
        catch(findall(C, C, L), E, true),
        (   var(E) -> R = L
        ;   E = error(F, _) -> R = error(F)
        ;   R = ball(E)
        ),
        \+ \+ ( numbervars(G-R, 0, _), writeq(G), write(' => '), writeq(R), nl ).

% o(G): for a goal whose effect is OUTPUT -- what it printed between < and >, then true, fail or the formal error term.
o(G) :- write('<'),
        catch(( G -> R = true ; R = fail ), E, ( E = error(F, _) -> R = error(F) ; R = ball(E) )),
        write('> '), writeq(R), nl.

main :-
    catch(( open('/tmp/gnu_drv_stream_1.txt', write, W0), write(W0, 'ab\ncd\n'), close(W0) ), _, true),
    % open/3 and open/4: the errors the manual lists, then a success graded by property
    t(open(_, read, _)),
    t(open('/tmp/gnu_drv_stream_1.txt', rd, _)),
    t(open('/tmp/gnu_drv_stream_9.txt', read, _)),
    t(open('/tmp/gnu_drv_stream_1.txt', read, s)),
    t(open(f(x), read, _)),
    t(\+ \+ (open('/tmp/gnu_drv_stream_1.txt', read, S), stream_property(S, mode(read)), close(S))),
    t(open('/tmp/gnu_drv_stream_1.txt', read, _, foo)),
    t(open('/tmp/gnu_drv_stream_1.txt', read, _, [bogus(1)])),
    t(open('/tmp/gnu_drv_stream_1.txt', read, _, [mirror(nosuch)])),
    catch(open('/tmp/gnu_drv_stream_1.txt', read, _, [alias(drv_r)]), _, true),
    catch(open('/tmp/gnu_drv_stream_2.txt', write, _, [alias(drv_w)]), _, true),
    catch(open('/tmp/gnu_drv_stream_3.txt', write, _, [alias(drv_m)]), _, true),
    catch(open('/tmp/gnu_drv_stream_1.txt', read, _, [type(binary), alias(drv_b)]), _, true),
    catch(open('/tmp/gnu_drv_stream_1.txt', read, _, [alias(drv_np), reposition(false), eof_action(error), buffering(none)]), _, true),
    t(open('/tmp/gnu_drv_stream_1.txt', read, _, [alias(drv_r)])),
    t(open('/tmp/gnu_drv_stream_1.txt', read, _, [mirror(drv_r)])),
    % stream_property/2 on the streams opened above
    t(\+ \+ (stream_property(S, alias(drv_r)), stream_property(S, mode(read)))),
    t(\+ \+ (stream_property(S, alias(drv_r)), stream_property(S, output))),
    t(\+ \+ (stream_property(S, alias(drv_r)), stream_property(S, file_name('/tmp/gnu_drv_stream_1.txt')))),
    t(\+ \+ (stream_property(S, alias(drv_r)), stream_property(S, type(text)))),
    t(\+ \+ (stream_property(S, alias(drv_r)), stream_property(S, reposition(true)))),
    t(\+ \+ (stream_property(S, alias(drv_r)), stream_property(S, eof_action(eof_code)))),
    t(\+ \+ (stream_property(S, alias(drv_r)), stream_property(S, buffering(block)))),
    t(\+ \+ (stream_property(S, alias(drv_r)), stream_property(S, end_of_stream(not)))),
    t(\+ \+ (stream_property(S, alias(drv_w)), stream_property(S, mode(write)), stream_property(S, output))),
    t(\+ \+ (stream_property(S, alias(drv_np)), stream_property(S, reposition(false)))),
    t(\+ \+ (stream_property(S, alias(drv_np)), stream_property(S, eof_action(error)))),
    t(stream_property(_, alias(nosuch))),
    t(stream_property(foo, _)),
    t(stream_property(_, bogus)),
    % reading drv_r: the counters, stream_position/2, set_stream_position/2, set_stream_line_column/3, the end of stream
    t((character_count(drv_r, N), line_count(drv_r, L), line_position(drv_r, P))),
    t(at_end_of_stream(drv_r)),
    t(\+ \+ (stream_position(drv_r, P), P = '$stream_position'(_, _, _, _))),
    t((stream_line_column(drv_r, L, _C), get_char(drv_r, X), get_char(drv_r, Y), get_char(drv_r, Z), stream_line_column(drv_r, _L2, _C2))),
    t((character_count(drv_r, N), line_count(drv_r, L), line_position(drv_r, P))),
    t(\+ \+ (stream_position(drv_r, P), get_char(drv_r, c), set_stream_position(drv_r, P), get_char(drv_r, c))),
    t(set_stream_line_column(drv_r, 1, 2)),
    t((line_count(drv_r, L), line_position(drv_r, P), get_char(drv_r, X))),
    t(set_stream_line_column(drv_r, 2, 1)),
    t((character_count(drv_r, N), get_char(drv_r, _X1), get_char(drv_r, _X2), get_char(drv_r, _X3))),
    t(at_end_of_stream(drv_r)),
    t(\+ \+ (stream_property(S, alias(drv_r)), stream_property(S, end_of_stream(at)))),
    t((character_count(drv_r, N), get_char(drv_r, X))),
    t(\+ \+ (stream_property(S, alias(drv_r)), stream_property(S, end_of_stream(past)))),
    t(set_stream_eof_action(drv_r, error)),
    t((character_count(drv_r, N), get_char(drv_r, X))),
    t(set_stream_eof_action(drv_r, foo)),
    t(set_stream_eof_action(drv_r, _)),
    t(set_stream_eof_action(drv_w, error)),
    t(character_count(drv_r, a)),
    t(line_count(_, _)),
    t(set_stream_line_column(drv_r, 1, a)),
    t(stream_position(drv_r, foo)),
    t(stream_position(_, _)),
    t(set_stream_position(drv_r, foo)),
    t((stream_position(drv_np, P), set_stream_position(drv_np, P))),
    t(set_stream_line_column(drv_np, 1, 1)),
    % seek/4 and the text-only counters on the binary stream drv_b
    t(seek(drv_b, bof, 2, N)),
    t((seek(drv_b, current, 1, N), get_byte(drv_b, _B))),
    t(seek(drv_b, eof, -1, N)),
    t(seek(drv_b, bof, 1, 2)),
    t(seek(drv_b, middle, 0, _)),
    t(seek(drv_b, 1, 0, _)),
    t(seek(drv_b, bof, a, _)),
    t(seek(drv_r, bof, 0, _)),
    t(line_count(drv_b, _)),
    t(stream_line_column(drv_b, _, _)),
    t(set_stream_line_column(drv_b, 1, 1)),
    % set_stream_type/2 and set_stream_buffering/2: before and after the first input/output
    catch(open('/tmp/gnu_drv_stream_1.txt', read, _, [alias(drv_t)]), _, true),
    t(set_stream_type(drv_t, binary)),
    t(\+ \+ (stream_property(S, alias(drv_t)), stream_property(S, type(binary)))),
    t(set_stream_type(drv_t, foo)),
    t(set_stream_type(drv_t, _)),
    t(set_stream_type(drv_r, binary)),
    t(set_stream_buffering(drv_w, line)),
    t(\+ \+ (stream_property(S, alias(drv_w)), stream_property(S, buffering(line)))),
    t(set_stream_buffering(drv_w, foo)),
    % aliases: add_stream_alias/2, current_alias/2
    t(add_stream_alias(drv_r, drv_r2)),
    t(\+ \+ (current_alias(S, drv_r), current_alias(S, drv_r2))),
    t(add_stream_alias(drv_w, drv_r2)),
    t(add_stream_alias(drv_r, 12)),
    t(current_alias(_, nosuch)),
    t(current_alias(foo, _)),
    t(current_alias(_, 12)),
    % mirrors: add_stream_mirror/2, current_mirror/2, remove_stream_mirror/2; the mirror file is read back below
    catch(open('/tmp/gnu_drv_stream_1.txt', read, _, [alias(drv_mr)]), _, true),
    t(add_stream_mirror(drv_mr, drv_m)),
    t(\+ \+ (current_alias(S, drv_mr), current_alias(M, drv_m), current_mirror(S, M))),
    t(\+ \+ (current_alias(S, drv_mr), stream_property(S, mirror(M)), current_alias(M, drv_m))),
    t((character_count(drv_mr, N), get_char(drv_mr, X), get_char(drv_mr, Y))),
    t(remove_stream_mirror(drv_mr, drv_m)),
    t(remove_stream_mirror(drv_mr, drv_m)),
    t(add_stream_mirror(drv_mr, drv_r)),
    t(add_stream_mirror(drv_mr, nosuch)),
    t(add_stream_mirror(_, drv_m)),
    t(current_mirror(foo, _)),
    % current_stream/1, current_input/1, current_output/1, set_input/1, set_output/1, at_end_of_stream/0, flush_output/0,1
    t(\+ \+ (current_alias(S, drv_r), current_stream(S))),
    t(current_stream('$stream'(9999))),
    t(current_stream(foo)),
    t(\+ \+ (current_output(S), current_alias(S, user_output))),
    t(current_input(foo)),
    t(current_output(user_output)),
    catch(open('/tmp/gnu_drv_stream_1.txt', read, _, [alias(drv_in)]), _, true),
    t(set_input(drv_in)),
    t(\+ \+ (current_input(S), current_alias(S, drv_in))),
    t((at_end_of_stream -> E = at ; E = not)),
    t(close(drv_in)),
    t(\+ \+ (current_input(S), current_alias(S, user_input))),
    t(set_input(_)),
    t(set_input(drv_w)),
    t(set_input(nosuch)),
    t((set_output(drv_w), write(hello), nl, flush_output, set_output(user_output))),
    t(\+ \+ (set_output(drv_w), current_output(S), set_output(user_output), current_alias(S, drv_w))),
    t(set_output(drv_r)),
    t(set_output(_)),
    t(flush_output),
    t(flush_output(drv_w)),
    t(flush_output(drv_r)),
    t(flush_output(_)),
    % constant term streams: open with a stream-term, aliased in setup, read and written through the alias
    catch(( open_input_atom_stream(abc, IA), add_stream_alias(IA, drv_ia) ), _, true),
    catch(( open_input_chars_stream([x, y], IC), add_stream_alias(IC, drv_ic) ), _, true),
    catch(( open_input_codes_stream([0'p, 0'q], ID), add_stream_alias(ID, drv_id) ), _, true),
    catch(( open_output_atom_stream(OA), add_stream_alias(OA, drv_oa) ), _, true),
    catch(( open_output_chars_stream(OC), add_stream_alias(OC, drv_oc) ), _, true),
    catch(( open_output_codes_stream(OD), add_stream_alias(OD, drv_od) ), _, true),
    t((character_count(drv_ia, N), get_char(drv_ia, X), get_char(drv_ia, Y))),
    t((line_count(drv_ic, L), get_char(drv_ic, X), get_char(drv_ic, Y), get_char(drv_ic, Z))),
    t(at_end_of_stream(drv_ic)),
    t((character_count(drv_id, N), get_code(drv_id, X))),
    t((character_count(drv_oa, _N0), write(drv_oa, hello), character_count(drv_oa, _N1))),
    t((line_count(drv_oc, L), write(drv_oc, hi))),
    t((line_position(drv_od, P), write(drv_od, ok))),
    t(close(drv_ia)),
    t(close_input_atom_stream(drv_r)),
    t(close_input_atom_stream(drv_oa)),
    t(close_output_atom_stream(drv_ia, _)),
    t(close_output_atom_stream(drv_r, _)),
    t(close_output_atom_stream(drv_oa, 12)),
    t(close_input_chars_stream(drv_oc)),
    t(close_output_codes_stream(drv_r, _)),
    t(close_input_codes_stream(nosuch)),
    t(close_input_atom_stream(drv_ia)),
    t(close_input_chars_stream(drv_ic)),
    t(close_input_codes_stream(drv_id)),
    t(close_output_atom_stream(drv_oa, _)),
    t(close_output_chars_stream(drv_oc, _)),
    t(close_output_codes_stream(drv_od, _)),
    t(close_output_atom_stream(drv_oa, _)),
    t(\+ \+ (open_input_atom_stream(z, S), close_input_atom_stream(S))),
    t(\+ \+ (open_output_chars_stream(S), close_output_chars_stream(S, []))),
    t(open_input_atom_stream(_, _)),
    t(open_input_atom_stream(f(x), _)),
    t(open_input_chars_stream(foo, _)),
    t(open_input_chars_stream([a, 1], _)),
    t(open_input_codes_stream([97, a], _)),
    t(open_input_codes_stream([-5], _)),
    t(open_output_atom_stream(s)),
    t(open_output_codes_stream(s)),
    t(\+ \+ (open_output_codes_stream(S), write(S, x), close_output_codes_stream(S, [0'x]))),
    % close/1 and close/2; then the files written through drv_w and the mirror drv_m are read back
    t(close(drv_np)),
    t(close(drv_np)),
    t(close(_)),
    t(close(user_output)),
    t(close(drv_b, [force(true)])),
    t(close(drv_r, [foo])),
    t(close(drv_r, bar)),
    catch(close(drv_w, []), _, true),
    catch(close(drv_m), _, true),
    catch(open('/tmp/gnu_drv_stream_2.txt', read, _, [alias(drv_w2)]), _, true),
    catch(open('/tmp/gnu_drv_stream_3.txt', read, _, [alias(drv_m2)]), _, true),
    t((line_count(drv_w2, _L0), get_char(drv_w2, _A1), get_char(drv_w2, _A2), get_char(drv_w2, _A3), get_char(drv_w2, _A4),
       get_char(drv_w2, _A5), get_char(drv_w2, _A6), get_char(drv_w2, _A7), line_count(drv_w2, _L1))),
    t((character_count(drv_m2, N), get_char(drv_m2, X), get_char(drv_m2, Y), get_char(drv_m2, Z))),
    catch(close(drv_r), _, true), catch(close(drv_t), _, true), catch(close(drv_mr), _, true),
    catch(close(drv_w2), _, true), catch(close(drv_m2), _, true),
    catch(delete_file('/tmp/gnu_drv_stream_1.txt'), _, true),
    catch(delete_file('/tmp/gnu_drv_stream_2.txt'), _, true),
    catch(delete_file('/tmp/gnu_drv_stream_3.txt'), _, true),
    true.
