% term_inl_driver.pl -- grades GNU Prolog's BipsPl/term_inl.pl through the predicates it defines (Lon via the ceo, CEO-1523: every
% Prolog source file of the GNU package is graded through a driver; CEO-700, CEO-1269: a library is graded by its driver,
% NAME_driver beside it). gprolog's answer is term_inl.pl's own code; SCRIP is graded three-way against it (m3 = m4 = gprolog).
% Every predicate is called in a mode GNU Prolog's manual documents; an error prints as its ISO formal term only.
% NOT DRIVEN: nb_setarg/3 -- absent from the reference gprolog 1.4.5 (existence_error(procedure,nb_setarg/3)); the vendored term_inl.pl is 1.6.0
% Operator heads ((==)/2, (@<)/2, (=..)/2 ...) whose left operand is a compound or an atom are written t((L op R)): the extra
% parentheses only group. term_hash/2,4 and term_ref/2 values are implementation numbers: they are tested by a property
% under \+ \+ so no number prints (a Range of 1 is the one documented value: 0 =< Hash < 1). A setarg/3,4 effect is shown
% on a fresh copy_term/2 copy read back by arg/3, so the conjunction calls term_inl.pl predicates only.
:- initialization(main).

% t(G): every solution of G, or the formal error term G raises.
t(G) :- copy_term(G, C),
        catch(findall(C, C, L), E, true),
        (   var(E) -> R = L
        ;   E = error(F, _) -> R = error(F)
        ;   R = ball(E)
        ),
        \+ \+ ( numbervars(G-R, 0, _), writeq(G), write(' => '), writeq(R), nl ).

% o(G): for a goal whose effect is OUTPUT -- what it printed between < and >, then true, fail or the formal error term.
o(G) :- write('<'),
        catch(( G -> R = true ; R = fail ), E, ( E = error(F, _) -> R = error(F) ; R = ball(E) )),
        write('> '), writeq(R), nl.

main :-
    t(compare(_, 1, a)),
    t(compare(_, f(a), f(a))),
    t(compare(_, b, a)),
    t(compare(_, 1.0, 1)),
    t(compare(_, f(b), g(a, a))),
    t(compare(<, a, b)),
    t(compare(=, a, b)),
    t(compare(foo, a, b)),
    t(compare(1, a, b)),
    t(X == X),
    t((f(X, a) == f(X, a))),
    t((f(X) == f(_))),
    t(1 == 1.0),
    t(X \== _),
    t((a \== a)),
    t(1 @< a),
    t(_ @< 1),
    t((foo(a, b) @< bar(a, b, c))),
    t(1.5 @< 1),
    t((b @=< b)),
    t((f(a) @> a)),
    t((g(b) @>= g(a))),
    t((g(a) @>= g(b))),
    t(arg(2, f(a, b, c), _)),
    t(arg(1, [x|y], _)),
    t(arg(4, f(a), _)),
    t(arg(0, f(a), _)),
    t(arg(_, f(a, b), _)),
    t(arg(1, foo, _)),
    t(arg(a, f(a), _)),
    t(arg(-1, f(a), _)),
    t(functor(f(a, b), _, _)),
    t(functor([_|_], _, _)),
    t(functor(abc, _, _)),
    t(functor(_, f, 3)),
    t(functor(_, 1.5, 0)),
    t(functor(_, _, 2)),
    t(functor(_, f(a), 1)),
    t(functor(_, f, -1)),
    t(functor(_, 1.5, 1)),
    t(_ =.. [f, a, b]),
    t((f(a, g(b)) =.. _)),
    t(_ =.. [foo]),
    t(1.5 =.. _),
    t(_ =.. []),
    t(_ =.. [f(a), b]),
    t(_ =.. _),
    t(copy_term(f(X, Y, X), _)),
    t(copy_term(f(X), f(a))),
    t(copy_term(a, b)),
    t(copy_term(_, _)),
    t(setarg(1, f(a, b), z)),
    t((copy_term(f(a), T), (setarg(1, T, b), fail ; true), arg(1, T, _))),
    t((copy_term(f(a, b), T), setarg(2, T, g(x)), arg(2, T, _))),
    t(setarg(3, f(a), z)),
    t(setarg(_, f(a), z)),
    t(setarg(a, f(a), z)),
    t(setarg(1, foo, z)),
    t(setarg(-1, f(a), z)),
    t(setarg(1, f(a, b), z, true)),
    t((copy_term(f(a), T), (setarg(1, T, b, false), fail ; true), arg(1, T, _))),
    t((copy_term(f(a), T), (setarg(1, T, b, true), fail ; true), arg(1, T, _))),
    t(setarg(1, f(a), g(x), false)),
    t(setarg(1, f(a), z, maybe)),
    t(setarg(1, f(a), z, _)),
    t(term_variables(f(X, g(Y, X), _), _)),
    t(term_variables(a, _)),
    t(term_variables(f(X), [_])),
    t(term_variables(f(X, Y), [_])),
    t(term_variables(f(X), foo)),
    t(term_variables(f(X, Y), _, _)),
    t(term_variables(a, _, [z])),
    t(subsumes_term(f(_), f(a))),
    t(subsumes_term(f(a), f(_))),
    t(subsumes_term(f(X, X), f(_, _))),
    t(subsumes_term(g(X), g(f(X)))),
    t(subsumes_term(f(X, Y), f(Y, X))),
    t(acyclic_term(f(_, [a]))),
    t(acyclic_term(a)),
    t(term_hash(foo(bar), -1, 1, _)),
    t(term_hash(f(_), _)),
    t(term_hash(f(_), -1, 0, _)),
    t(\+ \+ (term_hash(f(a, [b]), H1), term_hash(f(a, [b]), H2), integer(H1), H1 == H2)),
    t(\+ \+ (term_hash(f(a), -1, 10, H), integer(H), H >= 0, H < 10)),
    t(term_hash(a, _, 0, _)),
    t(term_hash(a, x, 0, _)),
    t(term_hash(a, -1, _, _)),
    t(term_hash(a, -1, -1, _)),
    t(term_hash(a, foo)),
    t(\+ \+ (term_ref(f(a, X), R), integer(R))),
    t(\+ \+ (copy_term(g(X, b), T), term_ref(T, R), term_ref(T2, R), T2 == T)),
    t(term_ref(_, _)),
    t(term_ref(a, x)),
    t(term_ref(_, -1)),
    t((X = f(X), acyclic_term(X))),
    true.
